FROM maven:3.9-eclipse-temurin-21-alpine AS build

WORKDIR /workspace

COPY pom.xml .
RUN mvn --batch-mode --no-transfer-progress dependency:go-offline

COPY src ./src
RUN mvn --batch-mode --no-transfer-progress -DskipTests package

FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

COPY --from=build \
    /workspace/target/hok-draft-coach-0.0.1-SNAPSHOT.jar \
    /app/app.jar

ENV PORT=80

EXPOSE 80

CMD ["java", "-XX:MaxRAMPercentage=75.0", "-jar", "/app/app.jar"]
