package br.com.carlosdaniel.hokdraftcoach.repository;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Repository;

import br.com.carlosdaniel.hokdraftcoach.model.AtributosHeroi;
import br.com.carlosdaniel.hokdraftcoach.model.ClasseHeroi;
import br.com.carlosdaniel.hokdraftcoach.model.DadosMetaHeroi;
import br.com.carlosdaniel.hokdraftcoach.model.Heroi;
import br.com.carlosdaniel.hokdraftcoach.model.Rota;
import br.com.carlosdaniel.hokdraftcoach.model.TierMeta;
import br.com.carlosdaniel.hokdraftcoach.model.TipoDano;

@Repository
public class CatalogoJungleRepository {

    public static final String VERSAO_META = "S15-HOK-PLUS-2.0";
    public static final LocalDate DATA_META = LocalDate.of(2026, 7, 2);
    public static final String FONTE_META = "HOKSTATS_TIER_LIST";

    private final List<Heroi> junglers = List.of(
        j(73L, "Ata", List.of(), ClasseHeroi.HIBRIDO,
            List.of(Rota.JUNGLE, Rota.CLASH_LANE),
            "Tanque-lutador de controle de terreno e iniciação",
            3, TipoDano.FISICO, new AtributosHeroi(8, 9, 5, 3, 6, 5), TierMeta.C,
            "tanque", "iniciação", "controle de terreno", "objetivos", "linha de frente"),
        j(12L, "Butterfly", List.of(), ClasseHeroi.ASSASSINO,
            List.of(Rota.JUNGLE),
            "Assassina de execução e resets em cadeia",
            2, TipoDano.FISICO, new AtributosHeroi(2, 4, 8, 2, 6, 9), TierMeta.C,
            "assassino", "reset", "execução", "limpeza", "snowball"),
        j(74L, "Fatih", List.of(), ClasseHeroi.LUTADOR,
            List.of(Rota.JUNGLE, Rota.CLASH_LANE),
            "Lutador berserker de roubo de vida e trocas prolongadas",
            4, TipoDano.FISICO, new AtributosHeroi(4, 7, 6, 2, 9, 7), TierMeta.C,
            "sustentação", "duelo", "roubo de vida", "anti-controle", "lutas longas"),
        j(22L, "Agudo", List.of("Agu", "Aguu"), ClasseHeroi.ATIRADOR,
            List.of(Rota.JUNGLE, Rota.FARM_LANE),
            "Atiradora resistente de pressão, buffs e controle de objetivos",
            3, TipoDano.FISICO, new AtributosHeroi(6, 8, 5, 8, 7, 4), TierMeta.C,
            "atirador jungle", "buffs de equipe", "objetivos", "poke", "início de jogo"),
        j(75L, "Arke", List.of("A Ke"), ClasseHeroi.ASSASSINO,
            List.of(Rota.JUNGLE),
            "Assassina furtiva de flanco, crítico e resets",
            4, TipoDano.FISICO, new AtributosHeroi(2, 3, 9, 2, 6, 10), TierMeta.B,
            "assassino", "furtividade", "flanco", "reset", "execução"),
        j(8L, "Arthur", List.of(), ClasseHeroi.LUTADOR,
            List.of(Rota.JUNGLE, Rota.CLASH_LANE),
            "Lutador resistente de silêncio e iniciação simples",
            1, TipoDano.MISTO, new AtributosHeroi(7, 9, 5, 2, 6, 6), TierMeta.B,
            "linha de frente", "silêncio", "iniciação", "anti-mobilidade", "segurança"),
        j(76L, "Athena", List.of(), ClasseHeroi.HIBRIDO,
            List.of(Rota.JUNGLE),
            "Lutadora-assassina de escudos, perseguição e pressão após a morte",
            4, TipoDano.FISICO, new AtributosHeroi(5, 6, 9, 2, 8, 8), TierMeta.C,
            "escudo", "mobilidade", "duelo", "invasão", "pressão"),
        j(77L, "Augran", List.of(), ClasseHeroi.HIBRIDO,
            List.of(Rota.JUNGLE, Rota.CLASH_LANE),
            "Lutador dominante de execução, sustentação e presença em objetivos",
            3, TipoDano.MISTO, new AtributosHeroi(6, 9, 8, 3, 10, 9), TierMeta.S,
            "execução", "sustentação", "anti-tanque", "objetivos", "linha de frente"),
        j(24L, "Chano", List.of(), ClasseHeroi.ATIRADOR,
            List.of(Rota.FARM_LANE, Rota.JUNGLE),
            "Atirador de artilharia, iniciação e limpeza tardia",
            3, TipoDano.FISICO, new AtributosHeroi(5, 3, 5, 9, 9, 7), TierMeta.B,
            "atirador jungle", "artilharia", "limpeza", "fim de jogo", "front-to-back"),
        j(78L, "Charlotte", List.of("Charlottr"), ClasseHeroi.LUTADOR,
            List.of(Rota.JUNGLE, Rota.CLASH_LANE),
            "Duelista móvel de redução de dano e combos contínuos",
            4, TipoDano.FISICO, new AtributosHeroi(5, 7, 8, 3, 9, 7), TierMeta.B,
            "duelo", "mobilidade", "redução de dano", "dano sustentado", "flanco"),
        j(25L, "Chicha", List.of(), ClasseHeroi.LUTADOR,
            List.of(Rota.CLASH_LANE, Rota.JUNGLE, Rota.FARM_LANE),
            "Lutadora de velocidade de ataque e limpeza após o primeiro engage",
            2, TipoDano.FISICO, new AtributosHeroi(5, 7, 8, 4, 10, 7), TierMeta.A,
            "velocidade de ataque", "limpeza", "segundo engage", "duelo", "flex"),
        j(79L, "Cirrus", List.of(), ClasseHeroi.HIBRIDO,
            List.of(Rota.JUNGLE),
            "Assassino-lutador de voo, mobilidade e acesso à retaguarda",
            4, TipoDano.FISICO, new AtributosHeroi(4, 5, 10, 3, 8, 8), TierMeta.C,
            "voo", "mobilidade", "dive", "backline", "rotação"),
        j(80L, "Dharma", List.of(), ClasseHeroi.LUTADOR,
            List.of(Rota.JUNGLE, Rota.CLASH_LANE),
            "Lutador de controle contra paredes, explosão e iniciação",
            3, TipoDano.FISICO, new AtributosHeroi(9, 7, 7, 2, 7, 9), TierMeta.C,
            "controle", "parede", "iniciação", "explosão", "pickoff"),
        j(81L, "Dian Wei", List.of(), ClasseHeroi.LUTADOR,
            List.of(Rota.JUNGLE),
            "Lutador de dano verdadeiro, perseguição e escalamento por eliminações",
            2, TipoDano.MISTO, new AtributosHeroi(4, 7, 7, 2, 10, 9), TierMeta.B,
            "dano verdadeiro", "anti-tanque", "duelo", "escalamento", "perseguição"),
        j(28L, "Fang", List.of("Li Yuanfang"), ClasseHeroi.ATIRADOR,
            List.of(Rota.FARM_LANE, Rota.JUNGLE),
            "Atirador flex de explosão e controle rápido de objetivos",
            3, TipoDano.FISICO, new AtributosHeroi(3, 3, 8, 7, 8, 9), TierMeta.B,
            "atirador jungle", "explosão", "objetivos", "início de jogo", "mobilidade"),
        j(82L, "Feyd", List.of(), ClasseHeroi.ASSASSINO,
            List.of(Rota.JUNGLE),
            "Assassino de terreno, emboscada e explosão lateral",
            4, TipoDano.FISICO, new AtributosHeroi(4, 4, 10, 3, 6, 10), TierMeta.C,
            "assassino", "terreno", "emboscada", "explosão", "flanco"),
        j(83L, "Gao Changgong", List.of("Prince of Lanling"), ClasseHeroi.ASSASSINO,
            List.of(Rota.JUNGLE),
            "Assassino furtivo de pressão precoce e pickoff",
            3, TipoDano.FISICO, new AtributosHeroi(4, 3, 9, 2, 5, 10), TierMeta.B,
            "furtividade", "pickoff", "gank", "início de jogo", "explosão"),
        j(84L, "Han Xin", List.of(), ClasseHeroi.ASSASSINO,
            List.of(Rota.JUNGLE),
            "Assassino de mobilidade extrema, invasão e split push",
            5, TipoDano.FISICO, new AtributosHeroi(5, 3, 10, 2, 8, 8), TierMeta.C,
            "mobilidade", "invasão", "split push", "farm", "objetivos"),
        j(85L, "Jing", List.of(), ClasseHeroi.ASSASSINO,
            List.of(Rota.JUNGLE),
            "Assassina mecânica de espelhos, execução e mobilidade extrema",
            5, TipoDano.FISICO, new AtributosHeroi(4, 3, 10, 3, 8, 10), TierMeta.C,
            "espelhos", "mobilidade", "execução", "duelo", "outplay"),
        j(86L, "Kaizer", List.of("Kaiser"), ClasseHeroi.LUTADOR,
            List.of(Rota.JUNGLE, Rota.CLASH_LANE),
            "Lutador de duelo, transformação e pressão sobre carregadores",
            2, TipoDano.FISICO, new AtributosHeroi(4, 9, 7, 2, 9, 9), TierMeta.A,
            "duelo", "transformação", "linha de frente", "explosão", "anti-carry"),
        j(20L, "Kongming", List.of("Zhuge Liang", "Kong Ming"), ClasseHeroi.MAGO,
            List.of(Rota.MID_LANE, Rota.JUNGLE),
            "Mago-assassino móvel de execução e resets",
            4, TipoDano.MAGICO, new AtributosHeroi(4, 3, 9, 6, 7, 10), TierMeta.A,
            "mago jungle", "execução", "reset", "mobilidade", "snowball"),
        j(11L, "Lam", List.of(), ClasseHeroi.ASSASSINO,
            List.of(Rota.JUNGLE),
            "Assassino móvel de execução, perseguição e controle de rio",
            4, TipoDano.FISICO, new AtributosHeroi(4, 4, 10, 2, 7, 10), TierMeta.B,
            "assassino", "execução", "mobilidade", "rio", "pickoff"),
        j(87L, "Li Bai", List.of(), ClasseHeroi.ASSASSINO,
            List.of(Rota.JUNGLE),
            "Assassino de entradas curtas, invulnerabilidade e poke explosivo",
            5, TipoDano.FISICO, new AtributosHeroi(4, 3, 10, 4, 7, 9), TierMeta.B,
            "invulnerabilidade", "mobilidade", "poke", "explosão", "outplay"),
        j(88L, "Liu Bei", List.of(), ClasseHeroi.HIBRIDO,
            List.of(Rota.JUNGLE),
            "Atirador-lutador de invasão, duelo e dano próximo",
            3, TipoDano.FISICO, new AtributosHeroi(4, 7, 7, 4, 10, 8), TierMeta.C,
            "invasão", "duelo", "dano próximo", "objetivos", "escudo"),
        j(89L, "Luna", List.of(), ClasseHeroi.HIBRIDO,
            List.of(Rota.JUNGLE),
            "Assassina mágica de resets, mobilidade e dano sustentado",
            5, TipoDano.MAGICO, new AtributosHeroi(5, 4, 10, 3, 9, 9), TierMeta.C,
            "mago jungle", "reset", "mobilidade", "dano sustentado", "duelo"),
        j(90L, "Mayene", List.of(), ClasseHeroi.LUTADOR,
            List.of(Rota.JUNGLE, Rota.CLASH_LANE),
            "Lutadora de combos, controle e alta flexibilidade mecânica",
            5, TipoDano.FISICO, new AtributosHeroi(8, 6, 9, 3, 8, 8), TierMeta.C,
            "combos", "controle", "mobilidade", "duelo", "flanco"),
        j(91L, "Menki", List.of("Meng Qi"), ClasseHeroi.HIBRIDO,
            List.of(Rota.JUNGLE, Rota.CLASH_LANE),
            "Lutador resistente de escudos, dano misto e controle de espaço",
            3, TipoDano.MISTO, new AtributosHeroi(6, 9, 5, 3, 9, 7), TierMeta.C,
            "escudo", "dano misto", "linha de frente", "duelo", "objetivos"),
        j(92L, "Mi Yue", List.of(), ClasseHeroi.HIBRIDO,
            List.of(Rota.JUNGLE, Rota.CLASH_LANE),
            "Maga-lutadora de sustentação, duelo e pressão lateral",
            4, TipoDano.MAGICO, new AtributosHeroi(4, 7, 8, 5, 9, 6), TierMeta.B,
            "sustentação", "duelo", "split push", "dano mágico", "invulnerabilidade"),
        j(93L, "Musashi", List.of("Miyamoto Musashi"), ClasseHeroi.LUTADOR,
            List.of(Rota.JUNGLE, Rota.CLASH_LANE),
            "Lutador de bloqueio de projéteis, anti-cura e foco em carregadores",
            3, TipoDano.FISICO, new AtributosHeroi(6, 8, 7, 2, 8, 9), TierMeta.B,
            "anti-cura", "bloqueio de projéteis", "duelo", "anti-carry", "dive"),
        j(13L, "Nakoruru", List.of(), ClasseHeroi.ASSASSINO,
            List.of(Rota.JUNGLE),
            "Assassina de explosão física, mobilidade e dano percentual",
            3, TipoDano.FISICO, new AtributosHeroi(2, 3, 9, 2, 6, 10), TierMeta.C,
            "assassino", "explosão", "mobilidade", "dano percentual", "gank"),
        j(94L, "Pei", List.of("Pei Qinhu"), ClasseHeroi.HIBRIDO,
            List.of(Rota.JUNGLE),
            "Lutador de duas formas, invasão e ritmo de início de jogo",
            5, TipoDano.MISTO, new AtributosHeroi(4, 5, 9, 6, 9, 8), TierMeta.C,
            "duas formas", "invasão", "início de jogo", "poke", "objetivos"),
        j(68L, "Sima Yi", List.of(), ClasseHeroi.HIBRIDO,
            List.of(Rota.MID_LANE, Rota.JUNGLE),
            "Assassino mágico de silêncio, acesso global e explosão",
            5, TipoDano.MAGICO, new AtributosHeroi(7, 3, 10, 5, 6, 10), TierMeta.B,
            "mago jungle", "silêncio", "acesso global", "explosão", "anti-mago"),
        j(95L, "Sun Ce", List.of(), ClasseHeroi.HIBRIDO,
            List.of(Rota.JUNGLE, Rota.CLASH_LANE),
            "Lutador-tanque de iniciação global e controle em cadeia",
            3, TipoDano.FISICO, new AtributosHeroi(9, 8, 9, 3, 7, 8), TierMeta.B,
            "iniciação global", "controle", "linha de frente", "gank", "rotação"),
        j(96L, "Ukyo Tachibana", List.of("Ukyo"), ClasseHeroi.HIBRIDO,
            List.of(Rota.JUNGLE, Rota.CLASH_LANE),
            "Assassino-lutador de poke curto, controle e explosão",
            4, TipoDano.FISICO, new AtributosHeroi(7, 5, 7, 5, 6, 9), TierMeta.C,
            "poke", "controle", "explosão", "duelo", "início de jogo"),
        j(97L, "Umbrosa", List.of(), ClasseHeroi.LUTADOR,
            List.of(Rota.JUNGLE, Rota.CLASH_LANE),
            "Lutadora de dano sustentado, cura e ressurreição",
            2, TipoDano.FISICO, new AtributosHeroi(5, 8, 7, 3, 10, 7), TierMeta.C,
            "sustentação", "ressurreição", "dano sustentado", "linha de frente", "duelo"),
        j(98L, "Wukong", List.of("Sun Wukong"), ClasseHeroi.ASSASSINO,
            List.of(Rota.JUNGLE),
            "Assassino de crítico, explosão e acesso rápido à retaguarda",
            3, TipoDano.FISICO, new AtributosHeroi(4, 4, 9, 2, 6, 10), TierMeta.A,
            "crítico", "explosão", "assassino", "dive", "snowball"),
        j(99L, "Wuyan", List.of("Zhong Wuyan"), ClasseHeroi.HIBRIDO,
            List.of(Rota.JUNGLE, Rota.CLASH_LANE),
            "Lutadora-tanque de petrificação e explosão em área",
            2, TipoDano.FISICO, new AtributosHeroi(9, 8, 6, 2, 7, 8), TierMeta.C,
            "petrificação", "controle", "linha de frente", "dano em área", "gank"),
        j(100L, "Yang Jian", List.of(), ClasseHeroi.LUTADOR,
            List.of(Rota.JUNGLE, Rota.CLASH_LANE),
            "Lutador de execução, sustain e perseguição de alvos marcados",
            4, TipoDano.MISTO, new AtributosHeroi(6, 7, 8, 4, 8, 9), TierMeta.C,
            "execução", "sustentação", "perseguição", "duelo", "dano verdadeiro"),
        j(101L, "Yao", List.of(), ClasseHeroi.HIBRIDO,
            List.of(Rota.JUNGLE, Rota.CLASH_LANE),
            "Assassino-lutador de combos, mobilidade e dano retardado",
            4, TipoDano.FISICO, new AtributosHeroi(5, 6, 9, 3, 8, 8), TierMeta.C,
            "combos", "mobilidade", "dano retardado", "duelo", "flanco"),
        j(102L, "Ying", List.of("Yun Ying"), ClasseHeroi.LUTADOR,
            List.of(Rota.JUNGLE),
            "Lutadora de lança, controle, execução e dano adaptável",
            4, TipoDano.FISICO, new AtributosHeroi(7, 7, 8, 4, 9, 8), TierMeta.B,
            "controle", "execução", "dano sustentado", "duelo", "flexibilidade"),
        j(103L, "Zilong", List.of("Zhao Yun"), ClasseHeroi.HIBRIDO,
            List.of(Rota.JUNGLE),
            "Lutador-assassino de entrada direta e foco em carregadores",
            2, TipoDano.FISICO, new AtributosHeroi(7, 7, 8, 2, 7, 9), TierMeta.C,
            "dive", "controle", "anti-carry", "explosão", "linha de frente"),
        j(104L, "Xuance", List.of("Baili Xuance"), ClasseHeroi.ASSASSINO,
            List.of(Rota.JUNGLE),
            "Assassino de gancho, mobilidade e limpeza após eliminações",
            4, TipoDano.FISICO, new AtributosHeroi(8, 3, 10, 5, 7, 9), TierMeta.C,
            "gancho", "assassino", "reset", "pickoff", "mobilidade"),
        j(105L, "Yango", List.of("Yuan Ge", "Yuan ge"), ClasseHeroi.ASSASSINO,
            List.of(Rota.JUNGLE),
            "Assassino de marionete, iniciação móvel e pickoff",
            5, TipoDano.FISICO, new AtributosHeroi(8, 3, 10, 5, 6, 10), TierMeta.C,
            "marionete", "assassino", "pickoff", "iniciação", "mobilidade")
    );

    public List<Heroi> listarTodos() {
        return junglers;
    }

    public Optional<Heroi> buscarPorNome(String nome) {
        return junglers.stream()
            .filter(heroi -> heroi.correspondeAoNome(nome))
            .findFirst();
    }

    public Optional<Heroi> buscarPorId(Long id) {
        return junglers.stream()
            .filter(heroi -> heroi.getId().equals(id))
            .findFirst();
    }

    private Heroi j(
        Long id,
        String nome,
        List<String> aliases,
        ClasseHeroi classe,
        List<Rota> rotasPossiveis,
        String estilo,
        int dificuldade,
        TipoDano tipoDano,
        AtributosHeroi atributos,
        TierMeta tier,
        String... caracteristicas
    ) {
        return new Heroi(
            id,
            nome,
            aliases,
            classe,
            Rota.JUNGLE,
            rotasPossiveis,
            estilo,
            dificuldade,
            tipoDano,
            atributos,
            List.of(caracteristicas),
            new DadosMetaHeroi(
                tier,
                VERSAO_META,
                DATA_META,
                FONTE_META,
                false
            )
        );
    }
}
