package br.com.carlosdaniel.hokdraftcoach.repository;

import java.util.List;

import org.springframework.stereotype.Repository;

import br.com.carlosdaniel.hokdraftcoach.model.ConfiancaDado;
import br.com.carlosdaniel.hokdraftcoach.model.ConfrontoClashLane;
import br.com.carlosdaniel.hokdraftcoach.model.TipoVantagemClash;

@Repository
public class ConfrontoClashRepository {

    private final List<ConfrontoClashLane> confrontos = List.of(
        m("Florentino", "Arthur", 9, ConfiancaDado.ALTA,
            "Mobilidade, sustain e dano prolongado superam o padrão linear de Arthur.",
            TipoVantagemClash.DUELO, TipoVantagemClash.SUSTENTACAO),
        m("Florentino", "Ata", 9, ConfiancaDado.MEDIA,
            "Reposicionamento evita o controle de terreno e transforma o tanque em fonte de cura.",
            TipoVantagemClash.DUELO, TipoVantagemClash.MECANICA),
        m("Florentino", "Dun", 8, ConfiancaDado.MEDIA,
            "Dano contínuo e mobilidade desgastam escudo e sustain sem aceitar troca frontal.",
            TipoVantagemClash.DUELO, TipoVantagemClash.SUSTENTACAO),
        m("Florentino", "Lu Bu", 8, ConfiancaDado.MEDIA,
            "Pode reposicionar entre os ataques lentos e evitar a zona da ultimate.",
            TipoVantagemClash.DUELO, TipoVantagemClash.MECANICA),
        m("Florentino", "Kaizer", 8, ConfiancaDado.MEDIA,
            "Mobilidade permite esperar a transformação e retomar o duelo depois.",
            TipoVantagemClash.DUELO, TipoVantagemClash.MECANICA),
        m("Donghuang", "Florentino", 9, ConfiancaDado.ALTA,
            "Supressão inevitável remove a mobilidade e impede a sequência de flores.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.LUTA),
        m("Fuzi", "Florentino", 8, ConfiancaDado.MEDIA,
            "Aprisionamento reduz o espaço de reposicionamento e força duelo estático.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.DUELO),
        m("Arthur", "Florentino", 7, ConfiancaDado.EXPLORATORIA,
            "Silêncio cria uma janela curta para negar a sequência, mas não vence o duelo prolongado.",
            TipoVantagemClash.MECANICA),

        m("Devara", "Arthur", 8, ConfiancaDado.EXPLORATORIA,
            "Escudo, mobilidade e anti-controle vencem trocas curtas repetidas.",
            TipoVantagemClash.DUELO, TipoVantagemClash.SUSTENTACAO),
        m("Devara", "Biron", 8, ConfiancaDado.EXPLORATORIA,
            "Anti-controle e escudo reduzem o pico inicial e permitem prolongar a troca.",
            TipoVantagemClash.DUELO, TipoVantagemClash.MECANICA),
        m("Devara", "Wuyan", 7, ConfiancaDado.EXPLORATORIA,
            "Imunidade a controle durante a ultimate reduz a janela de petrificação.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.LUTA),
        m("Mi Yue", "Devara", 7, ConfiancaDado.EXPLORATORIA,
            "Alcance, sustain e invulnerabilidade evitam o contato contínuo do herói novo.",
            TipoVantagemClash.DUELO, TipoVantagemClash.MECANICA),

        m("Augran", "Ata", 9, ConfiancaDado.ALTA,
            "Execução e dano sustentado atravessam a linha de frente de Ata.",
            TipoVantagemClash.DUELO, TipoVantagemClash.LUTA),
        m("Augran", "Bai Qi", 9, ConfiancaDado.MEDIA,
            "Sustain e execução reduzem o valor da cura e da alta vida do tanque.",
            TipoVantagemClash.DUELO, TipoVantagemClash.SUSTENTACAO),
        m("Augran", "Menki", 9, ConfiancaDado.ALTA,
            "Dano prolongado e execução superam escudos e resistência.",
            TipoVantagemClash.DUELO, TipoVantagemClash.LUTA),
        m("Augran", "Umbrosa", 8, ConfiancaDado.MEDIA,
            "Mantém pressão durante a ressurreição e executa a segunda barra de vida.",
            TipoVantagemClash.DUELO, TipoVantagemClash.LUTA),
        m("Musashi", "Augran", 8, ConfiancaDado.MEDIA,
            "Anti-cura reduz a sustentação que mantém Augran no combate.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.DUELO),

        m("Allain", "Ata", 8, ConfiancaDado.MEDIA,
            "Dano misto e invulnerabilidade punem uma frontline com pouca ameaça de burst.",
            TipoVantagemClash.DUELO, TipoVantagemClash.ESCALAMENTO),
        m("Allain", "Bai Qi", 8, ConfiancaDado.MEDIA,
            "Escalamento e dano misto vencem o tanque quando o controle principal não mata.",
            TipoVantagemClash.DUELO, TipoVantagemClash.ESCALAMENTO),
        m("Allain", "Xiang Yu", 8, ConfiancaDado.MEDIA,
            "Dano sustentado e misto reduzem o valor da mitigação física.",
            TipoVantagemClash.DUELO, TipoVantagemClash.ESCALAMENTO),
        m("Biron", "Allain", 8, ConfiancaDado.MEDIA,
            "Pressão e sustain precoce exploram a fase inicial mais fraca de Allain.",
            TipoVantagemClash.ROTA, TipoVantagemClash.SUSTENTACAO),
        m("Ukyo Tachibana", "Allain", 7, ConfiancaDado.MEDIA,
            "Poke e burst inicial atrasam o escalamento antes do duelo prolongado.",
            TipoVantagemClash.ROTA, TipoVantagemClash.DUELO),

        m("Diaochan", "Ata", 9, ConfiancaDado.MEDIA,
            "Dano verdadeiro, mobilidade e invulnerabilidade castigam o tanque imóvel.",
            TipoVantagemClash.DUELO, TipoVantagemClash.MECANICA),
        m("Diaochan", "Dun", 8, ConfiancaDado.MEDIA,
            "Dano verdadeiro e mobilidade evitam controles previsíveis e escudos.",
            TipoVantagemClash.DUELO, TipoVantagemClash.SUSTENTACAO),
        m("Diaochan", "Lu Bu", 8, ConfiancaDado.MEDIA,
            "Mobilidade dentro da ultimate evita ataques lentos e mantém DPS verdadeiro.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.DUELO),
        m("Arthur", "Diaochan", 9, ConfiancaDado.ALTA,
            "Silêncio interrompe os dashes e cria a janela de burst antes da invulnerabilidade.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.LUTA),
        m("Donghuang", "Diaochan", 9, ConfiancaDado.ALTA,
            "Supressão ignora mobilidade e remove a maga da zona da própria ultimate.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.LUTA),
        m("Fuzi", "Diaochan", 8, ConfiancaDado.MEDIA,
            "Aprisionamento limita a área dos dashes e força luta fora do círculo ideal.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.DUELO),

        m("Mi Yue", "Arthur", 8, ConfiancaDado.ALTA,
            "Alcance, sustain e invulnerabilidade desgastam Arthur sem aceitar all-in.",
            TipoVantagemClash.DUELO, TipoVantagemClash.SUSTENTACAO),
        m("Mi Yue", "Kaizer", 8, ConfiancaDado.MEDIA,
            "Kite e invulnerabilidade consomem a duração da transformação.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.DUELO),
        m("Mi Yue", "Dian Wei", 8, ConfiancaDado.MEDIA,
            "Distância e sustain impedem contato contínuo do lutador linear.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.DUELO),
        m("Musashi", "Mi Yue", 8, ConfiancaDado.ALTA,
            "Anti-cura e foco direto reduzem o sustain e forçam a ultimate defensiva.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.DUELO),
        m("Nezha", "Mi Yue", 8, ConfiancaDado.MEDIA,
            "Anti-cura e perseguição global reduzem a capacidade de escapar pela lateral.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.ROTACAO),

        m("Musashi", "Fatih", 9, ConfiancaDado.ALTA,
            "Anti-cura ataca diretamente o roubo de vida que sustenta Fatih.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.DUELO),
        m("Musashi", "Biron", 8, ConfiancaDado.ALTA,
            "Anti-cura e bloqueio de projéteis reduzem sustain e engage inicial.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.DUELO),
        m("Musashi", "Umbrosa", 9, ConfiancaDado.ALTA,
            "Anti-cura reduz a recuperação antes e depois da ressurreição.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.LUTA),
        m("Nezha", "Fatih", 8, ConfiancaDado.MEDIA,
            "Anti-cura e contato contínuo impedem que o berserker recupere toda a vida.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.DUELO),
        m("Nezha", "Umbrosa", 8, ConfiancaDado.MEDIA,
            "Anti-cura mantém a segunda vida vulnerável e permite perseguição após o retorno.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.LUTA),

        m("Fuzi", "Guan Yu", 9, ConfiancaDado.ALTA,
            "Aprisionamento remove a corrida e impede o ciclo de deslocamentos.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.DUELO),
        m("Fuzi", "Yao", 8, ConfiancaDado.MEDIA,
            "Ultimate prende o herói móvel e evita a retirada após o combo.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.DUELO),
        m("Fuzi", "Charlotte", 8, ConfiancaDado.MEDIA,
            "Aprisionamento reduz mobilidade e transforma o combate em DPS básico.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.DUELO),
        m("Fuzi", "Heino", 8, ConfiancaDado.MEDIA,
            "Split push e aprisionamento punem o mago quando alcançado na lateral.",
            TipoVantagemClash.SPLIT_PUSH, TipoVantagemClash.DUELO),
        m("Guan Yu", "Heino", 8, ConfiancaDado.MEDIA,
            "Rotação e flanco fecham a distância antes do poke controlar a luta.",
            TipoVantagemClash.ROTACAO, TipoVantagemClash.MECANICA),
        m("Mulan", "Heino", 8, ConfiancaDado.MEDIA,
            "Silêncio e burst impedem retorno temporal quando o flanco conecta.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.DUELO),
        m("Heino", "Ata", 8, ConfiancaDado.MEDIA,
            "Alcance e sustain controlam o tanque sem entrar na zona de paredes.",
            TipoVantagemClash.ROTA, TipoVantagemClash.SUSTENTACAO),
        m("Heino", "Lapulapu", 8, ConfiancaDado.MEDIA,
            "Poke e cura neutralizam um tanque com pouco alcance de ameaça.",
            TipoVantagemClash.ROTA, TipoVantagemClash.SUSTENTACAO),

        m("Li Xin", "Liu Bang", 8, ConfiancaDado.MEDIA,
            "Wave clear e pressão de torre castigam cada rotação global de Liu Bang.",
            TipoVantagemClash.SPLIT_PUSH, TipoVantagemClash.WAVE_CLEAR),
        m("Li Xin", "Bai Qi", 8, ConfiancaDado.MEDIA,
            "Poke e pressão lateral evitam a provocação e forçam o tanque a perder torres.",
            TipoVantagemClash.ROTA, TipoVantagemClash.SPLIT_PUSH),
        m("Li Xin", "Zhuangzi", 8, ConfiancaDado.MEDIA,
            "Pressão de torre e dano físico sustentado punem a utilidade sem wave clear superior.",
            TipoVantagemClash.SPLIT_PUSH, TipoVantagemClash.WAVE_CLEAR),
        m("Dharma", "Li Xin", 8, ConfiancaDado.MEDIA,
            "Controle em parede interrompe a forma de pressão e cria burst antes da fuga.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.DUELO),
        m("Mayene", "Li Xin", 8, ConfiancaDado.MEDIA,
            "Mobilidade e deslocamentos alcançam a forma de poke e interrompem o carregamento.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.DUELO),

        m("Zhuangzi", "Bai Qi", 9, ConfiancaDado.ALTA,
            "Purificação remove a provocação e quebra o principal motivo do engage.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.LUTA),
        m("Zhuangzi", "Lian Po", 8, ConfiancaDado.ALTA,
            "Limpeza de controle reduz o follow-up das múltiplas entradas.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.LUTA),
        m("Zhuangzi", "Wuyan", 9, ConfiancaDado.ALTA,
            "Purificação coletiva neutraliza petrificação e protege a formação.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.LUTA),
        m("Zhuangzi", "Dharma", 8, ConfiancaDado.ALTA,
            "Anti-controle reduz o valor do combo contra parede.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.LUTA),
        m("Zhuangzi", "Donghuang", 6, ConfiancaDado.MEDIA,
            "Responde aos controles secundários, mas não remove a supressão inevitável.",
            TipoVantagemClash.LUTA),

        m("Xiang Yu", "Arthur", 8, ConfiancaDado.ALTA,
            "Deslocamento e mitigação impedem Arthur de permanecer sobre o carry.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.LUTA),
        m("Xiang Yu", "Kaizer", 8, ConfiancaDado.MEDIA,
            "Pode afastar a transformação do carregador e consumir sua duração.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.LUTA),
        m("Xiang Yu", "Nezha", 8, ConfiancaDado.MEDIA,
            "Peel e deslocamento reduzem o valor da chegada global ao carry.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.LUTA),

        m("Lu Bu", "Ata", 8, ConfiancaDado.ALTA,
            "Dano verdadeiro pune a alta resistência e a luta agrupada do tanque.",
            TipoVantagemClash.DUELO, TipoVantagemClash.LUTA),
        m("Lu Bu", "Bai Qi", 8, ConfiancaDado.ALTA,
            "Dano verdadeiro atravessa defesa e sustain quando consegue manter contato.",
            TipoVantagemClash.DUELO, TipoVantagemClash.SUSTENTACAO),
        m("Lu Bu", "Menki", 8, ConfiancaDado.ALTA,
            "Dano verdadeiro reduz a eficiência dos escudos e da resistência.",
            TipoVantagemClash.DUELO, TipoVantagemClash.MECANICA),
        m("Guan Yu", "Lu Bu", 8, ConfiancaDado.MEDIA,
            "Deslocamentos repetidos impedem Lu Bu de manter a zona e acertar ataques lentos.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.ROTACAO),
        m("Mi Yue", "Lu Bu", 8, ConfiancaDado.MEDIA,
            "Kite e invulnerabilidade evitam o dano verdadeiro sustentado.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.DUELO),

        m("Biron", "Mulan", 8, ConfiancaDado.MEDIA,
            "Sustain e escudo sobrevivem ao burst inicial e vencem a troca estendida.",
            TipoVantagemClash.ROTA, TipoVantagemClash.SUSTENTACAO),
        m("Mulan", "Heino", 8, ConfiancaDado.MEDIA,
            "Silêncio e burst punem o mago antes do retorno temporal.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.DUELO),
        m("Mulan", "Diaochan", 8, ConfiancaDado.MEDIA,
            "Silêncio limita os dashes e permite burst antes da luta prolongada.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.DUELO),
        m("Donghuang", "Mulan", 8, ConfiancaDado.MEDIA,
            "Supressão impede a troca de forma e elimina a margem de outplay.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.LUTA),

        m("Dharma", "Heino", 8, ConfiancaDado.MEDIA,
            "Acesso por parede e burst fecham a distância contra o mago de poke.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.DUELO),
        m("Dharma", "Diaochan", 7, ConfiancaDado.MEDIA,
            "Controle em parede pode negar os dashes se o timing for preciso.",
            TipoVantagemClash.MECANICA),
        m("Dharma", "Guan Yu", 8, ConfiancaDado.MEDIA,
            "Knockback e parede interrompem a corrida e removem a passiva de movimento.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.DUELO),

        m("Sun Ce", "Heino", 8, ConfiancaDado.MEDIA,
            "Iniciação global fecha a distância antes do poke e força retorno defensivo.",
            TipoVantagemClash.ROTACAO, TipoVantagemClash.MECANICA),
        m("Sun Ce", "Diaochan", 7, ConfiancaDado.MEDIA,
            "Controle em cadeia cria uma janela curta antes dos dashes.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.LUTA),
        m("Liu Bang", "Sun Ce", 7, ConfiancaDado.MEDIA,
            "Proteção global responde à iniciação em outra rota e reduz a superioridade numérica.",
            TipoVantagemClash.ROTACAO, TipoVantagemClash.LUTA),

        m("Wuyan", "Yao", 8, ConfiancaDado.MEDIA,
            "Petrificação pune a permanência curta após os combos de mobilidade.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.DUELO),
        m("Wuyan", "Mayene", 8, ConfiancaDado.MEDIA,
            "Controle em área reduz os caminhos seguros dos combos e deslocamentos.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.LUTA),
        m("Arthur", "Yao", 8, ConfiancaDado.ALTA,
            "Silêncio interrompe a sequência e impede o retorno seguro.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.DUELO),
        m("Arthur", "Mayene", 8, ConfiancaDado.MEDIA,
            "Silêncio simplifica o duelo contra um kit dependente de combinações.",
            TipoVantagemClash.MECANICA, TipoVantagemClash.DUELO)
    );

    public List<ConfrontoClashLane> listarTodos() {
        return confrontos;
    }

    private ConfrontoClashLane m(
        String vencedor,
        String alvo,
        int vantagem,
        ConfiancaDado confianca,
        String motivo,
        TipoVantagemClash... tipos
    ) {
        return new ConfrontoClashLane(
            vencedor,
            alvo,
            vantagem,
            confianca,
            List.of(tipos),
            motivo
        );
    }
}
