package br.com.carlosdaniel.hokdraftcoach.repository;

import java.util.List;

import org.springframework.stereotype.Repository;

import br.com.carlosdaniel.hokdraftcoach.model.ConfiancaDado;
import br.com.carlosdaniel.hokdraftcoach.model.ConfrontoJungle;
import br.com.carlosdaniel.hokdraftcoach.model.TipoVantagemJungle;

@Repository
public class ConfrontoJungleRepository {

    private final List<ConfrontoJungle> confrontos = List.of(
        m("Augran", "Ata", 9, ConfiancaDado.ALTA,
            "Execução e dano prolongado atravessam a linha de frente de Ata.",
            TipoVantagemJungle.DUELO, TipoVantagemJungle.LUTA),
        m("Augran", "Menki", 9, ConfiancaDado.ALTA,
            "Sustentação e execução reduzem o valor dos escudos e da resistência.",
            TipoVantagemJungle.DUELO, TipoVantagemJungle.LUTA),
        m("Augran", "Umbrosa", 8, ConfiancaDado.MEDIA,
            "Consegue manter pressão durante a ressurreição e executar na segunda fase.",
            TipoVantagemJungle.DUELO, TipoVantagemJungle.LUTA),
        m("Augran", "Arthur", 8, ConfiancaDado.MEDIA,
            "Dano sustentado e execução vencem a troca longa contra o tanque simples.",
            TipoVantagemJungle.DUELO, TipoVantagemJungle.ESCALAMENTO),
        m("Augran", "Dian Wei", 8, ConfiancaDado.MEDIA,
            "Maior alcance de ameaça e sustain dificultam o duelo linear de Dian Wei.",
            TipoVantagemJungle.DUELO, TipoVantagemJungle.LUTA),

        m("Ata", "Agu", 9, ConfiancaDado.ALTA,
            "Controle de terreno e iniciação fecham a distância contra a atiradora jungle.",
            TipoVantagemJungle.GANK, TipoVantagemJungle.LUTA),
        m("Han Xin", "Agu", 9, ConfiancaDado.ALTA,
            "Invasão e mobilidade punem uma jungler dependente de posicionamento e farm.",
            TipoVantagemJungle.INVASAO, TipoVantagemJungle.MAPA),
        m("Sima Yi", "Agu", 8, ConfiancaDado.MEDIA,
            "Acesso global e silêncio atravessam o poke e alcançam a retaguarda.",
            TipoVantagemJungle.GANK, TipoVantagemJungle.MECANICA),
        m("Gao Changgong", "Agu", 8, ConfiancaDado.MEDIA,
            "Furtividade remove o tempo de reação da atiradora e força proteção constante.",
            TipoVantagemJungle.GANK, TipoVantagemJungle.MECANICA),
        m("Agu", "Kongming", 7, ConfiancaDado.ALTA,
            "Pressão à distância e buffs dificultam que Kongming alcance a faixa de execução.",
            TipoVantagemJungle.LUTA, TipoVantagemJungle.OBJETIVOS),

        m("Liu Bei", "Butterfly", 9, ConfiancaDado.ALTA,
            "Escudo e dano próximo vencem o primeiro all-in e impedem o reset.",
            TipoVantagemJungle.DUELO, TipoVantagemJungle.INVASAO),
        m("Kaizer", "Butterfly", 9, ConfiancaDado.ALTA,
            "Resistência durante a transformação impede a primeira execução.",
            TipoVantagemJungle.DUELO, TipoVantagemJungle.LUTA),
        m("Arthur", "Butterfly", 8, ConfiancaDado.MEDIA,
            "Silêncio bloqueia a sequência e compra tempo para a equipe eliminar a assassina.",
            TipoVantagemJungle.MECANICA, TipoVantagemJungle.LUTA),
        m("Wuyan", "Butterfly", 8, ConfiancaDado.MEDIA,
            "Petrificação interrompe a limpeza antes que os resets comecem.",
            TipoVantagemJungle.MECANICA, TipoVantagemJungle.LUTA),

        m("Musashi", "Fatih", 9, ConfiancaDado.ALTA,
            "Anti-cura reduz diretamente o roubo de vida que sustenta Fatih.",
            TipoVantagemJungle.MECANICA, TipoVantagemJungle.DUELO),
        m("Chano", "Fatih", 8, ConfiancaDado.MEDIA,
            "Alcance e dano contínuo permitem kite antes que o berserker conecte ataques.",
            TipoVantagemJungle.LUTA, TipoVantagemJungle.MECANICA),
        m("Agu", "Fatih", 7, ConfiancaDado.MEDIA,
            "Poke e buffs de movimento negam trocas corpo a corpo prolongadas.",
            TipoVantagemJungle.LUTA, TipoVantagemJungle.MAPA),
        m("Fatih", "Arthur", 7, ConfiancaDado.MEDIA,
            "Anti-controle e lifesteal superam o dano limitado de Arthur em duelo longo.",
            TipoVantagemJungle.DUELO, TipoVantagemJungle.ESCALAMENTO),

        m("Arthur", "Luna", 9, ConfiancaDado.ALTA,
            "Silêncio interrompe a sequência de marcas e cancela os resets de mobilidade.",
            TipoVantagemJungle.MECANICA, TipoVantagemJungle.LUTA),
        m("Arthur", "Jing", 8, ConfiancaDado.MEDIA,
            "Silêncio reduz as opções de espelho e transforma a entrada em duelo frontal.",
            TipoVantagemJungle.MECANICA, TipoVantagemJungle.DUELO),
        m("Arthur", "Li Bai", 8, ConfiancaDado.MEDIA,
            "Silêncio após a entrada impede o retorno confortável e a segunda rotação.",
            TipoVantagemJungle.MECANICA, TipoVantagemJungle.LUTA),
        m("Arthur", "Yango", 9, ConfiancaDado.MEDIA,
            "Silêncio corta sequências da marionete antes do burst completo.",
            TipoVantagemJungle.MECANICA, TipoVantagemJungle.LUTA),
        m("Arthur", "Xuance", 8, ConfiancaDado.MEDIA,
            "Resistência e silêncio reduzem o valor do gancho e do cleanup.",
            TipoVantagemJungle.MECANICA, TipoVantagemJungle.LUTA),

        m("Musashi", "Agu", 8, ConfiancaDado.MEDIA,
            "Acesso ao alvo e bloqueio de projéteis reduzem o poke da atiradora.",
            TipoVantagemJungle.MECANICA, TipoVantagemJungle.GANK),
        m("Musashi", "Chano", 9, ConfiancaDado.ALTA,
            "Bloqueio de projéteis e ultimate de foco negam o front-to-back do atirador.",
            TipoVantagemJungle.MECANICA, TipoVantagemJungle.LUTA),
        m("Musashi", "Umbrosa", 9, ConfiancaDado.ALTA,
            "Anti-cura reduz sustain e dificulta recuperar vida após a ressurreição.",
            TipoVantagemJungle.MECANICA, TipoVantagemJungle.LUTA),
        m("Musashi", "Mi Yue", 8, ConfiancaDado.MEDIA,
            "Anti-cura e foco direto limitam a sustentação da duelista mágica.",
            TipoVantagemJungle.MECANICA, TipoVantagemJungle.DUELO),

        m("Liu Bei", "Han Xin", 8, ConfiancaDado.MEDIA,
            "Dano próximo e escudo tornam invasões de Han Xin arriscadas em duelo direto.",
            TipoVantagemJungle.DUELO, TipoVantagemJungle.INVASAO),
        m("Liu Bei", "Jing", 8, ConfiancaDado.MEDIA,
            "Pressão corpo a corpo e escudo reduzem a margem de outplay dos espelhos.",
            TipoVantagemJungle.DUELO, TipoVantagemJungle.INVASAO),
        m("Liu Bei", "Lam", 8, ConfiancaDado.MEDIA,
            "Explosão próxima e resistência vencem o primeiro contato do assassino.",
            TipoVantagemJungle.DUELO, TipoVantagemJungle.INVASAO),
        m("Liu Bei", "Nakoruru", 8, ConfiancaDado.MEDIA,
            "Escudo absorve a primeira explosão e força uma troca prolongada desfavorável.",
            TipoVantagemJungle.DUELO, TipoVantagemJungle.MECANICA),

        m("Pei", "Wukong", 8, ConfiancaDado.ALTA,
            "Pico precoce e invasão atrasam os itens de crítico necessários para Wukong.",
            TipoVantagemJungle.INVASAO, TipoVantagemJungle.ESCALAMENTO),
        m("Pei", "Butterfly", 8, ConfiancaDado.MEDIA,
            "Pressão inicial impede que Butterfly encontre farm e primeira execução segura.",
            TipoVantagemJungle.INVASAO, TipoVantagemJungle.MAPA),
        m("Pei", "Kongming", 8, ConfiancaDado.MEDIA,
            "Invasão antes do pico de dano limita a capacidade de snowball do mago.",
            TipoVantagemJungle.INVASAO, TipoVantagemJungle.OBJETIVOS),
        m("Pei", "Chano", 9, ConfiancaDado.MEDIA,
            "Tempo precoce e invasões punem um atirador dependente de escalamento.",
            TipoVantagemJungle.INVASAO, TipoVantagemJungle.ESCALAMENTO),

        m("Han Xin", "Chano", 9, ConfiancaDado.MEDIA,
            "Mobilidade e invasão impedem o segundo atirador de alcançar o pico tardio.",
            TipoVantagemJungle.INVASAO, TipoVantagemJungle.MAPA),
        m("Han Xin", "Kongming", 8, ConfiancaDado.MEDIA,
            "Roubo de campos e pressão lateral reduzem recursos e oportunidades de execução.",
            TipoVantagemJungle.INVASAO, TipoVantagemJungle.MAPA),
        m("Han Xin", "Wukong", 8, ConfiancaDado.MEDIA,
            "Ritmo de farm e split push forçam Wukong a reagir antes dos itens de crítico.",
            TipoVantagemJungle.MAPA, TipoVantagemJungle.ESCALAMENTO),

        m("Kaizer", "Wukong", 9, ConfiancaDado.ALTA,
            "Transformação absorve o crítico inicial e vence o duelo prolongado.",
            TipoVantagemJungle.DUELO, TipoVantagemJungle.LUTA),
        m("Kaizer", "Nakoruru", 8, ConfiancaDado.ALTA,
            "Resistência reduz a explosão percentual e força a assassina a recuar.",
            TipoVantagemJungle.DUELO, TipoVantagemJungle.LUTA),
        m("Kaizer", "Arke", 8, ConfiancaDado.MEDIA,
            "A transformação impede a execução rápida e remove a janela de reset.",
            TipoVantagemJungle.DUELO, TipoVantagemJungle.LUTA),
        m("Kaizer", "Lam", 8, ConfiancaDado.MEDIA,
            "Linha de frente e dano direto impedem Lam de atravessar até a backline.",
            TipoVantagemJungle.LUTA, TipoVantagemJungle.DUELO),

        m("Dian Wei", "Ata", 8, ConfiancaDado.ALTA,
            "Dano verdadeiro pune diretamente a alta resistência do tanque.",
            TipoVantagemJungle.DUELO, TipoVantagemJungle.LUTA),
        m("Dian Wei", "Menki", 8, ConfiancaDado.ALTA,
            "Dano verdadeiro atravessa escudos e transforma o duelo prolongado.",
            TipoVantagemJungle.DUELO, TipoVantagemJungle.MECANICA),
        m("Dian Wei", "Umbrosa", 7, ConfiancaDado.MEDIA,
            "DPS e dano verdadeiro mantêm pressão após a primeira barra de vida.",
            TipoVantagemJungle.DUELO, TipoVantagemJungle.LUTA),

        m("Wuyan", "Luna", 9, ConfiancaDado.MEDIA,
            "Petrificação interrompe a sequência de resets e prende a maga no alcance aliado.",
            TipoVantagemJungle.MECANICA, TipoVantagemJungle.LUTA),
        m("Wuyan", "Jing", 8, ConfiancaDado.MEDIA,
            "Controle em área reduz o espaço seguro dentro da ultimate de espelhos.",
            TipoVantagemJungle.MECANICA, TipoVantagemJungle.LUTA),
        m("Wuyan", "Yango", 8, ConfiancaDado.MEDIA,
            "Petrificação pune a aproximação da marionete e interrompe o combo.",
            TipoVantagemJungle.MECANICA, TipoVantagemJungle.LUTA),
        m("Wuyan", "Xuance", 8, ConfiancaDado.MEDIA,
            "Resistência e controle em área impedem cleanup livre após o gancho.",
            TipoVantagemJungle.MECANICA, TipoVantagemJungle.LUTA),

        m("Dharma", "Yango", 9, ConfiancaDado.MEDIA,
            "Controle contra parede interrompe a sequência e explode o assassino frágil.",
            TipoVantagemJungle.MECANICA, TipoVantagemJungle.GANK),
        m("Dharma", "Jing", 8, ConfiancaDado.MEDIA,
            "Knockback em parede reduz o valor da mobilidade dentro de corredores.",
            TipoVantagemJungle.MECANICA, TipoVantagemJungle.LUTA),
        m("Dharma", "Li Bai", 8, ConfiancaDado.MEDIA,
            "Controle explosivo pune o ponto previsível de entrada ou retorno.",
            TipoVantagemJungle.MECANICA, TipoVantagemJungle.GANK),

        m("Sima Yi", "Kongming", 8, ConfiancaDado.ALTA,
            "Silêncio impede mobilidade e execução no momento crítico.",
            TipoVantagemJungle.MECANICA, TipoVantagemJungle.DUELO),
        m("Sima Yi", "Luna", 8, ConfiancaDado.MEDIA,
            "Silêncio corta resets e transforma a troca em burst direto.",
            TipoVantagemJungle.MECANICA, TipoVantagemJungle.DUELO),
        m("Sima Yi", "Agu", 8, ConfiancaDado.MEDIA,
            "Entrada global atravessa a distância e ameaça a fonte de buffs da equipe.",
            TipoVantagemJungle.GANK, TipoVantagemJungle.MAPA),
        m("Sima Yi", "Chano", 8, ConfiancaDado.MEDIA,
            "Acesso direto e silêncio punem o atirador antes do dano sustentado.",
            TipoVantagemJungle.GANK, TipoVantagemJungle.MECANICA),

        m("Kongming", "Ata", 8, ConfiancaDado.MEDIA,
            "Mobilidade e execução ignoram parte da linha de frente e buscam alvos baixos.",
            TipoVantagemJungle.LUTA, TipoVantagemJungle.MECANICA),
        m("Kongming", "Wuyan", 7, ConfiancaDado.MEDIA,
            "Pode jogar fora do alcance de petrificação e usar resets sobre alvos secundários.",
            TipoVantagemJungle.LUTA, TipoVantagemJungle.ESCALAMENTO),
        m("Kongming", "Zilong", 8, ConfiancaDado.MEDIA,
            "Mobilidade evita a entrada linear e cria execução após o mergulho.",
            TipoVantagemJungle.MECANICA, TipoVantagemJungle.LUTA),

        m("Luna", "Ata", 8, ConfiancaDado.MEDIA,
            "Dano mágico sustentado e mobilidade contornam o controle de terreno.",
            TipoVantagemJungle.DUELO, TipoVantagemJungle.LUTA),
        m("Luna", "Menki", 8, ConfiancaDado.MEDIA,
            "Resets e dano mágico prolongado vencem escudos quando não há controle confiável.",
            TipoVantagemJungle.DUELO, TipoVantagemJungle.ESCALAMENTO),
        m("Luna", "Dian Wei", 8, ConfiancaDado.MEDIA,
            "Mobilidade constante impede que o lutador linear mantenha contato.",
            TipoVantagemJungle.MECANICA, TipoVantagemJungle.DUELO),

        m("Nakoruru", "Agu", 8, ConfiancaDado.MEDIA,
            "Explosão e entrada aérea alcançam a atiradora antes que o poke se acumule.",
            TipoVantagemJungle.GANK, TipoVantagemJungle.MECANICA),
        m("Nakoruru", "Chano", 8, ConfiancaDado.MEDIA,
            "Dano percentual e burst removem o segundo carry da luta rapidamente.",
            TipoVantagemJungle.GANK, TipoVantagemJungle.LUTA),
        m("Nakoruru", "Menki", 7, ConfiancaDado.MEDIA,
            "Dano percentual reduz a eficiência de acumular apenas vida e escudos.",
            TipoVantagemJungle.MECANICA, TipoVantagemJungle.DUELO),

        m("Fang", "Wukong", 8, ConfiancaDado.MEDIA,
            "Objetivos e pressão inicial aceleram o jogo antes do pico de crítico.",
            TipoVantagemJungle.OBJETIVOS, TipoVantagemJungle.ESCALAMENTO),
        m("Fang", "Chano", 8, ConfiancaDado.MEDIA,
            "Explosão e controle de objetivos criam vantagem antes do late game.",
            TipoVantagemJungle.OBJETIVOS, TipoVantagemJungle.MAPA),
        m("Fang", "Agu", 7, ConfiancaDado.MEDIA,
            "Maior ameaça de burst em alvo e objetivo força Agu a jogar defensivamente.",
            TipoVantagemJungle.OBJETIVOS, TipoVantagemJungle.DUELO),

        m("Sun Ce", "Agu", 9, ConfiancaDado.MEDIA,
            "Iniciação global fecha a distância e cria engage sobre a atiradora imóvel.",
            TipoVantagemJungle.GANK, TipoVantagemJungle.MAPA),
        m("Sun Ce", "Chano", 8, ConfiancaDado.MEDIA,
            "Controle em cadeia alcança o atirador antes que o front-to-back comece.",
            TipoVantagemJungle.GANK, TipoVantagemJungle.LUTA),
        m("Sun Ce", "Han Xin", 7, ConfiancaDado.MEDIA,
            "Presença global responde ao split push e força lutas antes do roubo de mapa.",
            TipoVantagemJungle.MAPA, TipoVantagemJungle.GANK),

        m("Mi Yue", "Kaizer", 7, ConfiancaDado.MEDIA,
            "Sustentação, alcance e invulnerabilidade desgastam a transformação em duelo.",
            TipoVantagemJungle.DUELO, TipoVantagemJungle.MECANICA),
        m("Mi Yue", "Dian Wei", 8, ConfiancaDado.MEDIA,
            "Kite e sustain negam contato contínuo ao lutador linear.",
            TipoVantagemJungle.MECANICA, TipoVantagemJungle.DUELO),
        m("Mi Yue", "Arthur", 7, ConfiancaDado.MEDIA,
            "Dano mágico prolongado e sustain superam a pressão curta do tanque.",
            TipoVantagemJungle.DUELO, TipoVantagemJungle.ESCALAMENTO),

        m("Ying", "Butterfly", 8, ConfiancaDado.MEDIA,
            "Controle e sustain impedem uma execução limpa e removem a janela de reset.",
            TipoVantagemJungle.DUELO, TipoVantagemJungle.LUTA),
        m("Ying", "Wukong", 8, ConfiancaDado.MEDIA,
            "Resistência e controle sobrevivem ao crítico inicial e vencem a troca estendida.",
            TipoVantagemJungle.DUELO, TipoVantagemJungle.LUTA),
        m("Ying", "Zilong", 8, ConfiancaDado.MEDIA,
            "Controle adaptável interrompe a entrada linear e protege a retaguarda.",
            TipoVantagemJungle.MECANICA, TipoVantagemJungle.LUTA),

        m("Xuance", "Agu", 8, ConfiancaDado.MEDIA,
            "Gancho desloca a atiradora e inicia cleanup fora da proteção aliada.",
            TipoVantagemJungle.GANK, TipoVantagemJungle.MECANICA),
        m("Xuance", "Chano", 8, ConfiancaDado.MEDIA,
            "Pickoff impede o atirador de manter posição em lutas front-to-back.",
            TipoVantagemJungle.GANK, TipoVantagemJungle.LUTA),
        m("Yango", "Agu", 8, ConfiancaDado.EXPLORATORIA,
            "Marionete e iniciação móvel atravessam a linha frontal e alcançam a carry.",
            TipoVantagemJungle.GANK, TipoVantagemJungle.MECANICA),
        m("Yango", "Chano", 8, ConfiancaDado.EXPLORATORIA,
            "Múltiplas formas de aproximação punem o atirador dependente de posição.",
            TipoVantagemJungle.GANK, TipoVantagemJungle.LUTA)
    );

    public List<ConfrontoJungle> listarTodos() {
        return confrontos;
    }

    private ConfrontoJungle m(
        String vencedor,
        String alvo,
        int vantagem,
        ConfiancaDado confianca,
        String motivo,
        TipoVantagemJungle... tipos
    ) {
        return new ConfrontoJungle(
            vencedor,
            alvo,
            vantagem,
            confianca,
            List.of(tipos),
            motivo
        );
    }
}
