package br.com.carlosdaniel.hokdraftcoach.repository;

import java.util.List;

import org.springframework.stereotype.Repository;

import br.com.carlosdaniel.hokdraftcoach.model.ConfiancaDado;
import br.com.carlosdaniel.hokdraftcoach.model.ConfrontoMidLane;
import br.com.carlosdaniel.hokdraftcoach.model.TipoVantagemMid;

@Repository
public class ConfrontoMidRepository {

    private final List<ConfrontoMidLane> confrontos = List.of(
        m("Angela", "Diaochan", 9, ConfiancaDado.ALTA,
            "Burst e controle alcançam Diaochan antes que a luta prolongada comece.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),
        m("Milady", "Mai Shiranui", 8, ConfiancaDado.ALTA,
            "Invocações e pressão de torre punem as rotações e a limpeza menos constante de Mai.",
            TipoVantagemMid.ROTA, TipoVantagemMid.MAPA),
        m("Haya", "Milady", 8, ConfiancaDado.ALTA,
            "Mobilidade e pressão constante atravessam as invocações e ameaçam Milady diretamente.",
            TipoVantagemMid.ROTA, TipoVantagemMid.ROTACAO),
        m("Lady Zhen", "Sima Yi", 8, ConfiancaDado.ALTA,
            "Controle em área e congelamento punem a entrada previsível de Sima Yi.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),
        m("Dr Bian Qe", "Mai Shiranui", 8, ConfiancaDado.ALTA,
            "Sustentação e veneno vencem trocas repetidas e reduzem o valor do poke de Mai.",
            TipoVantagemMid.ROTA, TipoVantagemMid.LUTA),
        m("Dr Bian Qe", "Diaochan", 7, ConfiancaDado.ALTA,
            "Acúmulos, cura e dano persistente competem melhor em lutas prolongadas.",
            TipoVantagemMid.LUTA, TipoVantagemMid.ESCALAMENTO),
        m("Shangguan", "Diaochan", 8, ConfiancaDado.ALTA,
            "A sequência aérea reduz o tempo disponível para Diaochan estabelecer sua zona.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),
        m("Shangguan", "Sima Yi", 7, ConfiancaDado.ALTA,
            "Mobilidade e invulnerabilidade durante a finalização dificultam a explosão de Sima Yi.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),
        m("Ziya", "Diaochan", 7, ConfiancaDado.ALTA,
            "Alcance e desaceleração impedem Diaochan de alcançar uma luta confortável.",
            TipoVantagemMid.ROTA, TipoVantagemMid.LUTA),
        m("Gao Jianli", "Mai Shiranui", 7, ConfiancaDado.ALTA,
            "Resistência durante a entrada e dano em área punem a aproximação de Mai.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),

        m("Liang", "Kongming", 9, ConfiancaDado.ALTA,
            "Supressão interrompe mobilidade, execução e resets de Kongming.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),
        m("Liang", "Mai Shiranui", 9, ConfiancaDado.ALTA,
            "Controle garantido remove a principal vantagem de Mai: entrar e sair livremente.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),
        m("Liang", "Shangguan", 9, ConfiancaDado.ALTA,
            "A supressão pode interromper a sequência antes da invulnerabilidade final.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),
        m("Liang", "Sima Yi", 9, ConfiancaDado.ALTA,
            "Controle inevitável trava a entrada explosiva e impede a fuga.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),
        m("Liang", "Diaochan", 8, ConfiancaDado.MEDIA,
            "Supressão remove Diaochan de sua zona e permite burst aliado coordenado.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),

        m("Daji", "Kongming", 8, ConfiancaDado.MEDIA,
            "Controle direcionado impede o reposicionamento necessário para os resets.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),
        m("Daji", "Mai Shiranui", 8, ConfiancaDado.MEDIA,
            "O stun garantido transforma uma aproximação de Mai em janela de eliminação.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),
        m("Daji", "Shangguan", 8, ConfiancaDado.MEDIA,
            "Controle instantâneo pune o início da sequência antes da fase invulnerável.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),

        m("Sima Yi", "Angela", 8, ConfiancaDado.MEDIA,
            "Acesso rápido e silêncio interrompem a artilharia e evitam o canal completo.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.ROTACAO),
        m("Sima Yi", "Gan & Mo", 9, ConfiancaDado.MEDIA,
            "Entrada global e silêncio exploram a baixa mobilidade do artilheiro.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.ROTACAO),
        m("Sima Yi", "Nuwa", 8, ConfiancaDado.MEDIA,
            "Chegada pela retaguarda reduz a vantagem de alcance e terreno de Nuwa.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.MAPA),
        m("Sima Yi", "Xiao Qiao", 8, ConfiancaDado.MEDIA,
            "Silêncio e acesso direto punem a falta de mobilidade da maga.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.ROTACAO),
        m("Sima Yi", "Ziya", 9, ConfiancaDado.MEDIA,
            "Acesso global atravessa o alcance e elimina o artilheiro antes do cast completo.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.MAPA),

        m("Mai Shiranui", "Gan & Mo", 9, ConfiancaDado.MEDIA,
            "Mobilidade extrema atravessa a distância e força o artilheiro a defender-se.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.ROTACAO),
        m("Mai Shiranui", "Nuwa", 8, ConfiancaDado.MEDIA,
            "Múltiplos deslocamentos contornam terreno e alcançam a retaguarda.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),
        m("Mai Shiranui", "Ziya", 9, ConfiancaDado.MEDIA,
            "A mobilidade fecha a distância antes que Ziya converta seu alcance em dano.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.ROTACAO),
        m("Mai Shiranui", "Angela", 8, ConfiancaDado.MEDIA,
            "Reposicionamentos rápidos evitam o combo linear e ameaçam a lateral.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.ROTA),

        m("Kongming", "Gan & Mo", 8, ConfiancaDado.MEDIA,
            "Mobilidade e execução punem a baixa resistência do artilheiro.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.ROTACAO),
        m("Kongming", "Ziya", 8, ConfiancaDado.MEDIA,
            "Consegue atravessar o poke, executar e usar o reset para sair.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),
        m("Kongming", "Milady", 8, ConfiancaDado.MEDIA,
            "Limpeza por habilidades e mobilidade permitem ignorar invocações e ameaçar o corpo da maga.",
            TipoVantagemMid.ROTA, TipoVantagemMid.MECANICA),
        m("Kongming", "Daji", 7, ConfiancaDado.MEDIA,
            "Pressão de rota e mobilidade criam vantagem antes do pico completo de burst de Daji.",
            TipoVantagemMid.ROTA, TipoVantagemMid.ROTACAO),

        m("Yixing", "Gao Jianli", 9, ConfiancaDado.MEDIA,
            "O tabuleiro limita a entrada e mantém Gao dentro de uma zona controlada.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),
        m("Yixing", "Diaochan", 8, ConfiancaDado.MEDIA,
            "Zoneamento e confinamento reduzem os ângulos de dança da maga de batalha.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),
        m("Yixing", "Mai Shiranui", 8, ConfiancaDado.MEDIA,
            "Controle de área fecha rotas de entrada e saída.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),

        m("Wang Zhaojun", "Gao Jianli", 9, ConfiancaDado.MEDIA,
            "Congelamento e tempestade punem um mergulho frontal e previsível.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),
        m("Wang Zhaojun", "Diaochan", 8, ConfiancaDado.MEDIA,
            "Controle de zona restringe o espaço necessário para a luta prolongada.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),
        m("Wang Zhaojun", "Milady", 7, ConfiancaDado.MEDIA,
            "Wave clear em área remove invocações e impede pressão fácil de torre.",
            TipoVantagemMid.ROTA, TipoVantagemMid.MAPA),

        m("Lady Zhen", "Gao Jianli", 9, ConfiancaDado.MEDIA,
            "Controle em cadeia congela Gao durante sua entrada agrupada.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),
        m("Lady Zhen", "Diaochan", 8, ConfiancaDado.MEDIA,
            "Congelamento e dano em área punem permanência prolongada na mesma zona.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),
        m("Lady Zhen", "Kongming", 7, ConfiancaDado.MEDIA,
            "Controle em área protege a formação e dificulta resets seguros.",
            TipoVantagemMid.LUTA, TipoVantagemMid.MECANICA),

        m("Mozi", "Shangguan", 9, ConfiancaDado.MEDIA,
            "Controles de longa distância interrompem a preparação da sequência.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),
        m("Mozi", "Gao Jianli", 8, ConfiancaDado.MEDIA,
            "Escudo e controle impedem uma entrada limpa na retaguarda.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),
        m("Mozi", "Kongming", 7, ConfiancaDado.MEDIA,
            "Poke e controle reduzem a vida antes que Kongming encontre uma execução segura.",
            TipoVantagemMid.ROTA, TipoVantagemMid.LUTA),

        m("Nuwa", "Angela", 8, ConfiancaDado.MEDIA,
            "Maior alcance e criação de terreno dificultam o alinhamento do combo de Angela.",
            TipoVantagemMid.ROTA, TipoVantagemMid.MAPA),
        m("Nuwa", "Lady Zhen", 7, ConfiancaDado.MEDIA,
            "Alcance e controle de corredores evitam lutas no espaço ideal de Lady Zhen.",
            TipoVantagemMid.MAPA, TipoVantagemMid.LUTA),
        m("Nuwa", "Dr Bian Qe", 8, ConfiancaDado.MEDIA,
            "Poke de longa distância impede a aproximação necessária para acumular veneno.",
            TipoVantagemMid.ROTA, TipoVantagemMid.LUTA),

        m("Gan & Mo", "Daji", 8, ConfiancaDado.MEDIA,
            "Alcance extremo pressiona Daji antes que ela encontre distância de controle.",
            TipoVantagemMid.ROTA, TipoVantagemMid.LUTA),
        m("Gan & Mo", "Lady Zhen", 7, ConfiancaDado.MEDIA,
            "Poke fora do alcance reduz o valor do controle de área defensivo.",
            TipoVantagemMid.ROTA, TipoVantagemMid.LUTA),
        m("Gan & Mo", "Angela", 7, ConfiancaDado.MEDIA,
            "Maior liberdade de ângulo e precisão permitem vencer a guerra de artilharia.",
            TipoVantagemMid.ROTA, TipoVantagemMid.LUTA),

        m("Shi", "Milady", 8, ConfiancaDado.MEDIA,
            "Reposicionamento forçado expõe Milady e ignora a proteção das invocações.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),
        m("Shi", "Gan & Mo", 9, ConfiancaDado.MEDIA,
            "Controle de longa distância remove o artilheiro de uma posição segura.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.PICKOFF),
        m("Shi", "Angela", 8, ConfiancaDado.MEDIA,
            "Reposicionamento quebra o alinhamento do canal e cria pickoff.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),

        m("Diaochan", "Zhou Yu", 8, ConfiancaDado.MEDIA,
            "Mobilidade dentro da luta atravessa zonas persistentes e evita o dano previsível.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),
        m("Diaochan", "Heino", 7, ConfiancaDado.MEDIA,
            "No combate próximo, mobilidade e dano verdadeiro vencem a troca prolongada.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),
        m("Diaochan", "Milady", 8, ConfiancaDado.MEDIA,
            "Mobilidade e dano em área limpam invocações enquanto ameaçam a maga.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.ROTA),

        m("Heino", "Angela", 8, ConfiancaDado.MEDIA,
            "Alcance, sustain e retorno temporal reduzem a chance de eliminação em um combo.",
            TipoVantagemMid.ROTA, TipoVantagemMid.LUTA),
        m("Heino", "Zhou Yu", 7, ConfiancaDado.MEDIA,
            "Alcance e reposicionamento jogam fora da zona persistente de fogo.",
            TipoVantagemMid.ROTA, TipoVantagemMid.LUTA),
        m("Heino", "Dr Bian Qe", 7, ConfiancaDado.MEDIA,
            "Maior alcance impede acúmulos constantes e controla o ritmo da troca.",
            TipoVantagemMid.ROTA, TipoVantagemMid.LUTA),

        m("Yuhuan", "Mai Shiranui", 8, ConfiancaDado.ALTA,
            "Cura, mobilidade e invulnerabilidade reduzem o valor das trocas explosivas.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),
        m("Yuhuan", "Angela", 7, ConfiancaDado.MEDIA,
            "Sustentação e mobilidade evitam que o poke se transforme em eliminação.",
            TipoVantagemMid.ROTA, TipoVantagemMid.LUTA),
        m("Yuhuan", "Daji", 7, ConfiancaDado.MEDIA,
            "Sustentação e ferramentas defensivas dificultam a execução em uma rotação.",
            TipoVantagemMid.LUTA, TipoVantagemMid.ESCALAMENTO),

        m("Zhou Yu", "Daji", 8, ConfiancaDado.MEDIA,
            "Pressão de rota e wave clear prendem Daji e reduzem suas rotações.",
            TipoVantagemMid.ROTA, TipoVantagemMid.MAPA),
        m("Zhou Yu", "Angela", 7, ConfiancaDado.MEDIA,
            "Território persistente força Angela a abandonar posições fixas de canal.",
            TipoVantagemMid.ROTA, TipoVantagemMid.LUTA),

        m("Da Qiao", "Milady", 7, ConfiancaDado.MEDIA,
            "Wave control e macro neutralizam parte da pressão de torre e criam superioridade em outras rotas.",
            TipoVantagemMid.MAPA, TipoVantagemMid.ROTACAO),
        m("Da Qiao", "Daji", 7, ConfiancaDado.MEDIA,
            "Rotação global e retorno seguro diminuem a eficácia dos pickoffs previsíveis.",
            TipoVantagemMid.MAPA, TipoVantagemMid.ROTACAO),

        m("Lorion", "Gao Jianli", 9, ConfiancaDado.MEDIA,
            "Controle do orbe pune o mergulho frontal e mantém distância durante a ultimate.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),
        m("Lorion", "Diaochan", 8, ConfiancaDado.MEDIA,
            "Controle em área e explosão reduzem o tempo disponível para a dança prolongada.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),
        m("Lorion", "Milady", 8, ConfiancaDado.MEDIA,
            "Mobilidade e dano em área removem invocações e ameaçam a própria Milady.",
            TipoVantagemMid.ROTA, TipoVantagemMid.MECANICA),
        m("Lorion", "Lady Zhen", 7, ConfiancaDado.MEDIA,
            "Mobilidade do orbe cria ângulos fora da zona ideal da controladora.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA),

        m("Garuda", "Dr Bian Qe", 8, ConfiancaDado.MEDIA,
            "Poke e velocidade impedem aproximação constante para acumular veneno.",
            TipoVantagemMid.ROTA, TipoVantagemMid.ROTACAO),
        m("Garuda", "Milady", 7, ConfiancaDado.MEDIA,
            "Mobilidade e alcance permitem limpar pressão e sair para impactar o mapa.",
            TipoVantagemMid.ROTA, TipoVantagemMid.ROTACAO),
        m("Garuda", "Zhou Yu", 7, ConfiancaDado.MEDIA,
            "Velocidade de movimento facilita escapar das zonas persistentes de fogo.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.ROTACAO),

        m("Ser do Fluxo (Mago)", "Milady", 6, ConfiancaDado.EXPLORATORIA,
            "A adaptação de controle e wave clear pode neutralizar parte da pressão de invocações.",
            TipoVantagemMid.ROTA, TipoVantagemMid.MAPA),
        m("Ser do Fluxo (Mago)", "Daji", 6, ConfiancaDado.EXPLORATORIA,
            "Ferramentas adaptáveis aumentam a segurança contra pickoff em alvo único.",
            TipoVantagemMid.MECANICA, TipoVantagemMid.LUTA)
    );

    public List<ConfrontoMidLane> listarTodos() {
        return confrontos;
    }

    private ConfrontoMidLane m(
        String vencedor,
        String alvo,
        int vantagem,
        ConfiancaDado confianca,
        String motivo,
        TipoVantagemMid... tipos
    ) {
        return new ConfrontoMidLane(
            vencedor,
            alvo,
            vantagem,
            confianca,
            List.of(tipos),
            motivo
        );
    }
}
