package br.com.carlosdaniel.hokdraftcoach.repository;

import java.util.List;

import org.springframework.stereotype.Repository;

import br.com.carlosdaniel.hokdraftcoach.model.ArquetipoSuporte;
import br.com.carlosdaniel.hokdraftcoach.model.PerfilSuporte;
import br.com.carlosdaniel.hokdraftcoach.model.TipoComposicao;

@Repository
public class PerfilSuporteRepository {

    private final List<PerfilSuporte> perfis = List.of(
        p("Annette",
            a(ArquetipoSuporte.PROTETOR, ArquetipoSuporte.DESENGAGE, ArquetipoSuporte.CONTROLE_DE_AREA),
            c(TipoComposicao.POKE, TipoComposicao.HIPERCARREGADOR, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.DIVE, TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.ALTA_MOBILIDADE),
            c(TipoComposicao.PICKOFF, TipoComposicao.SPLIT_PUSH),
            8, 5, 10, 4, 6, 6, 5,
            "Nega entradas agrupadas e protege atiradores sem mobilidade."),
        p("Lapulapu",
            a(ArquetipoSuporte.TANQUE, ArquetipoSuporte.INICIADOR, ArquetipoSuporte.PROTETOR),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.LUTAS_LONGAS),
            c(TipoComposicao.DIVE, TipoComposicao.EXPLOSAO, TipoComposicao.ALVOS_IMOVEIS),
            c(TipoComposicao.POKE, TipoComposicao.DESENGAGE),
            8, 8, 7, 4, 7, 5, 5,
            "Cria a janela de entrada e absorve a primeira resposta inimiga."),
        p("Cai Yan",
            a(ArquetipoSuporte.CURADOR, ArquetipoSuporte.ENCANTADOR, ArquetipoSuporte.PROTETOR),
            c(TipoComposicao.HIPERCARREGADOR, TipoComposicao.LUTAS_LONGAS, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.POKE, TipoComposicao.ESCUDOS_E_CURA),
            c(TipoComposicao.EXPLOSAO, TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.PICKOFF),
            9, 3, 5, 10, 7, 4, 3,
            "Muito forte agrupada; perde valor contra burst e redução de cura."),
        p("Da Qiao",
            a(ArquetipoSuporte.MACRO, ArquetipoSuporte.DESENGAGE, ArquetipoSuporte.CONTROLE_DE_AREA),
            c(TipoComposicao.SPLIT_PUSH, TipoComposicao.POKE, TipoComposicao.PICKOFF),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.LUTAS_LONGAS),
            c(TipoComposicao.ALTA_MOBILIDADE, TipoComposicao.DIVE),
            7, 6, 9, 5, 7, 10, 10,
            "Portais, retornos e rotações globais escalam com coordenação."),
        p("Dolia",
            a(ArquetipoSuporte.ENCANTADOR, ArquetipoSuporte.AMPLIFICADOR, ArquetipoSuporte.CURADOR),
            c(TipoComposicao.ULTIMATES_DECISIVAS, TipoComposicao.LUTAS_LONGAS, TipoComposicao.ENGAGE_AGRUPADO),
            c(TipoComposicao.POKE, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.PICKOFF, TipoComposicao.EXPLOSAO),
            8, 5, 7, 9, 6, 6, 8,
            "Prioriza aliados cuja ultimate define a luta, como Marco Polo e Loong."),
        p("Donghuang",
            a(ArquetipoSuporte.TANQUE, ArquetipoSuporte.PICKOFF, ArquetipoSuporte.INICIADOR),
            c(TipoComposicao.PICKOFF, TipoComposicao.EXPLOSAO, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.DIVE, TipoComposicao.ALTA_MOBILIDADE, TipoComposicao.HIPERCARREGADOR),
            c(TipoComposicao.POKE, TipoComposicao.ESCUDOS_E_CURA),
            8, 9, 6, 6, 8, 5, 5,
            "A supressão trava um carregador ou mergulhador mesmo com mobilidade."),
        p("Dun",
            a(ArquetipoSuporte.TANQUE, ArquetipoSuporte.PROTETOR, ArquetipoSuporte.INICIADOR),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.LUTAS_LONGAS),
            c(TipoComposicao.DIVE, TipoComposicao.EXPLOSAO),
            c(TipoComposicao.POKE, TipoComposicao.ALTA_MOBILIDADE),
            8, 7, 7, 7, 6, 5, 4,
            "Escolha estável quando faltam linha de frente e peel."),
        p("Dyadia",
            a(ArquetipoSuporte.CURADOR, ArquetipoSuporte.ENCANTADOR, ArquetipoSuporte.POKE),
            c(TipoComposicao.LUTAS_LONGAS, TipoComposicao.POKE, TipoComposicao.ALTA_MOBILIDADE),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.ESCUDOS_E_CURA),
            c(TipoComposicao.EXPLOSAO, TipoComposicao.PICKOFF),
            8, 4, 6, 9, 8, 8, 6,
            "Pressão de rota, cura e mobilidade fazem dela um blind pick seguro."),
        p("Guiguzi",
            a(ArquetipoSuporte.INICIADOR, ArquetipoSuporte.PICKOFF, ArquetipoSuporte.MACRO),
            c(TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.PICKOFF, TipoComposicao.EXPLOSAO),
            c(TipoComposicao.POKE, TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.SPLIT_PUSH),
            c(TipoComposicao.DESENGAGE, TipoComposicao.CONTROLE_PESADO),
            4, 10, 3, 2, 8, 9, 8,
            "Camuflagem e agrupamento convertem visão negada em iniciação explosiva."),
        p("Kui",
            a(ArquetipoSuporte.PICKOFF, ArquetipoSuporte.TANQUE, ArquetipoSuporte.CONTROLE_DE_AREA),
            c(TipoComposicao.PICKOFF, TipoComposicao.POKE),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.HIPERCARREGADOR, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.ALTA_MOBILIDADE, TipoComposicao.DIVE),
            6, 8, 5, 2, 8, 5, 7,
            "O gancho quebra formações ao remover um alvo antes da luta."),
        p("Lian Po",
            a(ArquetipoSuporte.TANQUE, ArquetipoSuporte.INICIADOR, ArquetipoSuporte.CONTROLE_DE_AREA),
            c(TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.FRONT_TO_BACK, TipoComposicao.ULTIMATES_DECISIVAS),
            c(TipoComposicao.DIVE, TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.CONTROLE_PESADO),
            c(TipoComposicao.POKE, TipoComposicao.DESENGAGE),
            8, 10, 7, 4, 8, 6, 6,
            "Resiste a interrupções e prende alvos para ultimates como a de Marco Polo."),
        p("Liu Bang",
            a(ArquetipoSuporte.PROTETOR, ArquetipoSuporte.MACRO, ArquetipoSuporte.TANQUE),
            c(TipoComposicao.SPLIT_PUSH, TipoComposicao.HIPERCARREGADOR, TipoComposicao.DIVE),
            c(TipoComposicao.PICKOFF, TipoComposicao.DIVE, TipoComposicao.EXPLOSAO),
            c(TipoComposicao.POKE, TipoComposicao.ENGAGE_AGRUPADO),
            9, 5, 7, 5, 5, 10, 8,
            "Proteção global permite pressão lateral sem abandonar o carregador."),
        p("Liu Shan",
            a(ArquetipoSuporte.TANQUE, ArquetipoSuporte.INICIADOR, ArquetipoSuporte.PICKOFF),
            c(TipoComposicao.PICKOFF, TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.SPLIT_PUSH),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.POKE),
            c(TipoComposicao.DESENGAGE, TipoComposicao.ALTA_MOBILIDADE),
            7, 9, 6, 3, 9, 7, 5,
            "Converte vantagem de rota em controle de torre e snowball."),
        p("Ming",
            a(ArquetipoSuporte.AMPLIFICADOR, ArquetipoSuporte.ENCANTADOR, ArquetipoSuporte.PROTETOR),
            c(TipoComposicao.HIPERCARREGADOR, TipoComposicao.FRONT_TO_BACK, TipoComposicao.LUTAS_LONGAS),
            c(TipoComposicao.ESCUDOS_E_CURA, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.DIVE, TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.PICKOFF),
            9, 2, 4, 7, 8, 5, 4,
            "Multiplica um ADC forte, mas perde valor quando a dupla é separada."),
        p("Mozi",
            a(ArquetipoSuporte.POKE, ArquetipoSuporte.CONTROLE_DE_AREA, ArquetipoSuporte.DESENGAGE),
            c(TipoComposicao.POKE, TipoComposicao.PICKOFF, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.ULTIMATES_DECISIVAS, TipoComposicao.ENGAGE_AGRUPADO),
            c(TipoComposicao.DIVE, TipoComposicao.ALTA_MOBILIDADE),
            7, 6, 9, 3, 9, 5, 7,
            "Combina com ADCs de artilharia ao encadear poke e controle."),
        p("Sakeer",
            a(ArquetipoSuporte.CURADOR, ArquetipoSuporte.CONTROLE_DE_AREA, ArquetipoSuporte.PROTETOR),
            c(TipoComposicao.LUTAS_LONGAS, TipoComposicao.FRONT_TO_BACK, TipoComposicao.POKE),
            c(TipoComposicao.POKE, TipoComposicao.DIVE),
            c(TipoComposicao.EXPLOSAO, TipoComposicao.PICKOFF),
            8, 6, 7, 9, 7, 8, 7,
            "Visão, cura e controle mantêm ADCs móveis ativos na luta."),
        p("Sun Bin",
            a(ArquetipoSuporte.DESENGAGE, ArquetipoSuporte.MACRO, ArquetipoSuporte.ENCANTADOR),
            c(TipoComposicao.POKE, TipoComposicao.LUTAS_LONGAS, TipoComposicao.ALTA_MOBILIDADE),
            c(TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.EXPLOSAO, TipoComposicao.PICKOFF, TipoComposicao.CONTROLE_PESADO),
            7, 5, 9, 7, 7, 10, 7,
            "Acelera rotações e kite, mas não substitui uma linha de frente."),
        p("Xiang Yu",
            a(ArquetipoSuporte.TANQUE, ArquetipoSuporte.PROTETOR, ArquetipoSuporte.DESENGAGE),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.HIPERCARREGADOR),
            c(TipoComposicao.DIVE, TipoComposicao.EXPLOSAO, TipoComposicao.ENGAGE_AGRUPADO),
            c(TipoComposicao.POKE, TipoComposicao.ALTA_MOBILIDADE),
            9, 7, 9, 3, 7, 5, 4,
            "Deslocamentos expulsam lutadores e assassinos da zona do ADC."),
        p("Yaria",
            a(ArquetipoSuporte.ENCANTADOR, ArquetipoSuporte.PROTETOR, ArquetipoSuporte.MACRO),
            c(TipoComposicao.ALTA_MOBILIDADE, TipoComposicao.HIPERCARREGADOR, TipoComposicao.PICKOFF),
            c(TipoComposicao.DIVE, TipoComposicao.EXPLOSAO, TipoComposicao.PICKOFF),
            c(TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.POKE),
            10, 2, 6, 5, 7, 9, 5,
            "Acompanha reposicionamentos de Marco Polo e Arli sem quebrar o ritmo."),
        p("Yuhuan",
            a(ArquetipoSuporte.CURADOR, ArquetipoSuporte.POKE, ArquetipoSuporte.ENCANTADOR),
            c(TipoComposicao.POKE, TipoComposicao.LUTAS_LONGAS, TipoComposicao.ALTA_MOBILIDADE),
            c(TipoComposicao.POKE, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.DIVE, TipoComposicao.EXPLOSAO),
            7, 4, 6, 8, 7, 8, 8,
            "Valor por desgaste e mobilidade, com alta exigência de execução."),
        p("Zhang Fei",
            a(ArquetipoSuporte.TANQUE, ArquetipoSuporte.PROTETOR, ArquetipoSuporte.DESENGAGE),
            c(TipoComposicao.HIPERCARREGADOR, TipoComposicao.FRONT_TO_BACK, TipoComposicao.ENGAGE_AGRUPADO),
            c(TipoComposicao.DIVE, TipoComposicao.EXPLOSAO, TipoComposicao.PICKOFF),
            c(TipoComposicao.POKE, TipoComposicao.SPLIT_PUSH),
            10, 8, 10, 4, 7, 5, 4,
            "Blind pick seguro: escuda o ADC, segura dive e oferece iniciação."),
        p("Zhuangzi",
            a(ArquetipoSuporte.ANTI_CONTROLE, ArquetipoSuporte.DESENGAGE, ArquetipoSuporte.TANQUE),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.LUTAS_LONGAS),
            c(TipoComposicao.CONTROLE_PESADO, TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.PICKOFF),
            c(TipoComposicao.POKE, TipoComposicao.HIPERCARREGADOR),
            8, 3, 10, 6, 5, 6, 4,
            "Counter especializado para controle pesado e engage em cadeia."),
        p("Ziya",
            a(ArquetipoSuporte.POKE, ArquetipoSuporte.CONTROLE_DE_AREA, ArquetipoSuporte.AMPLIFICADOR),
            c(TipoComposicao.POKE, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.DIVE, TipoComposicao.ALTA_MOBILIDADE, TipoComposicao.PICKOFF),
            4, 4, 5, 2, 8, 5, 7,
            "Escala e controla corredores, mas precisa de proteção contra dive.")
    );

    public List<PerfilSuporte> listarTodos() {
        return perfis;
    }

    private PerfilSuporte p(
        String nome,
        List<ArquetipoSuporte> arquetipos,
        List<TipoComposicao> fortalece,
        List<TipoComposicao> quebra,
        List<TipoComposicao> sofreContra,
        int protecaoCarry,
        int iniciacao,
        int desengage,
        int sustentacao,
        int pressaoRota,
        int mobilidadeMapa,
        int dependenciaCoordenacao,
        String observacao
    ) {
        return new PerfilSuporte(
            nome,
            arquetipos,
            fortalece,
            quebra,
            sofreContra,
            protecaoCarry,
            iniciacao,
            desengage,
            sustentacao,
            pressaoRota,
            mobilidadeMapa,
            dependenciaCoordenacao,
            List.of(observacao)
        );
    }

    @SafeVarargs
    private final <T> List<T> a(T... valores) {
        return List.of(valores);
    }

    @SafeVarargs
    private final <T> List<T> c(T... valores) {
        return List.of(valores);
    }
}
