package br.com.carlosdaniel.hokdraftcoach.repository;

import java.util.List;

import org.springframework.stereotype.Repository;

import br.com.carlosdaniel.hokdraftcoach.model.ArquetipoMid;
import br.com.carlosdaniel.hokdraftcoach.model.PerfilMidLane;
import br.com.carlosdaniel.hokdraftcoach.model.TipoComposicao;

@Repository
public class PerfilMidRepository {

    private final List<PerfilMidLane> perfis = List.of(
        p("Ser do Fluxo (Mago)",
            a(ArquetipoMid.UTILITARIO, ArquetipoMid.CONTROLADOR, ArquetipoMid.POKE),
            c(TipoComposicao.ROTACAO, TipoComposicao.POKE, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.LUTAS_LONGAS),
            c(TipoComposicao.DIVE, TipoComposicao.PICKOFF),
            6, 7, 7, 6, 7, 7, 6, 6, 6,
            "Escolha adaptável para completar dano, controle ou utilidade sem especialização extrema."),
        p("Garuda",
            a(ArquetipoMid.POKE, ArquetipoMid.ROAMER, ArquetipoMid.ARTILHEIRO),
            c(TipoComposicao.POKE, TipoComposicao.ROTACAO, TipoComposicao.CERCO),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.DIVE, TipoComposicao.PICKOFF),
            7, 7, 9, 5, 9, 7, 6, 6, 6,
            "Velocidade e alcance permitem desgastar e mover a equipe antes da resposta inimiga."),
        p("Lorion",
            a(ArquetipoMid.CONTROLADOR, ArquetipoMid.EXPLOSAO, ArquetipoMid.ROAMER),
            c(TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.OBJETIVOS, TipoComposicao.ULTIMATES_DECISIVAS),
            c(TipoComposicao.DIVE, TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.ENGAGE_AGRUPADO),
            c(TipoComposicao.POKE, TipoComposicao.PICKOFF),
            8, 8, 8, 9, 7, 9, 7, 6, 8,
            "O posicionamento do orbe cria ameaça simultânea de controle, burst e mobilidade ao redor de objetivos."),
        p("Angela",
            a(ArquetipoMid.ARTILHEIRO, ArquetipoMid.EXPLOSAO, ArquetipoMid.PICKOFF),
            c(TipoComposicao.PICKOFF, TipoComposicao.EXPLOSAO, TipoComposicao.POKE),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.HIPERCARREGADOR, TipoComposicao.DIVE),
            c(TipoComposicao.DIVE, TipoComposicao.ESCUDOS_E_CURA, TipoComposicao.FRONT_TO_BACK),
            8, 8, 6, 7, 9, 10, 5, 6, 5,
            "Elimina alvos presos em uma rotação, mas perde valor quando o burst é absorvido ou evitado."),
        p("Da Qiao",
            a(ArquetipoMid.UTILITARIO, ArquetipoMid.ROAMER, ArquetipoMid.PUSHER),
            c(TipoComposicao.SPLIT_PUSH, TipoComposicao.ROTACAO, TipoComposicao.PRESSAO_DE_TORRE),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.LUTAS_LONGAS, TipoComposicao.ALVOS_IMOVEIS),
            c(TipoComposicao.DIVE, TipoComposicao.PICKOFF),
            7, 8, 10, 8, 7, 5, 4, 8, 10,
            "Muda o mapa com retorno à base e teleporte; seu valor cresce muito com coordenação."),
        p("Daji",
            a(ArquetipoMid.PICKOFF, ArquetipoMid.EXPLOSAO, ArquetipoMid.ROAMER),
            c(TipoComposicao.PICKOFF, TipoComposicao.EXPLOSAO, TipoComposicao.ROTACAO),
            c(TipoComposicao.ALTA_MOBILIDADE, TipoComposicao.HIPERCARREGADOR, TipoComposicao.ALVOS_IMOVEIS),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.ESCUDOS_E_CURA, TipoComposicao.DIVE),
            7, 6, 8, 8, 6, 10, 3, 5, 4,
            "Controle garantido e burst punem um alvo isolado, mas não atravessam bem linhas de frente resistentes."),
        p("Diaochan",
            a(ArquetipoMid.MAGO_DE_BATALHA, ArquetipoMid.SUSTENTACAO, ArquetipoMid.ESCALAMENTO),
            c(TipoComposicao.LUTAS_LONGAS, TipoComposicao.DIVE, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.ESCUDOS_E_CURA),
            c(TipoComposicao.CONTROLE_PESADO, TipoComposicao.EXPLOSAO, TipoComposicao.POKE),
            6, 6, 7, 6, 5, 7, 10, 6, 7,
            "Vence lutas prolongadas quando pode dançar dentro da própria zona e evitar controles-chave."),
        p("Dr Bian Qe",
            a(ArquetipoMid.MAGO_DE_BATALHA, ArquetipoMid.SUSTENTACAO, ArquetipoMid.UTILITARIO),
            c(TipoComposicao.LUTAS_LONGAS, TipoComposicao.ESCUDOS_E_CURA, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.POKE, TipoComposicao.ESCUDOS_E_CURA, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.EXPLOSAO, TipoComposicao.DIVE, TipoComposicao.PICKOFF),
            7, 7, 5, 4, 7, 5, 9, 6, 5,
            "Acúmulos de veneno e cura vencem desgaste; burst rápido impede que o kit amadureça."),
        p("Gan & Mo",
            a(ArquetipoMid.ARTILHEIRO, ArquetipoMid.EXPLOSAO, ArquetipoMid.POKE),
            c(TipoComposicao.POKE, TipoComposicao.CERCO, TipoComposicao.PICKOFF),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.FRONT_TO_BACK, TipoComposicao.OBJETIVOS),
            c(TipoComposicao.DIVE, TipoComposicao.ALTA_MOBILIDADE, TipoComposicao.PICKOFF),
            7, 7, 4, 3, 10, 10, 5, 5, 6,
            "A precisão de longa distância remove carries antes da luta, desde que exista proteção frontal."),
        p("Gao Jianli",
            a(ArquetipoMid.MAGO_DE_BATALHA, ArquetipoMid.EXPLOSAO, ArquetipoMid.ASSASSINO_MAGICO),
            c(TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.DIVE, TipoComposicao.ULTIMATES_DECISIVAS),
            c(TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.HIPERCARREGADOR),
            c(TipoComposicao.DESENGAGE, TipoComposicao.POKE, TipoComposicao.CONTROLE_PESADO),
            6, 7, 7, 5, 4, 8, 9, 5, 6,
            "Precisa entrar na formação inimiga; agrupamento aliado e controle prévio transformam sua ultimate."),
        p("Haya",
            a(ArquetipoMid.POKE, ArquetipoMid.ROAMER, ArquetipoMid.MAGO_DE_BATALHA),
            c(TipoComposicao.POKE, TipoComposicao.ROTACAO, TipoComposicao.ALTA_MOBILIDADE),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.FRONT_TO_BACK, TipoComposicao.CERCO),
            c(TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.DIVE, TipoComposicao.CONTROLE_PESADO),
            8, 8, 9, 5, 9, 7, 8, 6, 6,
            "Ganha ritmo com dano consistente e rotação, mas perde espaço quando é forçada a lutar de perto."),
        p("Heino",
            a(ArquetipoMid.POKE, ArquetipoMid.SUSTENTACAO, ArquetipoMid.ESCALAMENTO),
            c(TipoComposicao.POKE, TipoComposicao.LUTAS_LONGAS, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.POKE, TipoComposicao.FRONT_TO_BACK, TipoComposicao.OBJETIVOS),
            c(TipoComposicao.EXPLOSAO, TipoComposicao.PICKOFF, TipoComposicao.DIVE),
            7, 8, 7, 6, 9, 7, 8, 8, 7,
            "Alcance e sustentação geram consistência, mas controles e burst impedem o reposicionamento temporal."),
        p("Kongming",
            a(ArquetipoMid.ASSASSINO_MAGICO, ArquetipoMid.EXPLOSAO, ArquetipoMid.ROAMER),
            c(TipoComposicao.DIVE, TipoComposicao.PICKOFF, TipoComposicao.EXPLOSAO),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.HIPERCARREGADOR, TipoComposicao.ROTACAO),
            c(TipoComposicao.CONTROLE_PESADO, TipoComposicao.FRONT_TO_BACK, TipoComposicao.ESCUDOS_E_CURA),
            8, 8, 10, 4, 6, 10, 7, 6, 6,
            "Executa alvos e encadeia resets; precisa que a equipe produza a primeira janela de vida baixa."),
        p("Lady Zhen",
            a(ArquetipoMid.CONTROLADOR, ArquetipoMid.ZONEAMENTO, ArquetipoMid.ANTI_DIVE),
            c(TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.FRONT_TO_BACK, TipoComposicao.OBJETIVOS),
            c(TipoComposicao.DIVE, TipoComposicao.ALTA_MOBILIDADE, TipoComposicao.ENGAGE_AGRUPADO),
            c(TipoComposicao.POKE, TipoComposicao.ASSASSINO_MAGICO, TipoComposicao.DESENGAGE),
            7, 9, 6, 10, 8, 7, 7, 7, 6,
            "Congelamento e controle em área punem inimigos agrupados ou obrigados a entrar."),
        p("Liang",
            a(ArquetipoMid.CONTROLADOR, ArquetipoMid.PICKOFF, ArquetipoMid.ANTI_DIVE),
            c(TipoComposicao.PICKOFF, TipoComposicao.CONTROLE_PESADO, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.DIVE, TipoComposicao.ALTA_MOBILIDADE, TipoComposicao.ULTIMATES_DECISIVAS),
            c(TipoComposicao.POKE, TipoComposicao.SPLIT_PUSH, TipoComposicao.LUTAS_LONGAS),
            7, 8, 7, 10, 7, 6, 5, 7, 7,
            "A supressão interrompe a principal ameaça, mas exige acompanhamento para converter o controle."),
        p("Mai Shiranui",
            a(ArquetipoMid.ASSASSINO_MAGICO, ArquetipoMid.POKE, ArquetipoMid.ROAMER),
            c(TipoComposicao.PICKOFF, TipoComposicao.DIVE, TipoComposicao.ROTACAO),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.ARTILHARIA, TipoComposicao.HIPERCARREGADOR),
            c(TipoComposicao.CONTROLE_PESADO, TipoComposicao.FRONT_TO_BACK, TipoComposicao.ESCUDOS_E_CURA),
            8, 7, 10, 8, 8, 10, 5, 6, 7,
            "Mobilidade e deslocamentos castigam backlines imóveis; controles garantidos limitam suas entradas."),
        p("Milady",
            a(ArquetipoMid.PUSHER, ArquetipoMid.CERCO, ArquetipoMid.CONTROLADOR),
            c(TipoComposicao.PRESSAO_DE_TORRE, TipoComposicao.CERCO, TipoComposicao.WAVE_CLEAR),
            c(TipoComposicao.ROTACAO, TipoComposicao.SPLIT_PUSH, TipoComposicao.ESCALAMENTO),
            c(TipoComposicao.DIVE, TipoComposicao.ALTA_MOBILIDADE, TipoComposicao.ENGAGE_AGRUPADO),
            9, 10, 6, 5, 7, 7, 8, 7, 4,
            "Invocações convertem ausência inimiga em torres; assassinos móveis punem sua baixa mobilidade."),
        p("Mozi",
            a(ArquetipoMid.ARTILHEIRO, ArquetipoMid.CONTROLADOR, ArquetipoMid.ANTI_DIVE),
            c(TipoComposicao.POKE, TipoComposicao.PICKOFF, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.DIVE, TipoComposicao.ALTA_MOBILIDADE, TipoComposicao.ULTIMATES_DECISIVAS),
            c(TipoComposicao.ESCUDOS_E_CURA, TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.LUTAS_LONGAS),
            8, 8, 6, 10, 10, 8, 5, 8, 7,
            "Controle à distância interrompe entradas e canais; sustain reduz o valor do poke isolado."),
        p("Nuwa",
            a(ArquetipoMid.ARTILHEIRO, ArquetipoMid.ZONEAMENTO, ArquetipoMid.ROAMER),
            c(TipoComposicao.POKE, TipoComposicao.CERCO, TipoComposicao.OBJETIVOS),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.DIVE, TipoComposicao.ALTA_MOBILIDADE, TipoComposicao.PICKOFF),
            7, 9, 8, 8, 10, 9, 6, 7, 8,
            "Cria terreno, fecha corredores e influencia o mapa inteiro, mas precisa de distância e visão."),
        p("Shangguan",
            a(ArquetipoMid.ASSASSINO_MAGICO, ArquetipoMid.EXPLOSAO, ArquetipoMid.ROAMER),
            c(TipoComposicao.DIVE, TipoComposicao.PICKOFF, TipoComposicao.EXPLOSAO),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.HIPERCARREGADOR, TipoComposicao.ARTILHARIA),
            c(TipoComposicao.CONTROLE_PESADO, TipoComposicao.ANTI_DIVE, TipoComposicao.FRONT_TO_BACK),
            7, 7, 10, 4, 6, 10, 5, 5, 7,
            "Acesso direto à backline e invulnerabilidade recompensam execução; controle antecipado corta a sequência."),
        p("Shi",
            a(ArquetipoMid.PICKOFF, ArquetipoMid.CONTROLADOR, ArquetipoMid.UTILITARIO),
            c(TipoComposicao.PICKOFF, TipoComposicao.EXPLOSAO, TipoComposicao.ENGAGE_AGRUPADO),
            c(TipoComposicao.HIPERCARREGADOR, TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.ALTA_MOBILIDADE, TipoComposicao.DIVE, TipoComposicao.POKE),
            6, 7, 7, 10, 8, 6, 4, 7, 9,
            "Reposicionar um inimigo cria abates sem exigir dano próprio, mas depende muito do follow-up aliado."),
        p("Sima Yi",
            a(ArquetipoMid.ASSASSINO_MAGICO, ArquetipoMid.ROAMER, ArquetipoMid.ANTI_DIVE),
            c(TipoComposicao.DIVE, TipoComposicao.PICKOFF, TipoComposicao.ROTACAO),
            c(TipoComposicao.POKE, TipoComposicao.ARTILHARIA, TipoComposicao.ALVOS_IMOVEIS),
            c(TipoComposicao.CONTROLE_PESADO, TipoComposicao.FRONT_TO_BACK, TipoComposicao.ESCUDOS_E_CURA),
            8, 8, 10, 7, 4, 10, 6, 6, 6,
            "Silêncio e chegada global punem magos frágeis; formação resistente e controle negam sua saída."),
        p("Wang Zhaojun",
            a(ArquetipoMid.CONTROLADOR, ArquetipoMid.ZONEAMENTO, ArquetipoMid.ANTI_DIVE),
            c(TipoComposicao.OBJETIVOS, TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.DIVE, TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.ALVOS_IMOVEIS),
            c(TipoComposicao.ALTA_MOBILIDADE, TipoComposicao.PICKOFF, TipoComposicao.SPLIT_PUSH),
            7, 9, 6, 10, 8, 8, 7, 8, 6,
            "Congelamento e tempestade dominam zonas de objetivo e corredores estreitos."),
        p("Xiao Qiao",
            a(ArquetipoMid.POKE, ArquetipoMid.EXPLOSAO, ArquetipoMid.ARTILHEIRO),
            c(TipoComposicao.POKE, TipoComposicao.EXPLOSAO, TipoComposicao.ENGAGE_AGRUPADO),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.HIPERCARREGADOR),
            c(TipoComposicao.DIVE, TipoComposicao.FRONT_TO_BACK, TipoComposicao.PICKOFF),
            8, 8, 7, 7, 9, 9, 6, 6, 5,
            "Alcance e dano em área castigam agrupamento, mas a falta de mobilidade exige proteção."),
        p("Yixing",
            a(ArquetipoMid.CONTROLADOR, ArquetipoMid.ZONEAMENTO, ArquetipoMid.UTILITARIO),
            c(TipoComposicao.OBJETIVOS, TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.ULTIMATES_DECISIVAS),
            c(TipoComposicao.DIVE, TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.POKE, TipoComposicao.SPLIT_PUSH, TipoComposicao.ALTA_MOBILIDADE),
            7, 9, 6, 10, 8, 7, 7, 8, 9,
            "O tabuleiro delimita onde a luta pode acontecer e multiplica dano em área aliado."),
        p("Zhou Yu",
            a(ArquetipoMid.ZONEAMENTO, ArquetipoMid.PUSHER, ArquetipoMid.MAGO_DE_BATALHA),
            c(TipoComposicao.CERCO, TipoComposicao.OBJETIVOS, TipoComposicao.PRESSAO_DE_TORRE),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.LUTAS_LONGAS),
            c(TipoComposicao.DIVE, TipoComposicao.ALTA_MOBILIDADE, TipoComposicao.PICKOFF),
            9, 10, 6, 7, 8, 6, 9, 7, 7,
            "Fogo persistente controla território, ondas e torres; inimigos móveis atravessam sua zona."),
        p("Ziya",
            a(ArquetipoMid.ARTILHEIRO, ArquetipoMid.ESCALAMENTO, ArquetipoMid.UTILITARIO),
            c(TipoComposicao.POKE, TipoComposicao.CERCO, TipoComposicao.ESCALAMENTO),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.FRONT_TO_BACK, TipoComposicao.OBJETIVOS),
            c(TipoComposicao.DIVE, TipoComposicao.PICKOFF, TipoComposicao.ALTA_MOBILIDADE),
            6, 8, 6, 7, 10, 8, 5, 6, 7,
            "Alcance e progressão de nível fortalecem o plano tardio, mas o herói precisa de proteção."),
        p("Yuhuan",
            a(ArquetipoMid.SUSTENTACAO, ArquetipoMid.POKE, ArquetipoMid.ROAMER),
            c(TipoComposicao.LUTAS_LONGAS, TipoComposicao.POKE, TipoComposicao.ALTA_MOBILIDADE),
            c(TipoComposicao.POKE, TipoComposicao.FRONT_TO_BACK, TipoComposicao.ROTACAO),
            c(TipoComposicao.EXPLOSAO, TipoComposicao.DIVE, TipoComposicao.PICKOFF),
            7, 8, 9, 5, 8, 6, 8, 7, 8,
            "Cura, mobilidade e desgaste dão ritmo à equipe; burst impede que a sustentação tenha tempo." )
    );

    public List<PerfilMidLane> listarTodos() {
        return perfis;
    }

    private PerfilMidLane p(
        String nome,
        List<ArquetipoMid> arquetipos,
        List<TipoComposicao> fortalece,
        List<TipoComposicao> quebra,
        List<TipoComposicao> sofreContra,
        int pressaoRota,
        int waveClear,
        int rotacao,
        int controle,
        int poke,
        int explosao,
        int danoSustentado,
        int seguranca,
        int dependenciaCoordenacao,
        String observacao
    ) {
        return new PerfilMidLane(
            nome,
            arquetipos,
            fortalece,
            quebra,
            sofreContra,
            pressaoRota,
            waveClear,
            rotacao,
            controle,
            poke,
            explosao,
            danoSustentado,
            seguranca,
            dependenciaCoordenacao,
            List.of(observacao)
        );
    }

    @SafeVarargs
    private final <T> List<T> a(T... valores) {
        return List.of(valores);
    }

    @SafeVarargs
    private final <T> List<T> c(T... valores) {
        return List.of(valores);
    }
}
