package br.com.carlosdaniel.hokdraftcoach.repository;

import java.util.List;

import org.springframework.stereotype.Repository;

import br.com.carlosdaniel.hokdraftcoach.model.ArquetipoClash;
import br.com.carlosdaniel.hokdraftcoach.model.PerfilClashLane;
import br.com.carlosdaniel.hokdraftcoach.model.TipoComposicao;

@Repository
public class PerfilClashRepository {

    private final List<PerfilClashLane> perfis = List.of(
        p("Ata", a(ArquetipoClash.TANQUE, ArquetipoClash.INICIADOR, ArquetipoClash.CONTROLADOR),
            c(TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.FRONT_TO_BACK, TipoComposicao.OBJETIVOS),
            c(TipoComposicao.DIVE, TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.ALTA_MOBILIDADE),
            c(TipoComposicao.POKE, TipoComposicao.DESENGAGE, TipoComposicao.ANTI_TANQUE),
            n(6,7,8,7,4,6,9,10,6,5,6,8,6),
            "Controle de terreno e linha de frente são mais valiosos que o X1 puro."),
        p("Devara", a(ArquetipoClash.BRUISER, ArquetipoClash.DUELISTA, ArquetipoClash.SUSTENTACAO),
            c(TipoComposicao.LUTAS_LONGAS, TipoComposicao.FRONT_TO_BACK, TipoComposicao.DIVE),
            c(TipoComposicao.EXPLOSAO, TipoComposicao.CONTROLE_PESADO, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.POKE, TipoComposicao.DESENGAGE, TipoComposicao.ANTI_TANQUE),
            n(9,9,8,8,7,8,8,8,9,8,9,8,5),
            "Herói novo: escudo, anti-controle e energia favorecem trocas extensas."),
        p("Fatih", a(ArquetipoClash.JUGGERNAUT, ArquetipoClash.DUELISTA, ArquetipoClash.SUSTENTACAO),
            c(TipoComposicao.LUTAS_LONGAS, TipoComposicao.FRONT_TO_BACK, TipoComposicao.ESCUDOS_E_CURA),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.CONTROLE_PESADO, TipoComposicao.LUTAS_LONGAS),
            c(TipoComposicao.POKE, TipoComposicao.DESENGAGE, TipoComposicao.EXPLOSAO),
            n(7,9,10,7,7,5,6,7,10,7,8,6,5),
            "Roubo de vida exige contato contínuo; sofre quando é kiteado."),
        p("Florentino", a(ArquetipoClash.DUELISTA, ArquetipoClash.FLanqueador, ArquetipoClash.SUSTENTACAO),
            c(TipoComposicao.SPLIT_PUSH, TipoComposicao.DIVE, TipoComposicao.PICKOFF),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.LUTAS_LONGAS),
            c(TipoComposicao.CONTROLE_PESADO, TipoComposicao.EXPLOSAO, TipoComposicao.DESENGAGE),
            n(10,10,9,8,9,8,6,5,10,9,9,6,10),
            "O melhor X1 da rota quando executado corretamente, mas exige precisão."),
        p("Ser do Fluxo (Tanque)", a(ArquetipoClash.TANQUE, ArquetipoClash.INICIADOR, ArquetipoClash.UTILITARIO),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.ANTI_DIVE),
            c(TipoComposicao.DIVE, TipoComposicao.EXPLOSAO, TipoComposicao.CONTROLE_PESADO),
            c(TipoComposicao.ANTI_TANQUE, TipoComposicao.POKE, TipoComposicao.SPLIT_PUSH),
            n(6,6,8,7,4,7,9,10,6,6,7,9,4),
            "Completa drafts sem linha de frente e absorve a primeira rotação."),
        p("Lapulapu", a(ArquetipoClash.TANQUE, ArquetipoClash.INICIADOR, ArquetipoClash.UTILITARIO),
            c(TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.FRONT_TO_BACK, TipoComposicao.CONTROLE_PESADO),
            c(TipoComposicao.DIVE, TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.HIPERCARREGADOR),
            c(TipoComposicao.POKE, TipoComposicao.DESENGAGE, TipoComposicao.ANTI_TANQUE),
            n(6,6,8,7,4,6,9,10,5,5,6,8,5),
            "Escolha flex que troca pressão lateral por team fight confiável."),
        p("Allain", a(ArquetipoClash.DUELISTA, ArquetipoClash.ANTI_TANQUE, ArquetipoClash.ESCALAMENTO),
            c(TipoComposicao.SPLIT_PUSH, TipoComposicao.LUTAS_LONGAS, TipoComposicao.ESCALAMENTO),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.ANTI_TANQUE, TipoComposicao.ESCUDOS_E_CURA),
            c(TipoComposicao.POKE, TipoComposicao.CONTROLE_PESADO, TipoComposicao.SNOWBALL),
            n(6,9,8,7,9,5,6,6,10,8,10,7,5),
            "Dano misto e invulnerabilidade escalam muito, mas a rota inicial é vulnerável."),
        p("Arthur", a(ArquetipoClash.BRUISER, ArquetipoClash.TANQUE, ArquetipoClash.ANTI_CARRY),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.ANTI_DIVE, TipoComposicao.CONTROLE_PESADO),
            c(TipoComposicao.ALTA_MOBILIDADE, TipoComposicao.ASSASSINO_MAGICO, TipoComposicao.DIVE),
            c(TipoComposicao.POKE, TipoComposicao.ANTI_TANQUE, TipoComposicao.LUTAS_LONGAS),
            n(7,7,8,8,5,7,7,9,6,6,7,10,2),
            "Silêncio e resistência entregam resposta simples contra carries móveis."),
        p("Augran", a(ArquetipoClash.JUGGERNAUT, ArquetipoClash.ANTI_TANQUE, ArquetipoClash.SUSTENTACAO),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.LUTAS_LONGAS, TipoComposicao.OBJETIVOS),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.ESCUDOS_E_CURA, TipoComposicao.ANTI_TANQUE),
            c(TipoComposicao.POKE, TipoComposicao.DESENGAGE, TipoComposicao.CONTROLE_PESADO),
            n(9,10,10,8,8,7,8,9,10,9,10,9,5),
            "Execução e sustentação mantêm pressão mesmo contra frontlines pesadas."),
        p("Bai Qi", a(ArquetipoClash.TANQUE, ArquetipoClash.INICIADOR, ArquetipoClash.CONTROLADOR),
            c(TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.FRONT_TO_BACK, TipoComposicao.ULTIMATES_DECISIVAS),
            c(TipoComposicao.DIVE, TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.HIPERCARREGADOR),
            c(TipoComposicao.POKE, TipoComposicao.DESENGAGE, TipoComposicao.ANTI_TANQUE),
            n(6,6,9,7,4,7,10,10,6,5,7,8,7),
            "Provocação em área é uma das melhores iniciações quando há follow-up."),
        p("Biron", a(ArquetipoClash.BRUISER, ArquetipoClash.DUELISTA, ArquetipoClash.SUSTENTACAO),
            c(TipoComposicao.SNOWBALL, TipoComposicao.LUTAS_LONGAS, TipoComposicao.DIVE),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.FRONT_TO_BACK, TipoComposicao.ESCALAMENTO),
            c(TipoComposicao.POKE, TipoComposicao.DESENGAGE, TipoComposicao.CONTROLE_PESADO),
            n(9,9,9,8,7,7,7,7,9,8,7,8,5),
            "Pressão e cura no início criam prioridade para objetivo e invasão."),
        p("Charlotte", a(ArquetipoClash.DUELISTA, ArquetipoClash.BRUISER, ArquetipoClash.FLanqueador),
            c(TipoComposicao.DIVE, TipoComposicao.LUTAS_LONGAS, TipoComposicao.SPLIT_PUSH),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.FRONT_TO_BACK, TipoComposicao.LUTAS_LONGAS),
            c(TipoComposicao.CONTROLE_PESADO, TipoComposicao.POKE, TipoComposicao.EXPLOSAO),
            n(8,9,8,8,8,8,6,6,9,7,8,7,6),
            "Redução de dano e mobilidade sustentam duelos e flancos longos."),
        p("Chicha", a(ArquetipoClash.DUELISTA, ArquetipoClash.ESCALAMENTO, ArquetipoClash.FLanqueador),
            c(TipoComposicao.LUTAS_LONGAS, TipoComposicao.FRONT_TO_BACK, TipoComposicao.ESCALAMENTO),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.OBJETIVOS, TipoComposicao.ALVOS_IMOVEIS),
            c(TipoComposicao.DESENGAGE, TipoComposicao.POKE, TipoComposicao.CONTROLE_PESADO),
            n(8,9,8,9,8,7,6,6,10,8,9,7,6),
            "Entra como segunda onda após o gasto dos controles defensivos."),
        p("Diaochan", a(ArquetipoClash.MAGO_DE_ROTA, ArquetipoClash.DUELISTA, ArquetipoClash.ANTI_TANQUE),
            c(TipoComposicao.LUTAS_LONGAS, TipoComposicao.ASSASSINO_MAGICO, TipoComposicao.ANTI_TANQUE),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.CONTROLE_PESADO, TipoComposicao.ALVOS_IMOVEIS),
            c(TipoComposicao.EXPLOSAO, TipoComposicao.CONTROLE_PESADO, TipoComposicao.POKE),
            n(8,10,9,8,5,7,5,3,10,8,9,5,9),
            "Dano verdadeiro e invulnerabilidade vencem frontlines sem controle preciso."),
        p("Donghuang", a(ArquetipoClash.TANQUE, ArquetipoClash.CONTROLADOR, ArquetipoClash.ANTI_CARRY),
            c(TipoComposicao.PICKOFF, TipoComposicao.ANTI_DIVE, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.DIVE, TipoComposicao.ALTA_MOBILIDADE, TipoComposicao.HIPERCARREGADOR),
            c(TipoComposicao.POKE, TipoComposicao.SPLIT_PUSH, TipoComposicao.ANTI_TANQUE),
            n(7,8,9,7,4,6,9,10,6,5,7,8,6),
            "Supressão inevitável remove o carry ou o mergulhador da luta."),
        p("Dun", a(ArquetipoClash.TANQUE, ArquetipoClash.BRUISER, ArquetipoClash.SUSTENTACAO),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.ANTI_DIVE),
            c(TipoComposicao.DIVE, TipoComposicao.EXPLOSAO, TipoComposicao.ALVOS_IMOVEIS),
            c(TipoComposicao.ANTI_TANQUE, TipoComposicao.POKE, TipoComposicao.DESENGAGE),
            n(8,8,9,8,6,7,8,9,7,7,8,9,4),
            "Escudo, controle e sustain fazem dele um blind pick seguro."),
        p("Fuzi", a(ArquetipoClash.DUELISTA, ArquetipoClash.SPLIT_PUSHER, ArquetipoClash.ANTI_CARRY),
            c(TipoComposicao.SPLIT_PUSH, TipoComposicao.PICKOFF, TipoComposicao.ESCALAMENTO),
            c(TipoComposicao.HIPERCARREGADOR, TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.ESCALAMENTO),
            c(TipoComposicao.POKE, TipoComposicao.CONTROLE_PESADO, TipoComposicao.ENGAGE_AGRUPADO),
            n(8,10,8,8,10,5,6,5,10,6,9,7,5),
            "Aprisionamento e dano sustentado dominam a lateral e prendem carries."),
        p("Guan Yu", a(ArquetipoClash.FLanqueador, ArquetipoClash.GLOBAL, ArquetipoClash.INICIADOR),
            c(TipoComposicao.ROTACAO, TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.PICKOFF),
            c(TipoComposicao.POKE, TipoComposicao.ARTILHARIA, TipoComposicao.ALVOS_IMOVEIS),
            c(TipoComposicao.CONTROLE_PESADO, TipoComposicao.DESENGAGE, TipoComposicao.ANTI_DIVE),
            n(8,7,6,8,8,10,9,7,7,9,8,6,9),
            "Valor vem da rotação e do flanco, não de permanecer no 1x1 estático."),
        p("Heino", a(ArquetipoClash.MAGO_DE_ROTA, ArquetipoClash.SUSTENTACAO, ArquetipoClash.ESCALAMENTO),
            c(TipoComposicao.POKE, TipoComposicao.LUTAS_LONGAS, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.ESCALAMENTO),
            c(TipoComposicao.DIVE, TipoComposicao.PICKOFF, TipoComposicao.ASSASSINO_MAGICO),
            n(8,8,9,9,6,7,4,4,9,7,10,8,7),
            "Alcance e sustain controlam a rota, mas exigem proteção contra dive."),
        p("Kaizer", a(ArquetipoClash.JUGGERNAUT, ArquetipoClash.DUELISTA, ArquetipoClash.ANTI_CARRY),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.DIVE, TipoComposicao.LUTAS_LONGAS),
            c(TipoComposicao.HIPERCARREGADOR, TipoComposicao.FRONT_TO_BACK, TipoComposicao.ESCUDOS_E_CURA),
            c(TipoComposicao.POKE, TipoComposicao.DESENGAGE, TipoComposicao.ALTA_MOBILIDADE),
            n(8,10,8,8,7,6,7,9,9,9,8,9,4),
            "Transformação absorve burst e permite chegar ao principal carry."),
        p("Li Xin", a(ArquetipoClash.SPLIT_PUSHER, ArquetipoClash.BRUISER, ArquetipoClash.FLanqueador),
            c(TipoComposicao.SPLIT_PUSH, TipoComposicao.POKE, TipoComposicao.SNOWBALL),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.ESCALAMENTO, TipoComposicao.PRESSAO_DE_TORRE),
            c(TipoComposicao.CONTROLE_PESADO, TipoComposicao.DESENGAGE, TipoComposicao.ENGAGE_AGRUPADO),
            n(9,9,8,10,10,8,7,6,9,9,9,8,8),
            "Duas formas permitem alternar poke, all-in e pressão lateral."),
        p("Lian Po", a(ArquetipoClash.TANQUE, ArquetipoClash.INICIADOR, ArquetipoClash.CONTROLADOR),
            c(TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.FRONT_TO_BACK, TipoComposicao.CONTROLE_PESADO),
            c(TipoComposicao.DIVE, TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.HIPERCARREGADOR),
            c(TipoComposicao.POKE, TipoComposicao.ANTI_TANQUE, TipoComposicao.SPLIT_PUSH),
            n(7,7,9,8,4,7,10,10,6,6,7,9,5),
            "Anti-controle e múltiplas entradas fornecem engage muito confiável."),
        p("Liu Bang", a(ArquetipoClash.GLOBAL, ArquetipoClash.TANQUE, ArquetipoClash.SPLIT_PUSHER),
            c(TipoComposicao.SPLIT_PUSH, TipoComposicao.ROTACAO, TipoComposicao.DIVE),
            c(TipoComposicao.PICKOFF, TipoComposicao.SNOWBALL, TipoComposicao.SPLIT_PUSH),
            c(TipoComposicao.POKE, TipoComposicao.ANTI_TANQUE, TipoComposicao.PRESSAO_DE_TORRE),
            n(6,6,8,8,9,10,6,9,6,5,8,9,8),
            "Pressiona a lateral e transforma qualquer luta em superioridade numérica."),
        p("Lu Bu", a(ArquetipoClash.JUGGERNAUT, ArquetipoClash.ANTI_TANQUE, ArquetipoClash.INICIADOR),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.LUTAS_LONGAS),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.ANTI_TANQUE, TipoComposicao.ESCUDOS_E_CURA),
            c(TipoComposicao.POKE, TipoComposicao.DESENGAGE, TipoComposicao.ALTA_MOBILIDADE),
            n(7,9,8,8,7,6,9,9,10,8,9,7,6),
            "Dano verdadeiro e ultimate em área punem equipes que se agrupam."),
        p("Mayene", a(ArquetipoClash.DUELISTA, ArquetipoClash.FLanqueador, ArquetipoClash.CONTROLADOR),
            c(TipoComposicao.DIVE, TipoComposicao.PICKOFF, TipoComposicao.CONTROLE_PESADO),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.FRONT_TO_BACK, TipoComposicao.HIPERCARREGADOR),
            c(TipoComposicao.POKE, TipoComposicao.EXPLOSAO, TipoComposicao.CONTROLE_PESADO),
            n(8,9,7,8,8,9,8,5,8,9,8,6,10),
            "Muitos combos permitem adaptar o X1 e o flanco, mas exigem domínio."),
        p("Menki", a(ArquetipoClash.BRUISER, ArquetipoClash.TANQUE, ArquetipoClash.SPLIT_PUSHER),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.LUTAS_LONGAS, TipoComposicao.SPLIT_PUSH),
            c(TipoComposicao.EXPLOSAO, TipoComposicao.FRONT_TO_BACK, TipoComposicao.ALVOS_IMOVEIS),
            c(TipoComposicao.ANTI_TANQUE, TipoComposicao.POKE, TipoComposicao.DESENGAGE),
            n(8,9,9,8,9,6,6,9,9,7,9,8,5),
            "Escudos e dano misto oferecem lateral forte e frontline secundária."),
        p("Mi Yue", a(ArquetipoClash.MAGO_DE_ROTA, ArquetipoClash.DUELISTA, ArquetipoClash.SPLIT_PUSHER),
            c(TipoComposicao.SPLIT_PUSH, TipoComposicao.LUTAS_LONGAS, TipoComposicao.ASSASSINO_MAGICO),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.ANTI_TANQUE, TipoComposicao.LUTAS_LONGAS),
            c(TipoComposicao.PICKOFF, TipoComposicao.CONTROLE_PESADO, TipoComposicao.EXPLOSAO),
            n(9,10,10,8,10,7,4,4,10,6,9,9,5),
            "Sustain e alcance dominam o 1x1; contribuição em team fight é menor."),
        p("Mulan", a(ArquetipoClash.DUELISTA, ArquetipoClash.FLanqueador, ArquetipoClash.ANTI_CARRY),
            c(TipoComposicao.DIVE, TipoComposicao.PICKOFF, TipoComposicao.SPLIT_PUSH),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.ARTILHARIA, TipoComposicao.HIPERCARREGADOR),
            c(TipoComposicao.CONTROLE_PESADO, TipoComposicao.FRONT_TO_BACK, TipoComposicao.POKE),
            n(8,9,6,9,9,8,7,5,8,10,8,6,10),
            "Silêncio e burst eliminam backline, mas erro mecânico é muito punido."),
        p("Musashi", a(ArquetipoClash.DUELISTA, ArquetipoClash.ANTI_CARRY, ArquetipoClash.ANTI_TANQUE),
            c(TipoComposicao.DIVE, TipoComposicao.ANTI_DIVE, TipoComposicao.PICKOFF),
            c(TipoComposicao.ESCUDOS_E_CURA, TipoComposicao.ARTILHARIA, TipoComposicao.HIPERCARREGADOR),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.CONTROLE_PESADO, TipoComposicao.LUTAS_LONGAS),
            n(8,9,7,8,7,7,8,7,8,9,8,8,5),
            "Anti-cura e bloqueio de projéteis respondem a sustain e carries."),
        p("Nezha", a(ArquetipoClash.GLOBAL, ArquetipoClash.ANTI_CARRY, ArquetipoClash.FLanqueador),
            c(TipoComposicao.ROTACAO, TipoComposicao.DIVE, TipoComposicao.PICKOFF),
            c(TipoComposicao.ESCUDOS_E_CURA, TipoComposicao.ARTILHARIA, TipoComposicao.SPLIT_PUSH),
            c(TipoComposicao.DESENGAGE, TipoComposicao.CONTROLE_PESADO, TipoComposicao.FRONT_TO_BACK),
            n(7,8,7,8,8,10,9,7,8,8,8,7,7),
            "Ultimate global e anti-cura forçam o carry inimigo a respeitar a lateral."),
        p("Sun Ce", a(ArquetipoClash.GLOBAL, ArquetipoClash.INICIADOR, ArquetipoClash.TANQUE),
            c(TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.ROTACAO, TipoComposicao.DIVE),
            c(TipoComposicao.ARTILHARIA, TipoComposicao.POKE, TipoComposicao.SPLIT_PUSH),
            c(TipoComposicao.DESENGAGE, TipoComposicao.CONTROLE_PESADO, TipoComposicao.ANTI_TANQUE),
            n(8,8,7,9,8,10,10,9,7,8,8,8,7),
            "Navio global converte prioridade de rota em engage sobre outras lanes."),
        p("Ukyo Tachibana", a(ArquetipoClash.DUELISTA, ArquetipoClash.FLanqueador, ArquetipoClash.BRUISER),
            c(TipoComposicao.PICKOFF, TipoComposicao.POKE, TipoComposicao.SNOWBALL),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.ARTILHARIA, TipoComposicao.ESCALAMENTO),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.CONTROLE_PESADO, TipoComposicao.LUTAS_LONGAS),
            n(9,8,7,8,7,8,7,5,7,9,6,7,7),
            "Pressiona cedo com alcance curto e controle, mas perde valor tardio."),
        p("Umbrosa", a(ArquetipoClash.JUGGERNAUT, ArquetipoClash.SUSTENTACAO, ArquetipoClash.ESCALAMENTO),
            c(TipoComposicao.LUTAS_LONGAS, TipoComposicao.FRONT_TO_BACK, TipoComposicao.ESCALAMENTO),
            c(TipoComposicao.EXPLOSAO, TipoComposicao.FRONT_TO_BACK, TipoComposicao.OBJETIVOS),
            c(TipoComposicao.ANTI_TANQUE, TipoComposicao.ESCUDOS_E_CURA, TipoComposicao.POKE),
            n(8,9,10,8,8,6,7,9,10,7,9,8,4),
            "Ressurreição absorve a primeira rotação e prolonga o front-to-back."),
        p("Wuyan", a(ArquetipoClash.TANQUE, ArquetipoClash.CONTROLADOR, ArquetipoClash.BRUISER),
            c(TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.CONTROLE_PESADO, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.DIVE, TipoComposicao.ALTA_MOBILIDADE, TipoComposicao.ALVOS_IMOVEIS),
            c(TipoComposicao.POKE, TipoComposicao.DESENGAGE, TipoComposicao.ANTI_TANQUE),
            n(7,8,7,8,6,7,9,9,7,8,7,8,5),
            "Petrificação ameaça qualquer melee que permaneça no alcance."),
        p("Xiang Yu", a(ArquetipoClash.TANQUE, ArquetipoClash.ANTI_CARRY, ArquetipoClash.CONTROLADOR),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.ANTI_DIVE, TipoComposicao.CONTROLE_PESADO),
            c(TipoComposicao.DIVE, TipoComposicao.EXPLOSAO, TipoComposicao.HIPERCARREGADOR),
            c(TipoComposicao.ANTI_TANQUE, TipoComposicao.POKE, TipoComposicao.SPLIT_PUSH),
            n(7,7,8,8,5,7,8,10,6,6,8,9,4),
            "Deslocamento e mitigação protegem carries e desorganizam engages."),
        p("Yang Jian", a(ArquetipoClash.DUELISTA, ArquetipoClash.BRUISER, ArquetipoClash.ANTI_TANQUE),
            c(TipoComposicao.DIVE, TipoComposicao.LUTAS_LONGAS, TipoComposicao.PICKOFF),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.ESCUDOS_E_CURA),
            c(TipoComposicao.POKE, TipoComposicao.CONTROLE_PESADO, TipoComposicao.DESENGAGE),
            n(8,9,9,8,8,8,7,6,8,9,8,7,7),
            "Marca, execução e dano verdadeiro recompensam perseguição precisa."),
        p("Yao", a(ArquetipoClash.DUELISTA, ArquetipoClash.FLanqueador, ArquetipoClash.SPLIT_PUSHER),
            c(TipoComposicao.DIVE, TipoComposicao.SPLIT_PUSH, TipoComposicao.ROTACAO),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.PICKOFF, TipoComposicao.EXPLOSAO),
            c(TipoComposicao.CONTROLE_PESADO, TipoComposicao.POKE, TipoComposicao.FRONT_TO_BACK),
            n(8,9,7,9,9,9,6,6,8,8,8,7,8),
            "Combos e retorno de dano permitem entrar, absorver burst e recuar."),
        p("Zhuangzi", a(ArquetipoClash.TANQUE, ArquetipoClash.UTILITARIO, ArquetipoClash.SUSTENTACAO),
            c(TipoComposicao.ANTI_DIVE, TipoComposicao.LUTAS_LONGAS, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.CONTROLE_PESADO, TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.PICKOFF),
            c(TipoComposicao.ANTI_TANQUE, TipoComposicao.POKE, TipoComposicao.SPLIT_PUSH),
            n(7,7,9,8,5,7,5,9,8,5,8,10,5),
            "Purificação coletiva quebra composições dependentes de controle."),
        p("Dharma", a(ArquetipoClash.BRUISER, ArquetipoClash.INICIADOR, ArquetipoClash.CONTROLADOR),
            c(TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.PICKOFF, TipoComposicao.OBJETIVOS),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.DIVE, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.POKE, TipoComposicao.DESENGAGE, TipoComposicao.ALTA_MOBILIDADE),
            n(8,8,7,8,7,8,10,7,7,9,7,7,7),
            "Paredes transformam corredores de objetivo em engage explosivo.")
    );

    public List<PerfilClashLane> listarTodos() {
        return perfis;
    }

    private PerfilClashLane p(
        String heroi,
        List<ArquetipoClash> arquetipos,
        List<TipoComposicao> fortalece,
        List<TipoComposicao> quebra,
        List<TipoComposicao> sofreContra,
        int[] notas,
        String observacao
    ) {
        if (notas.length != 13) {
            throw new IllegalArgumentException("O perfil Clash exige 13 notas.");
        }
        return new PerfilClashLane(
            heroi, arquetipos, fortalece, quebra, sofreContra,
            notas[0], notas[1], notas[2], notas[3], notas[4], notas[5],
            notas[6], notas[7], notas[8], notas[9], notas[10], notas[11],
            notas[12], List.of(observacao)
        );
    }

    private int[] n(int... valores) {
        return valores;
    }

    @SafeVarargs
    private final <T> List<T> a(T... valores) {
        return List.of(valores);
    }

    @SafeVarargs
    private final <T> List<T> c(T... valores) {
        return List.of(valores);
    }
}
