package br.com.carlosdaniel.hokdraftcoach.repository;

import java.util.List;

import org.springframework.stereotype.Repository;

import br.com.carlosdaniel.hokdraftcoach.model.ArquetipoJungle;
import br.com.carlosdaniel.hokdraftcoach.model.PerfilJungle;
import br.com.carlosdaniel.hokdraftcoach.model.TipoComposicao;

@Repository
public class PerfilJungleRepository {

    private final List<PerfilJungle> perfis = List.of(
        p("Ata", a(ArquetipoJungle.TANQUE_INICIADOR, ArquetipoJungle.CONTROLADOR, ArquetipoJungle.OBJETIVOS),
            c(TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.FRONT_TO_BACK, TipoComposicao.OBJETIVOS),
            c(TipoComposicao.DIVE, TipoComposicao.ALTA_MOBILIDADE, TipoComposicao.ALVOS_IMOVEIS),
            c(TipoComposicao.POKE, TipoComposicao.DESENGAGE, TipoComposicao.ANTI_TANQUE),
            7, 7, 6, 7, 9, 5, 5, 6, 10, 9, 6,
            "Entrega linha de frente, controle de terreno e segurança em objetivos."),
        p("Butterfly", a(ArquetipoJungle.ASSASSINO_EXECUTOR, ArquetipoJungle.RESET, ArquetipoJungle.GANKER),
            c(TipoComposicao.SNOWBALL, TipoComposicao.PICKOFF, TipoComposicao.EXPLOSAO),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.ARTILHARIA, TipoComposicao.HIPERCARREGADOR),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.CONTROLE_PESADO, TipoComposicao.ANTI_DIVE),
            7, 8, 6, 7, 6, 8, 9, 6, 3, 5, 5,
            "Precisa da primeira eliminação para encadear resets e limpar a luta."),
        p("Fatih", a(ArquetipoJungle.LUTADOR_DUELISTA, ArquetipoJungle.FARMADOR, ArquetipoJungle.ANTI_TANQUE),
            c(TipoComposicao.LUTAS_LONGAS, TipoComposicao.FRONT_TO_BACK, TipoComposicao.ANTI_TANQUE),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.CONTROLE_PESADO, TipoComposicao.LUTAS_LONGAS),
            c(TipoComposicao.POKE, TipoComposicao.EXPLOSAO, TipoComposicao.DESENGAGE),
            7, 6, 7, 9, 7, 6, 7, 9, 7, 7, 5,
            "Roubo de vida e anti-controle recompensam combates corpo a corpo prolongados."),
        p("Agudo", a(ArquetipoJungle.ATIRADOR_JUNGLE, ArquetipoJungle.OBJETIVOS, ArquetipoJungle.UTILITARIO),
            c(TipoComposicao.POKE, TipoComposicao.CERCO, TipoComposicao.OBJETIVOS),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.ESCALAMENTO),
            c(TipoComposicao.DIVE, TipoComposicao.ASSASSINO_MAGICO, TipoComposicao.PICKOFF),
            9, 6, 5, 5, 9, 5, 5, 7, 8, 6, 7,
            "Limpa rapidamente e converte pressão em objetivos, mas precisa de proteção."),
        p("Arke", a(ArquetipoJungle.ASSASSINO_EXECUTOR, ArquetipoJungle.RESET, ArquetipoJungle.INVASOR),
            c(TipoComposicao.PICKOFF, TipoComposicao.SNOWBALL, TipoComposicao.DIVE),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.ARTILHARIA, TipoComposicao.HIPERCARREGADOR),
            c(TipoComposicao.CONTROLE_PESADO, TipoComposicao.FRONT_TO_BACK, TipoComposicao.ANTI_DIVE),
            8, 9, 8, 8, 7, 9, 10, 6, 2, 5, 6,
            "Furtividade e crítico pelas costas criam execuções e resets em sequência."),
        p("Arthur", a(ArquetipoJungle.LUTADOR_DUELISTA, ArquetipoJungle.TANQUE_INICIADOR, ArquetipoJungle.GANKER),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.ANTI_DIVE, TipoComposicao.CONTROLE_PESADO),
            c(TipoComposicao.ALTA_MOBILIDADE, TipoComposicao.ASSASSINO_MAGICO, TipoComposicao.DIVE),
            c(TipoComposicao.POKE, TipoComposicao.ANTI_TANQUE, TipoComposicao.LUTAS_LONGAS),
            7, 7, 6, 8, 7, 5, 6, 6, 9, 9, 3,
            "Silêncio e resistência oferecem uma resposta simples contra ameaças móveis."),
        p("Athena", a(ArquetipoJungle.LUTADOR_DUELISTA, ArquetipoJungle.INVASOR, ArquetipoJungle.GANKER),
            c(TipoComposicao.INVASAO, TipoComposicao.SNOWBALL, TipoComposicao.DIVE),
            c(TipoComposicao.PICKOFF, TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.ROTACAO),
            c(TipoComposicao.DESENGAGE, TipoComposicao.ANTI_TANQUE, TipoComposicao.CONTROLE_PESADO),
            8, 8, 9, 9, 7, 9, 8, 8, 6, 6, 6,
            "Escudos e pressão após a morte favorecem invasão e ritmo agressivo."),
        p("Augran", a(ArquetipoJungle.LUTADOR_DUELISTA, ArquetipoJungle.ANTI_TANQUE, ArquetipoJungle.OBJETIVOS),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.LUTAS_LONGAS, TipoComposicao.OBJETIVOS),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.ESCUDOS_E_CURA, TipoComposicao.ANTI_TANQUE),
            c(TipoComposicao.POKE, TipoComposicao.DESENGAGE, TipoComposicao.CONTROLE_PESADO),
            9, 8, 9, 10, 10, 8, 9, 10, 9, 9, 5,
            "Execução, sustentação e pressão de objetivo fazem dele a referência S15."),
        p("Chano", a(ArquetipoJungle.ATIRADOR_JUNGLE, ArquetipoJungle.FARMADOR, ArquetipoJungle.ESCALAMENTO),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.ESCALAMENTO, TipoComposicao.ARTILHARIA),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.LUTAS_LONGAS, TipoComposicao.OBJETIVOS),
            c(TipoComposicao.DIVE, TipoComposicao.PICKOFF, TipoComposicao.SNOWBALL),
            8, 6, 4, 5, 8, 5, 7, 9, 2, 6, 7,
            "Escala como segundo atirador e limpa lutas após o engage aliado."),
        p("Charlotte", a(ArquetipoJungle.LUTADOR_DUELISTA, ArquetipoJungle.GANKER, ArquetipoJungle.FARMADOR),
            c(TipoComposicao.DIVE, TipoComposicao.LUTAS_LONGAS, TipoComposicao.SPLIT_PUSH),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.FRONT_TO_BACK, TipoComposicao.LUTAS_LONGAS),
            c(TipoComposicao.CONTROLE_PESADO, TipoComposicao.POKE, TipoComposicao.EXPLOSAO),
            8, 7, 7, 9, 7, 8, 7, 9, 6, 7, 5,
            "Redução de dano e combos contínuos favorecem duelos e flancos."),
        p("Chicha", a(ArquetipoJungle.LUTADOR_DUELISTA, ArquetipoJungle.RESET, ArquetipoJungle.FARMADOR),
            c(TipoComposicao.LUTAS_LONGAS, TipoComposicao.FRONT_TO_BACK, TipoComposicao.ESCALAMENTO),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.OBJETIVOS, TipoComposicao.ALVOS_IMOVEIS),
            c(TipoComposicao.DESENGAGE, TipoComposicao.POKE, TipoComposicao.CONTROLE_PESADO),
            9, 6, 7, 9, 8, 8, 7, 10, 7, 7, 6,
            "Entra na segunda onda e converte cooldowns inimigos gastos em limpeza."),
        p("Cirrus", a(ArquetipoJungle.ASSASSINO_EXECUTOR, ArquetipoJungle.GANKER, ArquetipoJungle.GLOBAL),
            c(TipoComposicao.DIVE, TipoComposicao.ROTACAO, TipoComposicao.PICKOFF),
            c(TipoComposicao.ARTILHARIA, TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.SPLIT_PUSH),
            c(TipoComposicao.ANTI_DIVE, TipoComposicao.CONTROLE_PESADO, TipoComposicao.FRONT_TO_BACK),
            8, 8, 7, 7, 7, 10, 8, 8, 5, 6, 6,
            "Voo e acesso por terreno criam pressão de mapa e flancos incomuns."),
        p("Dharma", a(ArquetipoJungle.TANQUE_INICIADOR, ArquetipoJungle.GANKER, ArquetipoJungle.CONTROLADOR),
            c(TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.PICKOFF, TipoComposicao.OBJETIVOS),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.DIVE, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.POKE, TipoComposicao.DESENGAGE, TipoComposicao.ALTA_MOBILIDADE),
            7, 9, 7, 8, 8, 7, 9, 7, 8, 7, 7,
            "Paredes transformam ganks e corredores de objetivo em controle explosivo."),
        p("Dian Wei", a(ArquetipoJungle.LUTADOR_DUELISTA, ArquetipoJungle.ANTI_TANQUE, ArquetipoJungle.ESCALAMENTO),
            c(TipoComposicao.ANTI_TANQUE, TipoComposicao.LUTAS_LONGAS, TipoComposicao.SNOWBALL),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.ESCUDOS_E_CURA, TipoComposicao.OBJETIVOS),
            c(TipoComposicao.POKE, TipoComposicao.DESENGAGE, TipoComposicao.ALTA_MOBILIDADE),
            8, 6, 7, 10, 8, 7, 9, 10, 7, 7, 4,
            "Dano verdadeiro e escalamento punem composições resistentes que aceitam duelo."),
        p("Fang", a(ArquetipoJungle.ATIRADOR_JUNGLE, ArquetipoJungle.OBJETIVOS, ArquetipoJungle.GANKER),
            c(TipoComposicao.SNOWBALL, TipoComposicao.OBJETIVOS, TipoComposicao.PICKOFF),
            c(TipoComposicao.ESCALAMENTO, TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.DIVE, TipoComposicao.ANTI_DIVE, TipoComposicao.CONTROLE_PESADO),
            9, 8, 7, 7, 10, 8, 9, 8, 3, 7, 5,
            "Explosão de marca e limpeza rápida aceleram objetivos e snowball."),
        p("Feyd", a(ArquetipoJungle.ASSASSINO_EXECUTOR, ArquetipoJungle.GANKER, ArquetipoJungle.INVASOR),
            c(TipoComposicao.PICKOFF, TipoComposicao.DIVE, TipoComposicao.SNOWBALL),
            c(TipoComposicao.ARTILHARIA, TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.ROTACAO),
            c(TipoComposicao.CONTROLE_PESADO, TipoComposicao.ANTI_DIVE, TipoComposicao.FRONT_TO_BACK),
            8, 9, 8, 8, 7, 10, 10, 5, 2, 5, 7,
            "Usa terreno para emboscar e remover carregadores antes da luta."),
        p("Gao Changgong", a(ArquetipoJungle.ASSASSINO_EXECUTOR, ArquetipoJungle.GANKER, ArquetipoJungle.INVASOR),
            c(TipoComposicao.PICKOFF, TipoComposicao.SNOWBALL, TipoComposicao.INVASAO),
            c(TipoComposicao.ARTILHARIA, TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.ESCALAMENTO),
            c(TipoComposicao.ANTI_DIVE, TipoComposicao.CONTROLE_PESADO, TipoComposicao.FRONT_TO_BACK),
            8, 10, 8, 8, 7, 9, 10, 4, 2, 6, 5,
            "Furtividade e pico precoce punem rotas frágeis e sem visão."),
        p("Han Xin", a(ArquetipoJungle.INVASOR, ArquetipoJungle.FARMADOR, ArquetipoJungle.GLOBAL),
            c(TipoComposicao.INVASAO, TipoComposicao.SPLIT_PUSH, TipoComposicao.ROTACAO),
            c(TipoComposicao.ESCALAMENTO, TipoComposicao.OBJETIVOS, TipoComposicao.ALVOS_IMOVEIS),
            c(TipoComposicao.CONTROLE_PESADO, TipoComposicao.FRONT_TO_BACK, TipoComposicao.PICKOFF),
            10, 8, 10, 8, 9, 10, 7, 8, 3, 6, 7,
            "Mobilidade extrema transforma vantagem de farm em invasão e pressão lateral."),
        p("Jing", a(ArquetipoJungle.ASSASSINO_EXECUTOR, ArquetipoJungle.LUTADOR_DUELISTA, ArquetipoJungle.GANKER),
            c(TipoComposicao.DIVE, TipoComposicao.PICKOFF, TipoComposicao.SNOWBALL),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.HIPERCARREGADOR, TipoComposicao.ARTILHARIA),
            c(TipoComposicao.CONTROLE_PESADO, TipoComposicao.ANTI_DIVE, TipoComposicao.EXPLOSAO),
            9, 9, 8, 10, 8, 10, 10, 8, 3, 5, 7,
            "Espelhos e mobilidade recompensam execução mecânica e isolamento de alvo."),
        p("Kaizer", a(ArquetipoJungle.LUTADOR_DUELISTA, ArquetipoJungle.TANQUE_INICIADOR, ArquetipoJungle.ANTI_TANQUE),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.DIVE, TipoComposicao.LUTAS_LONGAS),
            c(TipoComposicao.HIPERCARREGADOR, TipoComposicao.FRONT_TO_BACK, TipoComposicao.ESCUDOS_E_CURA),
            c(TipoComposicao.POKE, TipoComposicao.DESENGAGE, TipoComposicao.ALTA_MOBILIDADE),
            8, 7, 8, 10, 8, 7, 9, 9, 9, 9, 4,
            "Transformação permite absorver dano e eliminar o carregador principal."),
        p("Kongming", a(ArquetipoJungle.MAGICO, ArquetipoJungle.ASSASSINO_EXECUTOR, ArquetipoJungle.RESET),
            c(TipoComposicao.ASSASSINO_MAGICO, TipoComposicao.PICKOFF, TipoComposicao.SNOWBALL),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.HIPERCARREGADOR, TipoComposicao.ARTILHARIA),
            c(TipoComposicao.CONTROLE_PESADO, TipoComposicao.FRONT_TO_BACK, TipoComposicao.ESCUDOS_E_CURA),
            9, 9, 7, 8, 8, 9, 10, 7, 2, 6, 6,
            "Dano mágico, execução e resets cobrem composições excessivamente físicas."),
        p("Lam", a(ArquetipoJungle.ASSASSINO_EXECUTOR, ArquetipoJungle.GANKER, ArquetipoJungle.GLOBAL),
            c(TipoComposicao.DIVE, TipoComposicao.PICKOFF, TipoComposicao.ROTACAO),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.ARTILHARIA, TipoComposicao.HIPERCARREGADOR),
            c(TipoComposicao.CONTROLE_PESADO, TipoComposicao.ANTI_DIVE, TipoComposicao.FRONT_TO_BACK),
            9, 9, 8, 8, 8, 10, 10, 7, 3, 6, 6,
            "Movimento no rio e execução criam pressão constante sobre alvos frágeis."),
        p("Li Bai", a(ArquetipoJungle.ASSASSINO_EXECUTOR, ArquetipoJungle.GANKER, ArquetipoJungle.FARMADOR),
            c(TipoComposicao.POKE, TipoComposicao.DIVE, TipoComposicao.PICKOFF),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.ARTILHARIA, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.CONTROLE_PESADO, TipoComposicao.ANTI_DIVE, TipoComposicao.INVASAO),
            9, 8, 7, 8, 7, 10, 9, 7, 2, 6, 8,
            "Entradas curtas e invulnerabilidade permitem desgastar sem compromisso prolongado."),
        p("Liu Bei", a(ArquetipoJungle.LUTADOR_DUELISTA, ArquetipoJungle.INVASOR, ArquetipoJungle.OBJETIVOS),
            c(TipoComposicao.INVASAO, TipoComposicao.OBJETIVOS, TipoComposicao.SNOWBALL),
            c(TipoComposicao.ASSASSINO_MAGICO, TipoComposicao.CONTROLE_PESADO, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.POKE, TipoComposicao.DESENGAGE, TipoComposicao.ALTA_MOBILIDADE),
            9, 7, 10, 10, 10, 7, 8, 10, 7, 8, 4,
            "Dano próximo, escudo e limpeza rápida dominam duelos e invasões precoces."),
        p("Luna", a(ArquetipoJungle.MAGICO, ArquetipoJungle.ASSASSINO_EXECUTOR, ArquetipoJungle.RESET),
            c(TipoComposicao.ASSASSINO_MAGICO, TipoComposicao.DIVE, TipoComposicao.LUTAS_LONGAS),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.HIPERCARREGADOR),
            c(TipoComposicao.CONTROLE_PESADO, TipoComposicao.EXPLOSAO, TipoComposicao.INVASAO),
            9, 8, 7, 10, 8, 10, 9, 10, 3, 5, 9,
            "Resets infinitos transformam marcação correta em mobilidade e DPS mágico."),
        p("Mayene", a(ArquetipoJungle.LUTADOR_DUELISTA, ArquetipoJungle.GANKER, ArquetipoJungle.CONTROLADOR),
            c(TipoComposicao.DIVE, TipoComposicao.CONTROLE_PESADO, TipoComposicao.PICKOFF),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.FRONT_TO_BACK, TipoComposicao.HIPERCARREGADOR),
            c(TipoComposicao.POKE, TipoComposicao.EXPLOSAO, TipoComposicao.CONTROLE_PESADO),
            8, 9, 8, 9, 7, 9, 8, 8, 6, 6, 9,
            "Muitos combos oferecem controle, deslocamento e adaptação ao alvo."),
        p("Menki", a(ArquetipoJungle.LUTADOR_DUELISTA, ArquetipoJungle.TANQUE_INICIADOR, ArquetipoJungle.OBJETIVOS),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.LUTAS_LONGAS, TipoComposicao.OBJETIVOS),
            c(TipoComposicao.EXPLOSAO, TipoComposicao.FRONT_TO_BACK, TipoComposicao.ALVOS_IMOVEIS),
            c(TipoComposicao.ANTI_TANQUE, TipoComposicao.POKE, TipoComposicao.DESENGAGE),
            8, 7, 7, 9, 9, 5, 7, 9, 9, 8, 5,
            "Escudos e dano misto completam equipes sem linha de frente ou dano sustentado."),
        p("Mi Yue", a(ArquetipoJungle.MAGICO, ArquetipoJungle.LUTADOR_DUELISTA, ArquetipoJungle.ESCALAMENTO),
            c(TipoComposicao.SPLIT_PUSH, TipoComposicao.LUTAS_LONGAS, TipoComposicao.ASSASSINO_MAGICO),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.ANTI_TANQUE, TipoComposicao.LUTAS_LONGAS),
            c(TipoComposicao.PICKOFF, TipoComposicao.CONTROLE_PESADO, TipoComposicao.EXPLOSAO),
            8, 6, 8, 10, 8, 8, 6, 10, 6, 8, 5,
            "Sustentação e dano mágico vencem duelos e pressionam rotas laterais."),
        p("Musashi", a(ArquetipoJungle.LUTADOR_DUELISTA, ArquetipoJungle.GANKER, ArquetipoJungle.ANTI_TANQUE),
            c(TipoComposicao.DIVE, TipoComposicao.ANTI_DIVE, TipoComposicao.PICKOFF),
            c(TipoComposicao.ESCUDOS_E_CURA, TipoComposicao.ARTILHARIA, TipoComposicao.HIPERCARREGADOR),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.CONTROLE_PESADO, TipoComposicao.LUTAS_LONGAS),
            8, 8, 8, 9, 8, 7, 9, 8, 8, 8, 5,
            "Anti-cura e bloqueio de projéteis punem carries protegidos e artilharia."),
        p("Nakoruru", a(ArquetipoJungle.ASSASSINO_EXECUTOR, ArquetipoJungle.GANKER, ArquetipoJungle.ANTI_TANQUE),
            c(TipoComposicao.EXPLOSAO, TipoComposicao.DIVE, TipoComposicao.PICKOFF),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.HIPERCARREGADOR),
            c(TipoComposicao.ANTI_DIVE, TipoComposicao.CONTROLE_PESADO, TipoComposicao.ESCUDOS_E_CURA),
            8, 9, 7, 8, 7, 9, 10, 6, 2, 6, 4,
            "Explosão percentual oferece acesso simples a carries e alvos resistentes."),
        p("Pei", a(ArquetipoJungle.INVASOR, ArquetipoJungle.GANKER, ArquetipoJungle.OBJETIVOS),
            c(TipoComposicao.INVASAO, TipoComposicao.SNOWBALL, TipoComposicao.OBJETIVOS),
            c(TipoComposicao.ESCALAMENTO, TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.ARTILHARIA),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.CONTROLE_PESADO, TipoComposicao.LUTAS_LONGAS),
            10, 9, 10, 9, 10, 9, 8, 9, 5, 7, 9,
            "Duas formas e pico precoce exigem coordenação para converter invasão em vantagem."),
        p("Sima Yi", a(ArquetipoJungle.MAGICO, ArquetipoJungle.ASSASSINO_EXECUTOR, ArquetipoJungle.GLOBAL),
            c(TipoComposicao.ASSASSINO_MAGICO, TipoComposicao.ROTACAO, TipoComposicao.PICKOFF),
            c(TipoComposicao.POKE, TipoComposicao.ARTILHARIA, TipoComposicao.ALVOS_IMOVEIS),
            c(TipoComposicao.CONTROLE_PESADO, TipoComposicao.FRONT_TO_BACK, TipoComposicao.ANTI_DIVE),
            9, 9, 8, 8, 8, 10, 10, 6, 2, 6, 6,
            "Silêncio e alcance global punem magos imóveis e composições de poke."),
        p("Sun Ce", a(ArquetipoJungle.TANQUE_INICIADOR, ArquetipoJungle.GLOBAL, ArquetipoJungle.CONTROLADOR),
            c(TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.ROTACAO, TipoComposicao.DIVE),
            c(TipoComposicao.ARTILHARIA, TipoComposicao.POKE, TipoComposicao.SPLIT_PUSH),
            c(TipoComposicao.DESENGAGE, TipoComposicao.CONTROLE_PESADO, TipoComposicao.ANTI_TANQUE),
            8, 10, 7, 8, 8, 9, 8, 7, 9, 8, 6,
            "Navio global entrega iniciação, rotação e linha de frente em uma escolha."),
        p("Ukyo Tachibana", a(ArquetipoJungle.ASSASSINO_EXECUTOR, ArquetipoJungle.GANKER, ArquetipoJungle.LUTADOR_DUELISTA),
            c(TipoComposicao.PICKOFF, TipoComposicao.POKE, TipoComposicao.SNOWBALL),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.ARTILHARIA, TipoComposicao.ESCALAMENTO),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.CONTROLE_PESADO, TipoComposicao.LUTAS_LONGAS),
            8, 9, 8, 8, 7, 7, 9, 6, 4, 6, 7,
            "Poke curto e controle dão ganks fortes antes do escalamento inimigo."),
        p("Umbrosa", a(ArquetipoJungle.LUTADOR_DUELISTA, ArquetipoJungle.FARMADOR, ArquetipoJungle.TANQUE_INICIADOR),
            c(TipoComposicao.LUTAS_LONGAS, TipoComposicao.FRONT_TO_BACK, TipoComposicao.ESCALAMENTO),
            c(TipoComposicao.EXPLOSAO, TipoComposicao.FRONT_TO_BACK, TipoComposicao.OBJETIVOS),
            c(TipoComposicao.ANTI_TANQUE, TipoComposicao.ESCUDOS_E_CURA, TipoComposicao.POKE),
            8, 7, 7, 9, 8, 7, 7, 10, 9, 8, 4,
            "Cura e ressurreição prolongam lutas e absorvem a primeira rotação inimiga."),
        p("Wukong", a(ArquetipoJungle.ASSASSINO_EXECUTOR, ArquetipoJungle.GANKER, ArquetipoJungle.ESCALAMENTO),
            c(TipoComposicao.EXPLOSAO, TipoComposicao.DIVE, TipoComposicao.SNOWBALL),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.ARTILHARIA, TipoComposicao.HIPERCARREGADOR),
            c(TipoComposicao.CONTROLE_PESADO, TipoComposicao.ANTI_DIVE, TipoComposicao.FRONT_TO_BACK),
            8, 9, 7, 9, 7, 9, 10, 6, 3, 6, 4,
            "Críticos e acesso simples à backline tornam o pick consistente no meta."),
        p("Wuyan", a(ArquetipoJungle.TANQUE_INICIADOR, ArquetipoJungle.CONTROLADOR, ArquetipoJungle.GANKER),
            c(TipoComposicao.ENGAGE_AGRUPADO, TipoComposicao.CONTROLE_PESADO, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.DIVE, TipoComposicao.ALTA_MOBILIDADE, TipoComposicao.ALVOS_IMOVEIS),
            c(TipoComposicao.POKE, TipoComposicao.DESENGAGE, TipoComposicao.ANTI_TANQUE),
            7, 8, 7, 8, 8, 6, 8, 7, 9, 8, 5,
            "Petrificação oferece iniciação e peel, mas depende de alcançar o alvo."),
        p("Yang Jian", a(ArquetipoJungle.LUTADOR_DUELISTA, ArquetipoJungle.ASSASSINO_EXECUTOR, ArquetipoJungle.ANTI_TANQUE),
            c(TipoComposicao.DIVE, TipoComposicao.LUTAS_LONGAS, TipoComposicao.PICKOFF),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.ESCUDOS_E_CURA),
            c(TipoComposicao.POKE, TipoComposicao.CONTROLE_PESADO, TipoComposicao.DESENGAGE),
            8, 8, 8, 9, 8, 8, 9, 8, 6, 7, 6,
            "Marca, execução e dano verdadeiro recompensam perseguição de alvos isolados."),
        p("Yao", a(ArquetipoJungle.LUTADOR_DUELISTA, ArquetipoJungle.GANKER, ArquetipoJungle.FARMADOR),
            c(TipoComposicao.DIVE, TipoComposicao.SPLIT_PUSH, TipoComposicao.ROTACAO),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.PICKOFF, TipoComposicao.EXPLOSAO),
            c(TipoComposicao.CONTROLE_PESADO, TipoComposicao.POKE, TipoComposicao.FRONT_TO_BACK),
            9, 8, 8, 9, 8, 9, 8, 8, 6, 7, 8,
            "Combos e retorno de dano permitem entrar, absorver burst e reposicionar."),
        p("Ying", a(ArquetipoJungle.LUTADOR_DUELISTA, ArquetipoJungle.CONTROLADOR, ArquetipoJungle.OBJETIVOS),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.CONTROLE_PESADO, TipoComposicao.LUTAS_LONGAS),
            c(TipoComposicao.DIVE, TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.FRONT_TO_BACK),
            c(TipoComposicao.POKE, TipoComposicao.EXPLOSAO, TipoComposicao.DESENGAGE),
            9, 8, 8, 9, 9, 8, 8, 9, 8, 8, 7,
            "Variações de lança oferecem controle, sustain e execução conforme a luta."),
        p("Zilong", a(ArquetipoJungle.GANKER, ArquetipoJungle.LUTADOR_DUELISTA, ArquetipoJungle.ASSASSINO_EXECUTOR),
            c(TipoComposicao.DIVE, TipoComposicao.PICKOFF, TipoComposicao.SNOWBALL),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.HIPERCARREGADOR, TipoComposicao.ARTILHARIA),
            c(TipoComposicao.FRONT_TO_BACK, TipoComposicao.CONTROLE_PESADO, TipoComposicao.ANTI_DIVE),
            7, 9, 7, 8, 7, 8, 9, 7, 7, 7, 4,
            "Entrada direta e controle simples punem carries sem proteção adequada."),
        p("Xuance", a(ArquetipoJungle.ASSASSINO_EXECUTOR, ArquetipoJungle.CONTROLADOR, ArquetipoJungle.RESET),
            c(TipoComposicao.PICKOFF, TipoComposicao.SNOWBALL, TipoComposicao.DIVE),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.ARTILHARIA, TipoComposicao.HIPERCARREGADOR),
            c(TipoComposicao.CONTROLE_PESADO, TipoComposicao.ANTI_DIVE, TipoComposicao.FRONT_TO_BACK),
            8, 9, 8, 8, 7, 10, 9, 7, 3, 5, 8,
            "Gancho e limpeza após abate criam pickoffs e resets, mas exigem precisão."),
        p("Yango", a(ArquetipoJungle.ASSASSINO_EXECUTOR, ArquetipoJungle.GANKER, ArquetipoJungle.CONTROLADOR),
            c(TipoComposicao.PICKOFF, TipoComposicao.SNOWBALL, TipoComposicao.DIVE),
            c(TipoComposicao.ALVOS_IMOVEIS, TipoComposicao.ARTILHARIA, TipoComposicao.HIPERCARREGADOR),
            c(TipoComposicao.CONTROLE_PESADO, TipoComposicao.ANTI_DIVE, TipoComposicao.FRONT_TO_BACK),
            8, 9, 8, 9, 7, 10, 10, 6, 2, 5, 10,
            "Marionete e múltiplas sequências oferecem enorme teto mecânico para pickoff.")
    );

    public List<PerfilJungle> listarTodos() {
        return perfis;
    }

    private PerfilJungle p(
        String heroi,
        List<ArquetipoJungle> arquetipos,
        List<TipoComposicao> fortalece,
        List<TipoComposicao> quebra,
        List<TipoComposicao> sofreContra,
        int limpeza,
        int gank,
        int invasao,
        int duelo,
        int objetivos,
        int mobilidade,
        int explosao,
        int danoSustentado,
        int linhaDeFrente,
        int seguranca,
        int dependenciaCoordenacao,
        String observacao
    ) {
        return new PerfilJungle(
            heroi, arquetipos, fortalece, quebra, sofreContra,
            limpeza, gank, invasao, duelo, objetivos, mobilidade,
            explosao, danoSustentado, linhaDeFrente, seguranca,
            dependenciaCoordenacao, List.of(observacao)
        );
    }

    @SafeVarargs
    private final <T> List<T> a(T... valores) {
        return List.of(valores);
    }

    @SafeVarargs
    private final <T> List<T> c(T... valores) {
        return List.of(valores);
    }
}
