package br.com.carlosdaniel.hokdraftcoach.repository;

import java.util.List;

import org.springframework.stereotype.Repository;

import br.com.carlosdaniel.hokdraftcoach.model.ConfiancaDado;
import br.com.carlosdaniel.hokdraftcoach.model.SinergiaMidEquipe;

@Repository
public class SinergiaMidRepository {

    private final List<SinergiaMidEquipe> sinergias = List.of(
        s("Angela", "Kui", 10, ConfiancaDado.ALTA,
            "O gancho deixa o alvo imóvel para o combo completo de Angela.",
            "gancho", "alvo imóvel", "explosão"),
        s("Angela", "Guiguzi", 9, ConfiancaDado.MEDIA,
            "Agrupamento e camuflagem entregam múltiplos alvos para o dano linear.",
            "agrupamento", "iniciação", "dano em área"),
        s("Angela", "Lian Po", 9, ConfiancaDado.MEDIA,
            "Controle em cadeia mantém inimigos dentro da ultimate.",
            "controle em área", "linha de frente", "canal seguro"),
        s("Angela", "Dolia", 8, ConfiancaDado.MEDIA,
            "Sustentação e reutilização de ultimate criam duas janelas de burst.",
            "reset de ultimate", "sustentação", "explosão"),

        s("Daji", "Dolia", 9, ConfiancaDado.MEDIA,
            "Uma segunda rotação de ultimate permite eliminar dois alvos isolados.",
            "reset de ultimate", "pickoff", "explosão"),
        s("Daji", "Guiguzi", 9, ConfiancaDado.ALTA,
            "Camuflagem aproxima Daji e o agrupamento melhora sua explosão.",
            "camuflagem", "agrupamento", "pickoff"),
        s("Daji", "Sun Bin", 8, ConfiancaDado.MEDIA,
            "Velocidade facilita rotações rápidas e retirada após o pickoff.",
            "velocidade", "rotação", "desengage"),
        s("Daji", "Donghuang", 8, ConfiancaDado.MEDIA,
            "Supressão garante tempo para descarregar todo o combo.",
            "supressão", "alvo único", "explosão"),

        s("Liang", "Dyadia", 9, ConfiancaDado.ALTA,
            "Cura e pressão mantêm Liang ativo enquanto ele controla a ameaça principal.",
            "sustentação", "controle", "pressão"),
        s("Liang", "Ming", 8, ConfiancaDado.MEDIA,
            "Amplificação aumenta o dano durante a janela de supressão.",
            "supressão", "amplificação", "pickoff"),
        s("Liang", "Yaria", 8, ConfiancaDado.MEDIA,
            "Escudo e proteção permitem aproximar-se para usar a ultimate com segurança.",
            "escudo", "proteção", "supressão"),
        s("Liang", "Lam", 9, ConfiancaDado.MEDIA,
            "A supressão entrega um alvo parado para a execução do assassino.",
            "controle garantido", "execução", "pickoff"),

        s("Milady", "Sun Bin", 9, ConfiancaDado.ALTA,
            "Velocidade de rotação transforma pressão de onda em pressão de torre.",
            "velocidade", "wave clear", "torres"),
        s("Milady", "Yaria", 8, ConfiancaDado.ALTA,
            "Escudo reduz o risco de dive enquanto as invocações pressionam.",
            "escudo", "anti-assassino", "pressão de torre"),
        s("Milady", "Zhang Fei", 8, ConfiancaDado.ALTA,
            "Linha de frente protege a maga e permite cerco prolongado.",
            "linha de frente", "escudo", "cerco"),
        s("Milady", "Liu Shan", 9, ConfiancaDado.MEDIA,
            "A dupla converte qualquer espaço em dano acelerado às torres.",
            "pressão de torre", "controle", "snowball"),

        s("Haya", "Sakeer", 8, ConfiancaDado.ALTA,
            "Visão e sustentação ampliam as rotações e o desgaste móvel.",
            "visão", "cura", "mobilidade"),
        s("Haya", "Lian Po", 8, ConfiancaDado.MEDIA,
            "Linha de frente e controle criam espaço para poke constante.",
            "linha de frente", "controle", "poke"),
        s("Haya", "Zhang Fei", 8, ConfiancaDado.MEDIA,
            "Peel permite manter distância e continuar causando dano.",
            "peel", "escudo", "dano consistente"),

        s("Mozi", "Dyadia", 8, ConfiancaDado.ALTA,
            "Cura e mobilidade mantêm a pressão de poke e controle.",
            "cura", "poke", "controle"),
        s("Mozi", "Zhuangzi", 8, ConfiancaDado.ALTA,
            "Purificação protege Mozi enquanto ele canaliza controle em área.",
            "anti-controle", "canal", "proteção"),
        s("Mozi", "Ming", 8, ConfiancaDado.ALTA,
            "Amplificação aumenta o impacto dos disparos de longa distância.",
            "amplificação", "artilharia", "escudo"),
        s("Mozi", "Shouyue", 10, ConfiancaDado.ALTA,
            "Controle à distância prepara tiros de precisão e cria uma composição de artilharia.",
            "artilharia", "controle à distância", "poke"),

        s("Xiao Qiao", "Donghuang", 9, ConfiancaDado.ALTA,
            "Supressão fixa o alvo para a explosão e a ultimate em área.",
            "supressão", "explosão", "alvo imóvel"),
        s("Xiao Qiao", "Dyadia", 8, ConfiancaDado.ALTA,
            "Cura e pressão permitem continuar o poke até encontrar o combo.",
            "cura", "poke", "pressão"),
        s("Xiao Qiao", "Cai Yan", 8, ConfiancaDado.ALTA,
            "Sustentação compensa a baixa mobilidade da maga em lutas prolongadas.",
            "cura", "proteção", "dano em área"),
        s("Xiao Qiao", "Lian Po", 9, ConfiancaDado.MEDIA,
            "Controle em área agrupa e mantém inimigos dentro da ultimate.",
            "iniciação", "controle em área", "explosão"),

        s("Nuwa", "Da Qiao", 9, ConfiancaDado.ALTA,
            "Terreno, portais e alcance global criam enorme controle de mapa.",
            "macro", "terreno", "alcance global"),
        s("Nuwa", "Zhuangzi", 8, ConfiancaDado.ALTA,
            "Proteção contra controle permite manter distância e controlar corredores.",
            "anti-controle", "zoneamento", "proteção"),
        s("Nuwa", "Dyadia", 8, ConfiancaDado.ALTA,
            "Sustentação e mobilidade ajudam Nuwa a manter o cerco.",
            "cura", "cerco", "poke"),

        s("Yixing", "Cai Yan", 8, ConfiancaDado.ALTA,
            "Cura mantém a equipe agrupada dentro da zona de controle do tabuleiro.",
            "cura", "controle de área", "luta longa"),
        s("Yixing", "Yaria", 8, ConfiancaDado.ALTA,
            "Escudo protege o controlador enquanto ele prepara a luta.",
            "escudo", "zoneamento", "proteção"),
        s("Yixing", "Dolia", 9, ConfiancaDado.ALTA,
            "Reset de ultimate oferece duas zonas decisivas de confinamento.",
            "reset de ultimate", "zoneamento", "objetivos"),
        s("Yixing", "Lian Po", 10, ConfiancaDado.ALTA,
            "Lian Po inicia e mantém a equipe inimiga dentro do tabuleiro.",
            "iniciação", "confinamento", "controle em cadeia"),

        s("Ziya", "Da Qiao", 9, ConfiancaDado.ALTA,
            "Macro e alcance permitem pressionar várias zonas sem exposição direta.",
            "macro", "artilharia", "wave clear"),
        s("Ziya", "Yaria", 8, ConfiancaDado.ALTA,
            "Escudo reduz a vulnerabilidade do artilheiro a assassinos.",
            "escudo", "anti-assassino", "poke"),
        s("Ziya", "Donghuang", 8, ConfiancaDado.ALTA,
            "Supressão mantém o alvo parado para a ultimate carregada.",
            "supressão", "artilharia", "explosão"),
        s("Ziya", "Marco Polo", 8, ConfiancaDado.MEDIA,
            "Desaceleração e zoneamento facilitam a entrada do ADC em área.",
            "desaceleração", "zoneamento", "ultimate em área"),

        s("Dr Bian Qe", "Liu Shan", 8, ConfiancaDado.ALTA,
            "Linha de frente e controle prolongam o tempo dos acúmulos de veneno.",
            "linha de frente", "controle", "luta longa"),
        s("Dr Bian Qe", "Dolia", 9, ConfiancaDado.ALTA,
            "Duas fontes de sustentação tornam a composição difícil de desgastar.",
            "cura", "luta longa", "sustentação"),
        s("Dr Bian Qe", "Zhuangzi", 8, ConfiancaDado.ALTA,
            "Purificação impede que controles interrompam a luta prolongada.",
            "anti-controle", "cura", "dano persistente"),
        s("Dr Bian Qe", "Zhang Fei", 8, ConfiancaDado.MEDIA,
            "Escudos e linha de frente dão tempo para veneno e cura acumularem.",
            "escudo", "linha de frente", "dano persistente"),

        s("Gan & Mo", "Cai Yan", 8, ConfiancaDado.ALTA,
            "Cura permite permanecer em posição e continuar disparando de longe.",
            "cura", "artilharia", "proteção"),
        s("Gan & Mo", "Guiguzi", 9, ConfiancaDado.ALTA,
            "Agrupamento transforma disparos de precisão em dano massivo em área.",
            "agrupamento", "artilharia", "explosão"),
        s("Gan & Mo", "Dolia", 9, ConfiancaDado.ALTA,
            "Reset de ultimate cria duas janelas de artilharia explosiva.",
            "reset de ultimate", "explosão", "artilharia"),
        s("Gan & Mo", "Kui", 10, ConfiancaDado.MEDIA,
            "O gancho oferece um alvo previsível para os projéteis cruzados.",
            "gancho", "alvo imóvel", "precisão"),

        s("Gao Jianli", "Kui", 10, ConfiancaDado.ALTA,
            "O gancho aproxima o alvo e inicia a luta no alcance ideal da ultimate.",
            "gancho", "dano em área", "iniciação"),
        s("Gao Jianli", "Sun Bin", 9, ConfiancaDado.ALTA,
            "Aceleração permite entrar, causar dano e sair antes da resposta.",
            "velocidade", "dive", "desengage"),
        s("Gao Jianli", "Liu Bang", 8, ConfiancaDado.ALTA,
            "Proteção global acompanha o mergulho e absorve a contraexplosão.",
            "proteção global", "dive", "escudo"),
        s("Gao Jianli", "Lian Po", 9, ConfiancaDado.MEDIA,
            "Controle em área mantém os inimigos agrupados durante a ultimate.",
            "iniciação", "agrupamento", "dano em área"),

        s("Shangguan", "Ming", 8, ConfiancaDado.ALTA,
            "Amplificação aumenta o dano da sequência e a chance de execução.",
            "amplificação", "explosão", "execução"),
        s("Shangguan", "Cai Yan", 8, ConfiancaDado.ALTA,
            "Cura protege a assassina após a entrada e durante a saída.",
            "cura", "dive", "sobrevivência"),
        s("Shangguan", "Guiguzi", 9, ConfiancaDado.ALTA,
            "Camuflagem e agrupamento criam uma entrada difícil de antecipar.",
            "camuflagem", "agrupamento", "dive"),
        s("Shangguan", "Donghuang", 8, ConfiancaDado.MEDIA,
            "Supressão impede respostas enquanto a sequência é preparada.",
            "supressão", "explosão", "alvo imóvel"),

        s("Shi", "Liu Shan", 8, ConfiancaDado.ALTA,
            "Reposicionamento e controle em cadeia isolam um alvo para execução.",
            "reposicionamento", "controle em cadeia", "pickoff"),
        s("Shi", "Zhang Fei", 8, ConfiancaDado.ALTA,
            "Linha de frente protege Shi enquanto ela busca o controle decisivo.",
            "proteção", "controle", "pickoff"),
        s("Shi", "Zhuangzi", 8, ConfiancaDado.ALTA,
            "Purificação mantém a controladora segura para reposicionar inimigos.",
            "anti-controle", "proteção", "setup"),
        s("Shi", "Kui", 9, ConfiancaDado.MEDIA,
            "Gancho e reposicionamento criam múltiplas formas de retirar um alvo da formação.",
            "gancho", "reposicionamento", "pickoff"),

        s("Yuhuan", "Dolia", 9, ConfiancaDado.ALTA,
            "Sustentação duplicada e ultimates defensivas estendem muito as lutas.",
            "cura", "luta longa", "reset de ultimate"),
        s("Yuhuan", "Ming", 8, ConfiancaDado.ALTA,
            "Amplificação reforça dano e cura durante as rotações móveis.",
            "amplificação", "cura", "mobilidade"),
        s("Yuhuan", "Liu Bang", 8, ConfiancaDado.ALTA,
            "Proteção global acompanha entradas e permite jogar agressivamente.",
            "proteção global", "mobilidade", "sustentação"),

        s("Zhou Yu", "Dyadia", 8, ConfiancaDado.ALTA,
            "Cura e mobilidade permitem permanecer próximo das zonas de fogo.",
            "cura", "zoneamento", "pressão"),
        s("Zhou Yu", "Kui", 9, ConfiancaDado.ALTA,
            "O gancho arrasta o alvo para o território em chamas.",
            "gancho", "zoneamento", "dano persistente"),
        s("Zhou Yu", "Liu Bang", 8, ConfiancaDado.ALTA,
            "Proteção global sustenta a pressão avançada sobre objetivos e torres.",
            "proteção global", "objetivos", "pressão de torre"),
        s("Zhou Yu", "Da Qiao", 9, ConfiancaDado.MEDIA,
            "Macro, wave control e território persistente sufocam o mapa inimigo.",
            "macro", "wave clear", "zoneamento"),

        s("Lady Zhen", "Dyadia", 8, ConfiancaDado.ALTA,
            "Sustentação ajuda a controladora a manter zonas defensivas por mais tempo.",
            "cura", "controle em área", "luta longa"),
        s("Lady Zhen", "Liu Shan", 9, ConfiancaDado.ALTA,
            "Controle frontal inicia a cadeia de congelamento.",
            "iniciação", "controle em cadeia", "congelamento"),
        s("Lady Zhen", "Zhang Fei", 9, ConfiancaDado.ALTA,
            "Peel força inimigos a permanecer na zona de controle da maga.",
            "peel", "congelamento", "anti-dive"),
        s("Lady Zhen", "Lian Po", 9, ConfiancaDado.MEDIA,
            "Iniciação em área agrupa inimigos para congelamento e ultimate.",
            "agrupamento", "controle em área", "dano em área"),

        s("Da Qiao", "Di Renjie", 9, ConfiancaDado.ALTA,
            "Limpeza, controle e teleporte criam pressão segura em várias rotas.",
            "macro", "wave clear", "reposicionamento"),
        s("Da Qiao", "Arli", 9, ConfiancaDado.ALTA,
            "Mobilidade extrema e retorno à base criam pressão lateral difícil de punir.",
            "macro", "mobilidade", "split push"),
        s("Da Qiao", "Shouyue", 8, ConfiancaDado.ALTA,
            "Portais e zoneamento ampliam a segurança do sniper.",
            "macro", "artilharia", "visão"),
        s("Da Qiao", "Marco Polo", 9, ConfiancaDado.MEDIA,
            "Reposicionamento e macro ampliam a mobilidade e a pressão lateral.",
            "macro", "mobilidade", "desengage"),

        s("Lorion", "Lian Po", 10, ConfiancaDado.MEDIA,
            "Controle em área mantém inimigos próximos do orbe e da explosão.",
            "iniciação", "controle em área", "explosão"),
        s("Lorion", "Guiguzi", 9, ConfiancaDado.MEDIA,
            "Agrupamento oferece o cenário ideal para controle e burst do orbe.",
            "agrupamento", "camuflagem", "dano em área"),
        s("Lorion", "Dolia", 9, ConfiancaDado.MEDIA,
            "Reset de ultimate permite repetir uma grande janela de controle em objetivo.",
            "reset de ultimate", "controle", "objetivos"),
        s("Lorion", "Marco Polo", 8, ConfiancaDado.EXPLORATORIA,
            "Controle em área prepara a entrada da ultimate do ADC.",
            "controle", "ultimate em área", "engage"),

        s("Garuda", "Dolia", 9, ConfiancaDado.ALTA,
            "Sustentação e reset permitem repetir pressão de poke e velocidade.",
            "cura", "reset de ultimate", "poke"),
        s("Garuda", "Lian Po", 8, ConfiancaDado.MEDIA,
            "Linha de frente cria espaço para desgaste e aceleração da equipe.",
            "linha de frente", "poke", "velocidade"),
        s("Garuda", "Zhang Fei", 8, ConfiancaDado.MEDIA,
            "Escudos e peel mantêm a maga em alcance seguro.",
            "escudo", "peel", "artilharia"),

        s("Ser do Fluxo (Mago)", "Zhang Fei", 8, ConfiancaDado.EXPLORATORIA,
            "Linha de frente permite usar a configuração adaptativa sem exposição excessiva.",
            "linha de frente", "adaptação", "controle"),
        s("Ser do Fluxo (Mago)", "Dyadia", 8, ConfiancaDado.EXPLORATORIA,
            "Cura e pressão complementam qualquer configuração utilitária do mago.",
            "cura", "adaptação", "pressão"),

        s("Heino", "Cai Yan", 8, ConfiancaDado.MEDIA,
            "Cura adicional reforça sustain e transforma a equipe em composição de desgaste.",
            "cura", "poke", "luta longa"),
        s("Heino", "Zhang Fei", 8, ConfiancaDado.MEDIA,
            "Linha de frente segura permite jogar no limite do alcance.",
            "linha de frente", "peel", "poke"),
        s("Heino", "Dolia", 8, ConfiancaDado.MEDIA,
            "Sustentação e utilidade prolongam o valor temporal do kit.",
            "sustentação", "controle", "luta longa"),

        s("Kongming", "Guiguzi", 9, ConfiancaDado.ALTA,
            "Agrupamento reduz inimigos à faixa de execução e inicia a cadeia de resets.",
            "agrupamento", "execução", "reset"),
        s("Kongming", "Donghuang", 8, ConfiancaDado.ALTA,
            "Supressão garante o primeiro alvo e abre os resets.",
            "supressão", "execução", "pickoff"),
        s("Kongming", "Dolia", 8, ConfiancaDado.MEDIA,
            "Reset de ultimate aumenta a capacidade de executar e continuar a luta.",
            "reset de ultimate", "execução", "mobilidade"),

        s("Mai Shiranui", "Guiguzi", 9, ConfiancaDado.ALTA,
            "Camuflagem e agrupamento criam ângulo perfeito para controle e burst.",
            "camuflagem", "agrupamento", "explosão"),
        s("Mai Shiranui", "Donghuang", 9, ConfiancaDado.ALTA,
            "Supressão elimina o risco durante a sequência de aproximação.",
            "supressão", "explosão", "controle"),
        s("Mai Shiranui", "Lian Po", 8, ConfiancaDado.MEDIA,
            "Linha de frente e controle permitem escolher ângulos laterais com segurança.",
            "linha de frente", "controle", "flanco"),

        s("Sima Yi", "Guiguzi", 9, ConfiancaDado.ALTA,
            "Camuflagem e chegada global tornam o pickoff difícil de antecipar.",
            "camuflagem", "acesso global", "silêncio"),
        s("Sima Yi", "Ming", 8, ConfiancaDado.MEDIA,
            "Amplificação aumenta a chance de eliminar a backline em uma entrada.",
            "amplificação", "explosão", "dive"),
        s("Sima Yi", "Zhang Fei", 8, ConfiancaDado.MEDIA,
            "Peel e linha de frente cobrem a saída após o mergulho.",
            "linha de frente", "desengage", "dive"),

        s("Wang Zhaojun", "Lian Po", 10, ConfiancaDado.ALTA,
            "Iniciação em área mantém inimigos dentro do congelamento e da tempestade.",
            "agrupamento", "congelamento", "controle em cadeia"),
        s("Wang Zhaojun", "Guiguzi", 9, ConfiancaDado.ALTA,
            "Agrupamento furtivo cria uma ultimate impossível de ignorar.",
            "camuflagem", "agrupamento", "dano em área"),
        s("Wang Zhaojun", "Dolia", 9, ConfiancaDado.ALTA,
            "Reset de ultimate permite controlar dois objetivos ou duas fases da luta.",
            "reset de ultimate", "objetivos", "zoneamento"),
        s("Wang Zhaojun", "Marco Polo", 8, ConfiancaDado.MEDIA,
            "Congelamento e desaceleração preparam a entrada da ultimate do ADC.",
            "controle", "ultimate em área", "engage"),

        s("Diaochan", "Dolia", 9, ConfiancaDado.ALTA,
            "Sustentação e reset permitem duas grandes janelas de luta prolongada.",
            "cura", "reset de ultimate", "luta longa"),
        s("Diaochan", "Cai Yan", 8, ConfiancaDado.ALTA,
            "Cura mantém Diaochan ativa enquanto ela acumula dano verdadeiro.",
            "cura", "dano sustentado", "mago de batalha"),
        s("Diaochan", "Zhang Fei", 8, ConfiancaDado.MEDIA,
            "Escudos e controle criam espaço para permanecer dentro da própria zona.",
            "escudo", "linha de frente", "luta longa")
    );

    public List<SinergiaMidEquipe> listarTodas() {
        return sinergias;
    }

    private SinergiaMidEquipe s(
        String mid,
        String aliado,
        int nota,
        ConfiancaDado confianca,
        String motivo,
        String... gatilhos
    ) {
        return new SinergiaMidEquipe(
            mid,
            aliado,
            nota,
            confianca,
            motivo,
            List.of(gatilhos)
        );
    }
}
