package br.com.carlosdaniel.hokdraftcoach.repository;

import java.util.List;

import org.springframework.stereotype.Repository;

import br.com.carlosdaniel.hokdraftcoach.model.ConfiancaDado;
import br.com.carlosdaniel.hokdraftcoach.model.SinergiaClashEquipe;

@Repository
public class SinergiaClashRepository {

    private final List<SinergiaClashEquipe> sinergias = List.of(
        s("Ata", "Marco Polo", 9, ConfiancaDado.ALTA,
            "Controle de terreno agrupa e mantém inimigos na ultimate do ADC.",
            "agrupamento", "controle", "ultimate em área"),
        s("Ata", "Yixing", 9, ConfiancaDado.ALTA,
            "Paredes e tabuleiro restringem completamente a área de fuga.",
            "controle de terreno", "confinamento", "objetivos"),
        s("Ata", "Wang Zhaojun", 9, ConfiancaDado.ALTA,
            "A iniciação mantém alvos dentro do congelamento e da tempestade.",
            "iniciação", "congelamento", "controle em cadeia"),

        s("Devara", "Dolia", 9, ConfiancaDado.MEDIA,
            "Cura e nova ultimate ampliam escudos, anti-controle e tempo de combate.",
            "cura", "reset de ultimate", "luta longa"),
        s("Devara", "Ming", 9, ConfiancaDado.MEDIA,
            "Amplificação acelera a geração de energia e o dano dos ataques aprimorados.",
            "amplificação", "energia", "duelo"),
        s("Devara", "Sun Bin", 8, ConfiancaDado.EXPLORATORIA,
            "Velocidade ajuda a manter contato durante a janela de anti-controle.",
            "velocidade", "anti-controle", "engage"),

        s("Fatih", "Cai Yan", 9, ConfiancaDado.ALTA,
            "Cura adicional multiplica o roubo de vida em lutas prolongadas.",
            "cura", "roubo de vida", "luta longa"),
        s("Fatih", "Zhuangzi", 8, ConfiancaDado.ALTA,
            "Purificação permite manter contato e continuar recuperando vida.",
            "anti-controle", "sustentação", "duelo"),
        s("Fatih", "Sun Bin", 8, ConfiancaDado.MEDIA,
            "Aceleração resolve o problema de alcance e oferece retirada segura.",
            "velocidade", "engage", "desengage"),

        s("Florentino", "Yaria", 10, ConfiancaDado.ALTA,
            "Escudo móvel acompanha todos os reposicionamentos do duelista.",
            "escudo", "mobilidade", "duelo"),
        s("Florentino", "Dolia", 9, ConfiancaDado.ALTA,
            "Cura e reutilização da ultimate prolongam a sequência de flores.",
            "cura", "reset de ultimate", "sustentação"),
        s("Florentino", "Liu Bang", 8, ConfiancaDado.MEDIA,
            "Proteção global permite pressionar a lateral e sobreviver ao colapso.",
            "proteção global", "split push", "duelo"),

        s("Ser do Fluxo (Tanque)", "Marco Polo", 9, ConfiancaDado.ALTA,
            "Linha de frente e controle criam espaço para a entrada do ADC.",
            "linha de frente", "controle", "ultimate em área"),
        s("Ser do Fluxo (Tanque)", "Wang Zhaojun", 9, ConfiancaDado.ALTA,
            "Engage em área prepara congelamento e tempestade.",
            "engage", "congelamento", "controle em cadeia"),
        s("Ser do Fluxo (Tanque)", "Garo", 8, ConfiancaDado.MEDIA,
            "Absorção de dano protege a atiradora imóvel durante o front-to-back.",
            "linha de frente", "peel", "hipercarregador"),

        s("Lapulapu", "Marco Polo", 9, ConfiancaDado.ALTA,
            "Múltiplos controles seguram inimigos na ultimate do ADC.",
            "iniciação", "controle em área", "ultimate em área"),
        s("Lapulapu", "Lorion", 8, ConfiancaDado.ALTA,
            "Engage frontal oferece tempo para Lorion montar sua zona de dano.",
            "engage", "controle", "dano em área"),
        s("Lapulapu", "Garo", 8, ConfiancaDado.MEDIA,
            "Proteção e linha de frente mantêm a hipercarregadora segura.",
            "proteção", "linha de frente", "hipercarregador"),

        s("Allain", "Ming", 10, ConfiancaDado.ALTA,
            "Amplificação fortalece dano misto, sustain e escalamento do duelista.",
            "amplificação", "dano misto", "duelo"),
        s("Allain", "Yaria", 9, ConfiancaDado.ALTA,
            "Escudo acompanha a entrada e protege durante a janela de invulnerabilidade.",
            "escudo", "dive", "invulnerabilidade"),
        s("Allain", "Da Qiao", 8, ConfiancaDado.MEDIA,
            "Macro transforma pressão lateral em retorno e teleporte seguros.",
            "macro", "split push", "escalamento"),

        s("Arthur", "Angela", 9, ConfiancaDado.ALTA,
            "Silêncio e controle simples mantêm o alvo no combo linear da maga.",
            "silêncio", "controle", "explosão"),
        s("Arthur", "Marco Polo", 8, ConfiancaDado.ALTA,
            "Linha de frente e silêncio criam espaço para o ADC entrar.",
            "linha de frente", "anti-mobilidade", "ultimate em área"),
        s("Arthur", "Cai Yan", 8, ConfiancaDado.MEDIA,
            "Cura transforma o tanque simples em presença prolongada.",
            "cura", "linha de frente", "luta longa"),

        s("Augran", "Dolia", 10, ConfiancaDado.ALTA,
            "Cura e reutilização de ultimate ampliam execução e presença frontal.",
            "cura", "reset de ultimate", "execução"),
        s("Augran", "Ming", 9, ConfiancaDado.ALTA,
            "Amplificação acelera dano sustentado e limiar de execução.",
            "amplificação", "execução", "dano sustentado"),
        s("Augran", "Zhang Fei", 9, ConfiancaDado.ALTA,
            "Escudos e segunda linha de frente permitem pressionar sem recuar.",
            "escudo", "linha de frente", "luta longa"),

        s("Bai Qi", "Wang Zhaojun", 10, ConfiancaDado.ALTA,
            "Provocação em área prepara congelamento e tempestade completos.",
            "provocação", "congelamento", "controle em cadeia"),
        s("Bai Qi", "Yixing", 10, ConfiancaDado.ALTA,
            "Provocação dentro do tabuleiro elimina todas as rotas de fuga.",
            "provocação", "confinamento", "team fight"),
        s("Bai Qi", "Dolia", 9, ConfiancaDado.ALTA,
            "Reset de ultimate oferece uma segunda provocação decisiva.",
            "reset de ultimate", "provocação", "engage"),

        s("Biron", "Sun Bin", 9, ConfiancaDado.ALTA,
            "Velocidade mantém contato e melhora a pressão de início de jogo.",
            "velocidade", "sustain", "snowball"),
        s("Biron", "Dyadia", 9, ConfiancaDado.ALTA,
            "Cura e mobilidade ampliam trocas e perseguições prolongadas.",
            "cura", "mobilidade", "duelo"),
        s("Biron", "Kongming", 8, ConfiancaDado.MEDIA,
            "Controle e dano inicial deixam alvos na faixa de execução do mago.",
            "controle", "execução", "snowball"),

        s("Charlotte", "Yaria", 9, ConfiancaDado.ALTA,
            "Escudo acompanha a duelista móvel durante combos e flancos.",
            "escudo", "mobilidade", "duelo"),
        s("Charlotte", "Liang", 9, ConfiancaDado.ALTA,
            "Supressão oferece alvo imóvel para completar toda a sequência.",
            "supressão", "combo", "duelo"),
        s("Charlotte", "Dolia", 8, ConfiancaDado.MEDIA,
            "Cura e reset mantêm a lutadora ativa em combates longos.",
            "cura", "reset de ultimate", "luta longa"),

        s("Chicha", "Sakeer", 9, ConfiancaDado.ALTA,
            "Visão e cura permitem aguardar o primeiro engage e entrar na limpeza.",
            "visão", "segundo engage", "cleanup"),
        s("Chicha", "Zhang Fei", 9, ConfiancaDado.ALTA,
            "Escudos preservam a lutadora até a janela de segundo engage.",
            "escudo", "linha de frente", "cleanup"),
        s("Chicha", "Dolia", 8, ConfiancaDado.MEDIA,
            "Sustentação e nova ultimate ampliam dano contínuo e limpeza.",
            "cura", "reset de ultimate", "dano sustentado"),

        s("Diaochan", "Dolia", 10, ConfiancaDado.ALTA,
            "Cura e reset de ultimate criam duas zonas completas de dança.",
            "cura", "reset de ultimate", "dano verdadeiro"),
        s("Diaochan", "Yaria", 9, ConfiancaDado.ALTA,
            "Escudo acompanha os dashes e reduz o risco dentro da formação inimiga.",
            "escudo", "mobilidade", "luta longa"),
        s("Diaochan", "Zhuangzi", 8, ConfiancaDado.MEDIA,
            "Purificação impede que controle interrompa sua sequência de dashes.",
            "anti-controle", "dano verdadeiro", "mobilidade"),

        s("Donghuang", "Angela", 10, ConfiancaDado.ALTA,
            "Supressão torna impossível escapar do combo completo da maga.",
            "supressão", "explosão", "pickoff"),
        s("Donghuang", "Gan & Mo", 10, ConfiancaDado.ALTA,
            "Alvo imóvel oferece trajetória garantida para toda a artilharia.",
            "supressão", "artilharia", "explosão"),
        s("Donghuang", "Marco Polo", 9, ConfiancaDado.ALTA,
            "Supressão remove a principal ameaça antes da entrada do ADC.",
            "supressão", "anti-carry", "ultimate em área"),

        s("Dun", "Marco Polo", 9, ConfiancaDado.ALTA,
            "Controle, escudo e frontline criam espaço para o ADC canalizar dano.",
            "linha de frente", "controle", "ultimate em área"),
        s("Dun", "Dolia", 9, ConfiancaDado.ALTA,
            "Sustentação em camadas torna o tanque muito difícil de remover.",
            "cura", "escudo", "luta longa"),
        s("Dun", "Garo", 8, ConfiancaDado.MEDIA,
            "Peel e resistência protegem a atiradora de longo alcance.",
            "peel", "linha de frente", "hipercarregador"),

        s("Fuzi", "Da Qiao", 10, ConfiancaDado.ALTA,
            "Split push, aprisionamento e teleporte criam pressão lateral constante.",
            "split push", "macro", "aprisionamento"),
        s("Fuzi", "Milady", 9, ConfiancaDado.ALTA,
            "Duas fontes de pressão em torre obrigam o inimigo a dividir recursos.",
            "split push", "torres", "macro"),
        s("Fuzi", "Liu Bang", 8, ConfiancaDado.MEDIA,
            "Proteção global permite manter o duelo lateral sob colapso inimigo.",
            "proteção global", "duelo", "split push"),

        s("Guan Yu", "Da Qiao", 10, ConfiancaDado.ALTA,
            "Rotação extrema e portais criam superioridade em qualquer lado do mapa.",
            "macro", "rotação", "flanco"),
        s("Guan Yu", "Liu Bang", 9, ConfiancaDado.ALTA,
            "Proteção global acompanha o flanco profundo e reduz o risco da entrada.",
            "proteção global", "flanco", "deslocamento"),
        s("Guan Yu", "Wang Zhaojun", 8, ConfiancaDado.MEDIA,
            "Deslocamentos empurram inimigos para dentro da tempestade.",
            "deslocamento", "congelamento", "controle em área"),

        s("Heino", "Sakeer", 9, ConfiancaDado.ALTA,
            "Visão e cura protegem o mago enquanto ele desgasta a rota e a luta.",
            "visão", "cura", "poke"),
        s("Heino", "Zhang Fei", 9, ConfiancaDado.ALTA,
            "Peel e escudos impedem dive sobre o mago de alcance.",
            "peel", "escudo", "front-to-back"),
        s("Heino", "Dolia", 8, ConfiancaDado.MEDIA,
            "Sustentação e reset temporal ampliam a sobrevivência em lutas longas.",
            "cura", "reset de ultimate", "tempo"),

        s("Kaizer", "Yaria", 9, ConfiancaDado.ALTA,
            "Escudo sobre a transformação cria um mergulho muito difícil de parar.",
            "escudo", "transformação", "dive"),
        s("Kaizer", "Ming", 9, ConfiancaDado.ALTA,
            "Amplificação transforma o duelista em ameaça direta ao carry.",
            "amplificação", "duelo", "anti-carry"),
        s("Kaizer", "Dolia", 8, ConfiancaDado.MEDIA,
            "Cura e reset prolongam a janela da transformação.",
            "cura", "reset de ultimate", "linha de frente"),

        s("Li Xin", "Da Qiao", 10, ConfiancaDado.ALTA,
            "Pressão lateral, retorno e teleporte formam um plano completo de macro.",
            "split push", "macro", "torres"),
        s("Li Xin", "Guiguzi", 9, ConfiancaDado.ALTA,
            "Camuflagem e agrupamento criam ângulo para a forma de engage.",
            "camuflagem", "agrupamento", "snowball"),
        s("Li Xin", "Liu Shan", 9, ConfiancaDado.ALTA,
            "Pressão conjunta destrói torres rapidamente após qualquer pickoff.",
            "torres", "controle", "pressão lateral"),

        s("Lian Po", "Yixing", 10, ConfiancaDado.ALTA,
            "Múltiplos knockups mantêm inimigos presos dentro do tabuleiro.",
            "knockup", "confinamento", "team fight"),
        s("Lian Po", "Wang Zhaojun", 10, ConfiancaDado.ALTA,
            "Controle em cadeia prepara toda a tempestade congelante.",
            "knockup", "congelamento", "controle em cadeia"),
        s("Lian Po", "Marco Polo", 9, ConfiancaDado.ALTA,
            "Engage resistente segura a formação para a ultimate do ADC.",
            "engage", "agrupamento", "ultimate em área"),

        s("Liu Bang", "Gao Jianli", 10, ConfiancaDado.ALTA,
            "Proteção global entrega o mago de batalha no centro da luta.",
            "proteção global", "dive", "dano em área"),
        s("Liu Bang", "Sima Yi", 9, ConfiancaDado.ALTA,
            "Dois acessos globais criam pickoff e sobrevivência na retaguarda.",
            "proteção global", "acesso global", "explosão"),
        s("Liu Bang", "Marco Polo", 9, ConfiancaDado.ALTA,
            "Escudo global protege o ADC durante sua entrada agressiva.",
            "proteção global", "escudo", "ultimate em área"),

        s("Lu Bu", "Guiguzi", 10, ConfiancaDado.ALTA,
            "Agrupamento prepara uma ultimate com dano verdadeiro em vários alvos.",
            "agrupamento", "dano verdadeiro", "engage"),
        s("Lu Bu", "Dolia", 9, ConfiancaDado.ALTA,
            "Reset de ultimate oferece uma segunda zona decisiva de engage.",
            "reset de ultimate", "dano verdadeiro", "team fight"),
        s("Lu Bu", "Cai Yan", 8, ConfiancaDado.MEDIA,
            "Cura permite permanecer no centro da luta causando dano verdadeiro.",
            "cura", "linha de frente", "luta longa"),

        s("Mayene", "Liang", 9, ConfiancaDado.ALTA,
            "Supressão oferece tempo para escolher e completar o combo ideal.",
            "supressão", "combos", "controle"),
        s("Mayene", "Lian Po", 8, ConfiancaDado.ALTA,
            "Iniciação frontal libera a lutadora para flanquear e deslocar carries.",
            "iniciação", "flanco", "controle"),
        s("Mayene", "Dolia", 8, ConfiancaDado.MEDIA,
            "Cura e reset sustentam sequências mecânicas prolongadas.",
            "cura", "reset de ultimate", "combos"),

        s("Menki", "Cai Yan", 9, ConfiancaDado.ALTA,
            "Cura e escudos criam uma frontline extremamente resistente.",
            "cura", "escudo", "linha de frente"),
        s("Menki", "Marco Polo", 8, ConfiancaDado.ALTA,
            "Controle de espaço protege o ADC e prende inimigos no alcance.",
            "linha de frente", "peel", "dano sustentado"),
        s("Menki", "Ming", 8, ConfiancaDado.MEDIA,
            "Amplificação fortalece dano misto, escudos e pressão lateral.",
            "amplificação", "dano misto", "split push"),

        s("Mi Yue", "Da Qiao", 10, ConfiancaDado.ALTA,
            "Sustain lateral e teleporte formam uma composição de split push forte.",
            "split push", "macro", "sustentação"),
        s("Mi Yue", "Ming", 9, ConfiancaDado.ALTA,
            "Amplificação fortalece dano mágico e recuperação no duelo.",
            "amplificação", "dano mágico", "duelo"),
        s("Mi Yue", "Zhuangzi", 8, ConfiancaDado.MEDIA,
            "Purificação permite manter vínculo e dano durante controles inimigos.",
            "anti-controle", "sustentação", "duelo"),

        s("Mulan", "Guiguzi", 9, ConfiancaDado.ALTA,
            "Camuflagem esconde o flanco e permite silêncio sobre múltiplos alvos.",
            "camuflagem", "flanco", "silêncio"),
        s("Mulan", "Liu Bang", 9, ConfiancaDado.ALTA,
            "Proteção global acompanha a entrada profunda na backline.",
            "proteção global", "flanco", "explosão"),
        s("Mulan", "Liang", 8, ConfiancaDado.MEDIA,
            "Supressão cria alvo imóvel para a sequência de duas armas.",
            "supressão", "silêncio", "burst"),

        s("Musashi", "Liang", 9, ConfiancaDado.ALTA,
            "Supressão permite remover a principal fonte de cura ou dano.",
            "supressão", "anti-carry", "anti-cura"),
        s("Musashi", "Yaria", 8, ConfiancaDado.ALTA,
            "Escudo acompanha o mergulho durante a ultimate de foco.",
            "escudo", "dive", "anti-carry"),
        s("Musashi", "Daji", 8, ConfiancaDado.MEDIA,
            "Controle garantido deixa o carry pronto para foco e anti-cura.",
            "controle garantido", "anti-cura", "explosão"),

        s("Nezha", "Liu Bang", 10, ConfiancaDado.ALTA,
            "Duas ultimates globais transformam qualquer alvo isolado em superioridade.",
            "global", "proteção global", "pickoff"),
        s("Nezha", "Da Qiao", 9, ConfiancaDado.ALTA,
            "Portais permitem pressionar lateral e iniciar em qualquer parte do mapa.",
            "macro", "global", "split push"),
        s("Nezha", "Sima Yi", 8, ConfiancaDado.MEDIA,
            "Acesso global duplo apaga rapidamente a retaguarda inimiga.",
            "acesso global", "dive", "anti-carry"),

        s("Sun Ce", "Gao Jianli", 10, ConfiancaDado.ALTA,
            "Navio entrega o mago de batalha no centro da formação.",
            "iniciação global", "dano em área", "dive"),
        s("Sun Ce", "Wang Zhaojun", 10, ConfiancaDado.ALTA,
            "Controle em cadeia prepara congelamento e tempestade.",
            "iniciação global", "congelamento", "controle em cadeia"),
        s("Sun Ce", "Marco Polo", 9, ConfiancaDado.ALTA,
            "Engage global agrupa antes da ultimate do ADC.",
            "iniciação", "agrupamento", "ultimate em área"),

        s("Ukyo Tachibana", "Kui", 9, ConfiancaDado.ALTA,
            "Gancho coloca o alvo no alcance do controle e burst curto.",
            "gancho", "controle", "explosão"),
        s("Ukyo Tachibana", "Daji", 8, ConfiancaDado.ALTA,
            "Controle garantido permite completar a sequência sem perder distância.",
            "controle garantido", "explosão", "pickoff"),
        s("Ukyo Tachibana", "Sun Bin", 8, ConfiancaDado.MEDIA,
            "Velocidade ajuda a entrar no alcance curto e sair após o combo.",
            "velocidade", "poke curto", "desengage"),

        s("Umbrosa", "Cai Yan", 9, ConfiancaDado.ALTA,
            "Cura adicional e ressurreição criam duas fases de frontline.",
            "cura", "ressurreição", "linha de frente"),
        s("Umbrosa", "Dolia", 9, ConfiancaDado.ALTA,
            "Sustentação em camadas prolonga muito o dano contínuo.",
            "cura", "ressurreição", "luta longa"),
        s("Umbrosa", "Zhuangzi", 8, ConfiancaDado.MEDIA,
            "Purificação impede que controle negue a segunda entrada.",
            "anti-controle", "ressurreição", "linha de frente"),

        s("Wuyan", "Wang Zhaojun", 9, ConfiancaDado.ALTA,
            "Petrificação prepara congelamento e tempestade em área.",
            "petrificação", "congelamento", "controle em cadeia"),
        s("Wuyan", "Marco Polo", 9, ConfiancaDado.ALTA,
            "Controle em área mantém inimigos dentro da ultimate do ADC.",
            "petrificação", "agrupamento", "ultimate em área"),
        s("Wuyan", "Cai Yan", 8, ConfiancaDado.MEDIA,
            "Cura prolonga a presença frontal enquanto busca novas petrificações.",
            "cura", "linha de frente", "controle"),

        s("Xiang Yu", "Garo", 9, ConfiancaDado.ALTA,
            "Deslocamento e peel mantêm a hipercarregadora longe do dive.",
            "peel", "deslocamento", "hipercarregador"),
        s("Xiang Yu", "Marco Polo", 8, ConfiancaDado.ALTA,
            "Empurra mergulhadores para longe durante a ultimate do ADC.",
            "peel", "anti-dive", "ultimate em área"),
        s("Xiang Yu", "Dolia", 8, ConfiancaDado.MEDIA,
            "Cura e reset ampliam mitigação e capacidade de proteção.",
            "cura", "reset de ultimate", "linha de frente"),

        s("Yang Jian", "Liang", 9, ConfiancaDado.ALTA,
            "Supressão permite conectar a marca, executar e recuperar vida.",
            "supressão", "execução", "sustentação"),
        s("Yang Jian", "Sun Bin", 8, ConfiancaDado.ALTA,
            "Velocidade mantém contato com o alvo marcado durante a perseguição.",
            "velocidade", "perseguição", "execução"),
        s("Yang Jian", "Ming", 8, ConfiancaDado.MEDIA,
            "Amplificação melhora dano verdadeiro e recuperação no duelo.",
            "amplificação", "dano verdadeiro", "duelo"),

        s("Yao", "Dolia", 9, ConfiancaDado.ALTA,
            "Reset de ultimate oferece outra janela de retorno e mobilidade.",
            "reset de ultimate", "mobilidade", "combos"),
        s("Yao", "Yaria", 8, ConfiancaDado.ALTA,
            "Escudo móvel acompanha entradas e retornos do lutador.",
            "escudo", "mobilidade", "duelo"),
        s("Yao", "Da Qiao", 8, ConfiancaDado.MEDIA,
            "Macro e mobilidade criam pressão lateral e retirada segura.",
            "macro", "split push", "mobilidade"),

        s("Zhuangzi", "Hou Yi", 9, ConfiancaDado.ALTA,
            "Purificação e frontline permitem ao hipercarregador atacar sem interrupção.",
            "anti-controle", "proteção", "hipercarregador"),
        s("Zhuangzi", "Garo", 9, ConfiancaDado.ALTA,
            "Anti-controle protege a atiradora imóvel durante o front-to-back.",
            "anti-controle", "peel", "hipercarregador"),
        s("Zhuangzi", "Gao Jianli", 8, ConfiancaDado.MEDIA,
            "Purificação permite ao mago permanecer no centro da formação.",
            "anti-controle", "dive", "dano em área"),

        s("Dharma", "Wang Zhaojun", 10, ConfiancaDado.ALTA,
            "Knockback na parede entrega congelamento e tempestade completos.",
            "parede", "congelamento", "controle em cadeia"),
        s("Dharma", "Angela", 9, ConfiancaDado.ALTA,
            "Controle contra parede mantém o alvo dentro de todo o combo.",
            "parede", "alvo imóvel", "explosão"),
        s("Dharma", "Gan & Mo", 9, ConfiancaDado.ALTA,
            "Alvo preso oferece trajetória previsível para a artilharia.",
            "parede", "artilharia", "explosão")
    );

    public List<SinergiaClashEquipe> listarTodas() {
        return sinergias;
    }

    private SinergiaClashEquipe s(
        String top,
        String aliado,
        int nota,
        ConfiancaDado confianca,
        String motivo,
        String... gatilhos
    ) {
        return new SinergiaClashEquipe(
            top,
            aliado,
            nota,
            confianca,
            motivo,
            List.of(gatilhos)
        );
    }
}
