package br.com.carlosdaniel.hokdraftcoach.repository;

import java.util.List;

import org.springframework.stereotype.Repository;

import br.com.carlosdaniel.hokdraftcoach.model.ConfiancaDado;
import br.com.carlosdaniel.hokdraftcoach.model.SinergiaJungleEquipe;

@Repository
public class SinergiaJungleRepository {

    private final List<SinergiaJungleEquipe> sinergias = List.of(
        s("Ata", "Marco Polo", 9, ConfiancaDado.ALTA,
            "Controle de terreno e agrupamento preparam a ultimate do ADC.",
            "iniciação", "agrupamento", "ultimate em área"),
        s("Ata", "Yixing", 9, ConfiancaDado.ALTA,
            "Paredes e tabuleiro limitam completamente a área de fuga.",
            "controle de terreno", "confinamento", "objetivos"),
        s("Ata", "Wang Zhaojun", 9, ConfiancaDado.ALTA,
            "Iniciação mantém inimigos dentro do congelamento e da tempestade.",
            "iniciação", "congelamento", "controle em cadeia"),

        s("Butterfly", "Guiguzi", 9, ConfiancaDado.ALTA,
            "Camuflagem e agrupamento produzem a primeira execução para os resets.",
            "camuflagem", "agrupamento", "reset"),
        s("Butterfly", "Liang", 9, ConfiancaDado.ALTA,
            "Supressão deixa um alvo pronto para execução e inicia a limpeza.",
            "supressão", "execução", "reset"),
        s("Butterfly", "Dolia", 8, ConfiancaDado.MEDIA,
            "Sustentação e nova janela de ultimate ajudam a manter a cadeia de abates.",
            "sustentação", "reset de ultimate", "cleanup"),

        s("Fatih", "Cai Yan", 9, ConfiancaDado.ALTA,
            "Cura adicional multiplica o valor do roubo de vida em lutas longas.",
            "cura", "roubo de vida", "luta longa"),
        s("Fatih", "Zhuangzi", 8, ConfiancaDado.ALTA,
            "Purificação permite permanecer em contato e continuar recuperando vida.",
            "anti-controle", "sustentação", "duelo"),
        s("Fatih", "Sun Bin", 8, ConfiancaDado.MEDIA,
            "Aceleração reduz o problema de alcance e oferece retirada após a entrada.",
            "velocidade", "engage", "desengage"),

        s("Agu", "Sun Bin", 9, ConfiancaDado.ALTA,
            "Velocidade e utilidade transformam buffs e poke em controle de objetivo.",
            "velocidade", "buffs", "objetivos"),
        s("Agu", "Sakeer", 9, ConfiancaDado.ALTA,
            "Visão e cura protegem a jungler atiradora durante cerco e objetivos.",
            "visão", "cura", "cerco"),
        s("Agu", "Da Qiao", 8, ConfiancaDado.MEDIA,
            "Macro e retorno seguro ampliam a pressão de mapa da composição.",
            "macro", "objetivos", "reposicionamento"),

        s("Arke", "Guiguzi", 10, ConfiancaDado.ALTA,
            "Camuflagem coletiva permite flanco invisível e primeiro reset.",
            "camuflagem", "flanco", "reset"),
        s("Arke", "Daji", 9, ConfiancaDado.ALTA,
            "Controle garantido entrega a execução e abre a cadeia de abates.",
            "controle garantido", "explosão", "reset"),
        s("Arke", "Yaria", 8, ConfiancaDado.MEDIA,
            "Escudo acompanha o mergulho e aumenta a chance de saída após o abate.",
            "escudo", "dive", "sobrevivência"),

        s("Arthur", "Angela", 9, ConfiancaDado.ALTA,
            "Silêncio e controle simples mantêm o alvo no combo linear da maga.",
            "silêncio", "controle", "explosão"),
        s("Arthur", "Marco Polo", 8, ConfiancaDado.MEDIA,
            "Linha de frente e silêncio criam espaço para o ADC entrar.",
            "linha de frente", "anti-mobilidade", "ultimate em área"),
        s("Arthur", "Cai Yan", 8, ConfiancaDado.MEDIA,
            "Cura transforma o tanque simples em presença prolongada na linha frontal.",
            "cura", "linha de frente", "luta longa"),

        s("Athena", "Ming", 9, ConfiancaDado.ALTA,
            "Amplificação fortalece duelos, invasões e dano de ataques aprimorados.",
            "amplificação", "invasão", "duelo"),
        s("Athena", "Liu Bang", 8, ConfiancaDado.ALTA,
            "Proteção global acompanha invasões profundas e reduz o risco da entrada.",
            "proteção global", "invasão", "escudo"),
        s("Athena", "Da Qiao", 8, ConfiancaDado.MEDIA,
            "Retorno e teleporte convertem pressão agressiva em macro seguro.",
            "macro", "invasão", "retorno"),

        s("Augran", "Dolia", 10, ConfiancaDado.ALTA,
            "Cura e reutilização de ultimate ampliam execução e presença prolongada.",
            "cura", "reset de ultimate", "execução"),
        s("Augran", "Ming", 9, ConfiancaDado.ALTA,
            "Amplificação acelera dano sustentado e limiar de execução.",
            "amplificação", "execução", "dano sustentado"),
        s("Augran", "Zhang Fei", 9, ConfiancaDado.ALTA,
            "Escudos e linha de frente permitem que Augran pressione sem recuar.",
            "escudo", "linha de frente", "luta longa"),
        s("Augran", "Liang", 9, ConfiancaDado.MEDIA,
            "Supressão segura a ameaça enquanto Augran acumula dano e executa.",
            "supressão", "execução", "controle"),

        s("Chano", "Dolia", 9, ConfiancaDado.ALTA,
            "Sustentação e reset de ultimate ampliam a janela de cleanup tardio.",
            "cura", "reset de ultimate", "cleanup"),
        s("Chano", "Sakeer", 9, ConfiancaDado.ALTA,
            "Visão e cura mantêm o segundo atirador seguro durante o escalamento.",
            "visão", "cura", "front-to-back"),
        s("Chano", "Zhang Fei", 9, ConfiancaDado.ALTA,
            "Peel e escudos protegem o dano sustentado do atirador jungle.",
            "peel", "escudo", "dano sustentado"),

        s("Charlotte", "Yaria", 8, ConfiancaDado.ALTA,
            "Escudo acompanha a duelista móvel durante combos e flancos.",
            "escudo", "mobilidade", "duelo"),
        s("Charlotte", "Dolia", 8, ConfiancaDado.MEDIA,
            "Cura e utilidade mantêm a sequência de habilidades em lutas longas.",
            "cura", "combos", "luta longa"),
        s("Charlotte", "Liang", 8, ConfiancaDado.MEDIA,
            "Supressão cria alvo imóvel para completar os combos de redução de dano.",
            "supressão", "duelo", "controle"),

        s("Chicha", "Sakeer", 9, ConfiancaDado.ALTA,
            "Visão e cura permitem aguardar o primeiro engage e entrar na limpeza.",
            "visão", "segundo engage", "cleanup"),
        s("Chicha", "Feyd", 8, ConfiancaDado.ALTA,
            "Feyd inicia pela lateral e Chicha entra após os cooldowns defensivos.",
            "flanco", "segundo engage", "limpeza"),
        s("Chicha", "Chano", 8, ConfiancaDado.ALTA,
            "Iniciação e dano sustentado criam múltiplas ondas de cleanup.",
            "iniciação", "dano sustentado", "cleanup"),

        s("Cirrus", "Guiguzi", 9, ConfiancaDado.MEDIA,
            "Camuflagem e voo criam flancos difíceis de rastrear.",
            "camuflagem", "voo", "flanco"),
        s("Cirrus", "Liu Bang", 8, ConfiancaDado.MEDIA,
            "Proteção global acompanha a entrada aérea na retaguarda.",
            "proteção global", "dive", "backline"),
        s("Cirrus", "Da Qiao", 8, ConfiancaDado.MEDIA,
            "Mobilidade de mapa e portais criam pressão simultânea em várias rotas.",
            "macro", "voo", "rotação"),

        s("Dharma", "Wang Zhaojun", 10, ConfiancaDado.ALTA,
            "Knockback na parede entrega congelamento e tempestade em área.",
            "parede", "congelamento", "controle em cadeia"),
        s("Dharma", "Angela", 9, ConfiancaDado.ALTA,
            "Controle contra parede mantém o alvo dentro de todo o combo.",
            "parede", "alvo imóvel", "explosão"),
        s("Dharma", "Gan & Mo", 9, ConfiancaDado.ALTA,
            "Alvo preso em parede oferece trajetória previsível para a artilharia.",
            "parede", "artilharia", "explosão"),

        s("Dian Wei", "Sun Bin", 9, ConfiancaDado.ALTA,
            "Aceleração resolve o problema de alcance e mantém contato no duelo.",
            "velocidade", "perseguição", "dano verdadeiro"),
        s("Dian Wei", "Cai Yan", 8, ConfiancaDado.ALTA,
            "Cura prolonga o tempo necessário para acumular dano e executar tanques.",
            "cura", "dano verdadeiro", "luta longa"),
        s("Dian Wei", "Zhuangzi", 8, ConfiancaDado.MEDIA,
            "Purificação impede que controles interrompam sua perseguição linear.",
            "anti-controle", "perseguição", "duelo"),

        s("Fang", "Liu Shan", 9, ConfiancaDado.ALTA,
            "Pressão precoce, controle e dano a estruturas aceleram o snowball.",
            "objetivos", "torres", "snowball"),
        s("Fang", "Dolia", 8, ConfiancaDado.ALTA,
            "Cura e reutilização de ultimate criam duas zonas de explosão.",
            "cura", "reset de ultimate", "objetivos"),
        s("Fang", "Da Qiao", 8, ConfiancaDado.MEDIA,
            "Macro converte a limpeza rápida em objetivos opostos no mapa.",
            "macro", "limpeza", "objetivos"),

        s("Feyd", "Guiguzi", 9, ConfiancaDado.ALTA,
            "Camuflagem combinada com terreno cria emboscadas sem informação.",
            "camuflagem", "terreno", "emboscada"),
        s("Feyd", "Liu Bang", 9, ConfiancaDado.ALTA,
            "Proteção global acompanha o flanco e absorve a resposta inimiga.",
            "proteção global", "flanco", "explosão"),
        s("Feyd", "Shi", 8, ConfiancaDado.MEDIA,
            "Reposicionamento de Shi coloca o alvo na rota de emboscada.",
            "reposicionamento", "emboscada", "pickoff"),

        s("Gao Changgong", "Guiguzi", 10, ConfiancaDado.ALTA,
            "Dupla camuflagem transforma a primeira rotação em ameaça invisível.",
            "camuflagem", "gank", "explosão"),
        s("Gao Changgong", "Daji", 9, ConfiancaDado.ALTA,
            "Controle garantido e burst combinado eliminam antes da reação.",
            "controle garantido", "explosão", "pickoff"),
        s("Gao Changgong", "Da Qiao", 8, ConfiancaDado.MEDIA,
            "Portais e macro permitem aparecer em rotas frágeis repetidamente.",
            "macro", "gank", "furtividade"),

        s("Han Xin", "Da Qiao", 10, ConfiancaDado.ALTA,
            "Mobilidade extrema e teleporte criam uma composição de split push.",
            "split push", "macro", "mobilidade"),
        s("Han Xin", "Sun Bin", 8, ConfiancaDado.ALTA,
            "Velocidade amplia invasões e permite sair após roubar objetivos.",
            "velocidade", "invasão", "objetivos"),
        s("Han Xin", "Milady", 8, ConfiancaDado.MEDIA,
            "Pressão simultânea de jungle e torres sufoca recursos do mapa.",
            "invasão", "torres", "macro"),

        s("Jing", "Yaria", 9, ConfiancaDado.ALTA,
            "Escudo acompanha a assassina durante os movimentos dentro dos espelhos.",
            "escudo", "mobilidade", "outplay"),
        s("Jing", "Liang", 9, ConfiancaDado.ALTA,
            "Supressão cria alvo imóvel para uma sequência completa de espelhos.",
            "supressão", "execução", "espelhos"),
        s("Jing", "Dolia", 8, ConfiancaDado.MEDIA,
            "Sustentação e nova janela de ultimate ampliam o potencial de luta.",
            "cura", "reset de ultimate", "mobilidade"),

        s("Kaizer", "Yaria", 9, ConfiancaDado.ALTA,
            "Escudo sobre a transformação cria um mergulho muito difícil de parar.",
            "escudo", "transformação", "dive"),
        s("Kaizer", "Ming", 9, ConfiancaDado.ALTA,
            "Amplificação transforma o duelista em ameaça direta ao carry.",
            "amplificação", "duelo", "anti-carry"),
        s("Kaizer", "Dolia", 8, ConfiancaDado.MEDIA,
            "Cura e reutilização de ultimate prolongam a presença transformada.",
            "cura", "reset de ultimate", "linha de frente"),

        s("Kongming", "Guiguzi", 9, ConfiancaDado.ALTA,
            "Agrupamento reduz vários alvos à faixa de execução e inicia resets.",
            "agrupamento", "execução", "reset"),
        s("Kongming", "Donghuang", 9, ConfiancaDado.ALTA,
            "Supressão garante o primeiro alvo para iniciar a cadeia de execuções.",
            "supressão", "execução", "snowball"),
        s("Kongming", "Dolia", 8, ConfiancaDado.MEDIA,
            "Reset de ultimate oferece outra execução durante a mesma luta.",
            "reset de ultimate", "execução", "mobilidade"),

        s("Lam", "Guiguzi", 9, ConfiancaDado.ALTA,
            "Camuflagem e controle criam entrada inesperada pelo rio.",
            "camuflagem", "rio", "execução"),
        s("Lam", "Liang", 9, ConfiancaDado.ALTA,
            "Supressão deixa o alvo na vida ideal para execução.",
            "supressão", "execução", "pickoff"),
        s("Lam", "Da Qiao", 8, ConfiancaDado.MEDIA,
            "Macro e acesso pelo rio criam pressão constante entre as rotas.",
            "macro", "rio", "rotação"),

        s("Li Bai", "Yaria", 9, ConfiancaDado.ALTA,
            "Escudo acompanha entradas curtas sem impedir o retorno seguro.",
            "escudo", "poke", "mobilidade"),
        s("Li Bai", "Dolia", 8, ConfiancaDado.ALTA,
            "Reset de ultimate permite repetir a janela invulnerável de dano.",
            "reset de ultimate", "invulnerabilidade", "poke"),
        s("Li Bai", "Shi", 8, ConfiancaDado.MEDIA,
            "Reposicionamento inimigo oferece ângulo para entrada e ultimate.",
            "reposicionamento", "explosão", "pickoff"),

        s("Liu Bei", "Ming", 10, ConfiancaDado.ALTA,
            "Amplificação aumenta limpeza, invasão, escudo e dano próximo.",
            "amplificação", "invasão", "duelo"),
        s("Liu Bei", "Dyadia", 9, ConfiancaDado.ALTA,
            "Cura e pressão acompanham a invasão agressiva.",
            "cura", "invasão", "pressão"),
        s("Liu Bei", "Guiguzi", 8, ConfiancaDado.MEDIA,
            "Agrupamento aproxima múltiplos inimigos do dano máximo da arma.",
            "agrupamento", "dano próximo", "explosão"),

        s("Luna", "Yaria", 10, ConfiancaDado.ALTA,
            "Escudo móvel acompanha todos os resets e reduz o risco mecânico.",
            "escudo", "reset", "mobilidade"),
        s("Luna", "Dolia", 9, ConfiancaDado.ALTA,
            "Cura e reutilização de ultimate criam outra sequência de resets.",
            "cura", "reset de ultimate", "dano mágico"),
        s("Luna", "Zhuangzi", 8, ConfiancaDado.MEDIA,
            "Purificação impede que controle interrompa a cadeia de marcas.",
            "anti-controle", "reset", "mobilidade"),

        s("Mayene", "Liang", 9, ConfiancaDado.ALTA,
            "Supressão oferece tempo para escolher e completar o combo ideal.",
            "supressão", "combos", "controle"),
        s("Mayene", "Dolia", 8, ConfiancaDado.MEDIA,
            "Cura e utilidade sustentam a lutadora durante sequências longas.",
            "cura", "combos", "duelo"),
        s("Mayene", "Lian Po", 8, ConfiancaDado.MEDIA,
            "Iniciação frontal libera Mayene para flanquear e deslocar carries.",
            "iniciação", "flanco", "controle"),

        s("Menki", "Cai Yan", 9, ConfiancaDado.ALTA,
            "Cura e escudos criam uma linha de frente difícil de remover.",
            "cura", "escudo", "linha de frente"),
        s("Menki", "Dolia", 8, ConfiancaDado.ALTA,
            "Sustentação prolonga o dano misto e a pressão de objetivo.",
            "cura", "objetivos", "dano misto"),
        s("Menki", "Marco Polo", 8, ConfiancaDado.MEDIA,
            "Linha de frente e controle de espaço permitem ao ADC causar dano livre.",
            "linha de frente", "peel", "dano sustentado"),

        s("Mi Yue", "Da Qiao", 9, ConfiancaDado.ALTA,
            "Sustentação lateral e teleporte formam forte composição de split push.",
            "split push", "macro", "sustentação"),
        s("Mi Yue", "Ming", 8, ConfiancaDado.ALTA,
            "Amplificação fortalece dano mágico e cura em duelos prolongados.",
            "amplificação", "dano mágico", "duelo"),
        s("Mi Yue", "Zhuangzi", 8, ConfiancaDado.MEDIA,
            "Purificação permite manter vínculo e dano durante controles inimigos.",
            "anti-controle", "sustentação", "duelo"),

        s("Musashi", "Daji", 9, ConfiancaDado.ALTA,
            "Controle garantido deixa o carry pronto para foco e anti-cura.",
            "controle garantido", "anti-cura", "explosão"),
        s("Musashi", "Liang", 9, ConfiancaDado.ALTA,
            "Supressão permite escolher e remover a principal fonte de cura ou dano.",
            "supressão", "anti-carry", "anti-cura"),
        s("Musashi", "Yaria", 8, ConfiancaDado.MEDIA,
            "Escudo acompanha o mergulho e protege durante a ultimate de foco.",
            "escudo", "dive", "anti-carry"),

        s("Nakoruru", "Ming", 9, ConfiancaDado.ALTA,
            "Amplificação aumenta o burst percentual e garante execução rápida.",
            "amplificação", "dano percentual", "explosão"),
        s("Nakoruru", "Donghuang", 9, ConfiancaDado.ALTA,
            "Supressão remove a chance de escapar da entrada aérea.",
            "supressão", "explosão", "gank"),
        s("Nakoruru", "Guiguzi", 8, ConfiancaDado.MEDIA,
            "Camuflagem coletiva esconde a rota da entrada aérea.",
            "camuflagem", "gank", "explosão"),

        s("Pei", "Ming", 10, ConfiancaDado.ALTA,
            "Amplificação maximiza o pico precoce, invasão e dano das duas formas.",
            "amplificação", "invasão", "duas formas"),
        s("Pei", "Guiguzi", 9, ConfiancaDado.ALTA,
            "Camuflagem e agrupamento convertem a prioridade inicial em eliminações.",
            "camuflagem", "agrupamento", "snowball"),
        s("Pei", "Da Qiao", 8, ConfiancaDado.MEDIA,
            "Macro usa a vantagem inicial para controlar ambos os lados do mapa.",
            "macro", "invasão", "objetivos"),

        s("Sima Yi", "Guiguzi", 9, ConfiancaDado.ALTA,
            "Camuflagem e chegada global tornam o pickoff quase impossível de prever.",
            "camuflagem", "acesso global", "silêncio"),
        s("Sima Yi", "Ming", 9, ConfiancaDado.ALTA,
            "Amplificação aumenta a chance de eliminar a backline em uma entrada.",
            "amplificação", "explosão mágica", "dive"),
        s("Sima Yi", "Zhang Fei", 8, ConfiancaDado.MEDIA,
            "Peel e linha de frente cobrem a saída após o mergulho global.",
            "linha de frente", "desengage", "dive"),

        s("Sun Ce", "Gao Jianli", 10, ConfiancaDado.ALTA,
            "Navio inicia e entrega o mago de batalha no centro da formação.",
            "iniciação global", "dano em área", "dive"),
        s("Sun Ce", "Wang Zhaojun", 10, ConfiancaDado.ALTA,
            "Controle em cadeia prepara congelamento e tempestade.",
            "iniciação global", "congelamento", "controle em cadeia"),
        s("Sun Ce", "Marco Polo", 9, ConfiancaDado.ALTA,
            "Engage global agrupa e desorganiza antes da ultimate do ADC.",
            "iniciação", "agrupamento", "ultimate em área"),
        s("Sun Ce", "Dolia", 9, ConfiancaDado.MEDIA,
            "Reset de ultimate oferece uma segunda iniciação global decisiva.",
            "reset de ultimate", "iniciação global", "objetivos"),

        s("Ukyo Tachibana", "Kui", 9, ConfiancaDado.ALTA,
            "Gancho coloca o alvo no alcance do controle e burst de Ukyo.",
            "gancho", "controle", "explosão"),
        s("Ukyo Tachibana", "Daji", 8, ConfiancaDado.ALTA,
            "Controle garantido permite executar a sequência sem perder distância.",
            "controle garantido", "explosão", "pickoff"),
        s("Ukyo Tachibana", "Sun Bin", 8, ConfiancaDado.MEDIA,
            "Velocidade ajuda a entrar no alcance curto e sair após o combo.",
            "velocidade", "poke curto", "desengage"),

        s("Umbrosa", "Cai Yan", 9, ConfiancaDado.ALTA,
            "Cura adicional e ressurreição criam duas fases de linha de frente.",
            "cura", "ressurreição", "linha de frente"),
        s("Umbrosa", "Dolia", 9, ConfiancaDado.ALTA,
            "Sustentação em camadas prolonga muito o dano contínuo.",
            "cura", "ressurreição", "luta longa"),
        s("Umbrosa", "Zhuangzi", 8, ConfiancaDado.MEDIA,
            "Purificação impede que controle e anti-engage neguem sua presença.",
            "anti-controle", "sustentação", "linha de frente"),

        s("Wukong", "Guiguzi", 9, ConfiancaDado.ALTA,
            "Camuflagem coletiva esconde a preparação do crítico e do flanco.",
            "camuflagem", "crítico", "flanco"),
        s("Wukong", "Ming", 9, ConfiancaDado.ALTA,
            "Amplificação transforma um crítico em eliminação imediata.",
            "amplificação", "crítico", "explosão"),
        s("Wukong", "Dolia", 8, ConfiancaDado.MEDIA,
            "Nova ultimate oferece outra janela de controle e burst.",
            "reset de ultimate", "crítico", "dive"),

        s("Wuyan", "Wang Zhaojun", 9, ConfiancaDado.ALTA,
            "Petrificação prepara congelamento e tempestade em área.",
            "petrificação", "congelamento", "controle em cadeia"),
        s("Wuyan", "Marco Polo", 9, ConfiancaDado.ALTA,
            "Controle em área segura os inimigos dentro da ultimate do ADC.",
            "petrificação", "agrupamento", "ultimate em área"),
        s("Wuyan", "Cai Yan", 8, ConfiancaDado.MEDIA,
            "Cura prolonga a presença frontal enquanto busca novas petrificações.",
            "cura", "linha de frente", "controle"),

        s("Yang Jian", "Liang", 9, ConfiancaDado.ALTA,
            "Supressão permite conectar a marca, executar e recuperar vida.",
            "supressão", "execução", "sustentação"),
        s("Yang Jian", "Ming", 8, ConfiancaDado.ALTA,
            "Amplificação melhora o dano verdadeiro e a recuperação em duelo.",
            "amplificação", "dano verdadeiro", "duelo"),
        s("Yang Jian", "Sun Bin", 8, ConfiancaDado.MEDIA,
            "Velocidade mantém contato com o alvo marcado durante a perseguição.",
            "velocidade", "perseguição", "execução"),

        s("Yao", "Dolia", 9, ConfiancaDado.ALTA,
            "Reset de ultimate oferece outra janela de retorno de dano e mobilidade.",
            "reset de ultimate", "mobilidade", "combos"),
        s("Yao", "Yaria", 8, ConfiancaDado.ALTA,
            "Escudo móvel acompanha entradas e retornos do lutador.",
            "escudo", "mobilidade", "duelo"),
        s("Yao", "Da Qiao", 8, ConfiancaDado.MEDIA,
            "Macro e mobilidade criam forte pressão lateral e retirada segura.",
            "macro", "split push", "mobilidade"),

        s("Ying", "Dolia", 9, ConfiancaDado.ALTA,
            "Sustentação e nova ultimate ampliam controle e execução adaptativa.",
            "cura", "reset de ultimate", "controle"),
        s("Ying", "Zhang Fei", 8, ConfiancaDado.ALTA,
            "Linha de frente adicional libera Ying para alternar controle e dano.",
            "linha de frente", "controle", "dano sustentado"),
        s("Ying", "Shi", 8, ConfiancaDado.MEDIA,
            "Reposicionamento coloca o alvo na trajetória das sequências de lança.",
            "reposicionamento", "controle", "execução"),

        s("Zilong", "Daji", 9, ConfiancaDado.ALTA,
            "Controle garantido prepara uma entrada direta sobre o carry.",
            "controle garantido", "dive", "explosão"),
        s("Zilong", "Liu Bang", 8, ConfiancaDado.ALTA,
            "Proteção global acompanha o mergulho e aumenta a sobrevivência.",
            "proteção global", "dive", "anti-carry"),
        s("Zilong", "Zhang Fei", 8, ConfiancaDado.MEDIA,
            "Segunda linha de frente cobre a saída após a entrada no carry.",
            "linha de frente", "dive", "desengage"),

        s("Xuance", "Daji", 9, ConfiancaDado.ALTA,
            "Stun garantido prepara o gancho e o primeiro cleanup.",
            "controle garantido", "gancho", "reset"),
        s("Xuance", "Guiguzi", 9, ConfiancaDado.ALTA,
            "Agrupamento e camuflagem criam ganchos e resets em sequência.",
            "camuflagem", "agrupamento", "reset"),
        s("Xuance", "Yaria", 8, ConfiancaDado.MEDIA,
            "Escudo acompanha a perseguição depois de conectar o gancho.",
            "escudo", "gancho", "perseguição"),

        s("Yango", "Liang", 9, ConfiancaDado.MEDIA,
            "Supressão oferece tempo para posicionar marionete e completar a sequência.",
            "supressão", "marionete", "explosão"),
        s("Yango", "Guiguzi", 9, ConfiancaDado.MEDIA,
            "Camuflagem esconde tanto o assassino quanto a preparação da marionete.",
            "camuflagem", "marionete", "pickoff"),
        s("Yango", "Liu Bang", 8, ConfiancaDado.EXPLORATORIA,
            "Proteção global reduz o risco de uma sequência mecânica profunda.",
            "proteção global", "marionete", "dive")
    );

    public List<SinergiaJungleEquipe> listarTodas() {
        return sinergias;
    }

    private SinergiaJungleEquipe s(
        String jungler,
        String aliado,
        int nota,
        ConfiancaDado confianca,
        String motivo,
        String... gatilhos
    ) {
        return new SinergiaJungleEquipe(
            jungler,
            aliado,
            nota,
            confianca,
            motivo,
            List.of(gatilhos)
        );
    }
}
