package br.com.carlosdaniel.hokdraftcoach.repository;

import java.util.List;

import org.springframework.stereotype.Repository;

import br.com.carlosdaniel.hokdraftcoach.model.ConfiancaDado;
import br.com.carlosdaniel.hokdraftcoach.model.SinergiaBotLane;

@Repository
public class SinergiaBotLaneRepository {

    private final List<SinergiaBotLane> sinergias = List.of(
        s("Lian Po", "Marco Polo", 10, ConfiancaDado.ALTA,
            "O controle em área mantém alvos dentro da ultimate do Marco Polo.",
            "iniciação", "controle em área", "janela de ultimate"),
        s("Lapulapu", "Marco Polo", 9, ConfiancaDado.MEDIA,
            "Absorve a primeira resposta e cria espaço para a entrada do ADC.",
            "linha de frente", "iniciação", "proteção pós-entrada"),
        s("Sakeer", "Marco Polo", 9, ConfiancaDado.MEDIA,
            "Cura, visão e controle sustentam entradas prolongadas.",
            "sustentação", "visão", "controle"),
        s("Da Qiao", "Marco Polo", 9, ConfiancaDado.MEDIA,
            "Reposicionamento e macro ampliam a mobilidade e a pressão lateral.",
            "macro", "reposicionamento", "desengage"),
        s("Zhang Fei", "Marco Polo", 9, ConfiancaDado.ALTA,
            "Escudos e contra-iniciação deixam a ultimate mais segura.",
            "escudo", "peel", "contra-iniciação"),
        s("Yaria", "Marco Polo", 9, ConfiancaDado.ALTA,
            "Acompanha todos os deslocamentos do ADC sem quebrar o ritmo.",
            "mobilidade compartilhada", "escudo", "anti-assassino"),
        s("Dolia", "Marco Polo", 8, ConfiancaDado.ALTA,
            "O reset da ultimate cria uma segunda condição de luta em área.",
            "reset de ultimate", "sustentação", "controle"),
        s("Liu Shan", "Marco Polo", 8, ConfiancaDado.ALTA,
            "Controle em cadeia abre a luta e converte vantagem em torres.",
            "controle", "pressão de torre", "iniciação"),

        s("Yaria", "Arli", 10, ConfiancaDado.ALTA,
            "Acompanha a mobilidade extrema e reduz o risco dos reposicionamentos.",
            "mobilidade compartilhada", "escudo", "duelo"),
        s("Ming", "Arli", 9, ConfiancaDado.MEDIA,
            "Amplifica dano e cura uma atiradora capaz de escolher o combate.",
            "amplificação", "cura", "duelo"),
        s("Guiguzi", "Arli", 8, ConfiancaDado.MEDIA,
            "A iniciação furtiva entrega alvos agrupados para execução.",
            "camuflagem", "agrupamento", "execução"),

        s("Zhang Fei", "Hou Yi", 10, ConfiancaDado.ALTA,
            "Protege um ADC imóvel e encadeia controle com sua ultimate global.",
            "peel", "escudo", "controle em cadeia"),
        s("Ming", "Hou Yi", 9, ConfiancaDado.MEDIA,
            "Maximiza o dano sustentado de ataques básicos.",
            "amplificação", "velocidade de ataque", "cura"),
        s("Cai Yan", "Hou Yi", 9, ConfiancaDado.MEDIA,
            "Mantém o hipercarregador vivo em lutas front-to-back.",
            "cura", "proteção", "luta longa"),

        s("Zhang Fei", "Garo", 10, ConfiancaDado.ALTA,
            "Fornece linha de frente e peel para Garo usar o alcance máximo.",
            "linha de frente", "escudo", "desengage"),
        s("Cai Yan", "Garo", 9, ConfiancaDado.MEDIA,
            "A cura prolonga o tempo de dano da carregadora tardia.",
            "cura", "hipercarregador", "luta longa"),
        s("Ming", "Garo", 9, ConfiancaDado.MEDIA,
            "Amplifica o DPS de uma atiradora de longo alcance.",
            "amplificação", "dano sustentado", "proteção"),

        s("Zhang Fei", "Huang Zhong", 10, ConfiancaDado.MEDIA,
            "Forma uma zona defensiva ao redor da ultimate estacionária.",
            "peel", "zona defensiva", "cerco"),
        s("Cai Yan", "Huang Zhong", 9, ConfiancaDado.MEDIA,
            "Cura e controle sustentam o ADC enquanto ele permanece fixo.",
            "cura", "controle", "cerco"),
        s("Zhuangzi", "Huang Zhong", 8, ConfiancaDado.MEDIA,
            "Purificação reduz a fraqueza do ADC a controle em cadeia.",
            "anti-controle", "proteção", "cerco"),

        s("Zhang Fei", "Luban No.7", 10, ConfiancaDado.MEDIA,
            "Peel máximo para um ADC imóvel de alto dano sustentado.",
            "escudo", "desengage", "linha de frente"),
        s("Yaria", "Luban No.7", 9, ConfiancaDado.MEDIA,
            "Escudo e visão reduzem a vulnerabilidade a assassinos.",
            "escudo", "anti-assassino", "visão"),
        s("Liu Shan", "Luban No.7", 8, ConfiancaDado.MEDIA,
            "Controle frontal permite descarregar passivas e derrubar torres.",
            "controle", "pressão de torre", "front-to-back"),

        s("Da Qiao", "Di Renjie", 9, ConfiancaDado.MEDIA,
            "Pressão segura, limpeza e macro controlam o mapa sem expor o ADC.",
            "macro", "controle", "reposicionamento"),
        s("Sun Bin", "Di Renjie", 8, ConfiancaDado.MEDIA,
            "A aceleração reforça o kite e a autossuficiência.",
            "velocidade", "kite", "desengage"),
        s("Ming", "Di Renjie", 8, ConfiancaDado.MEDIA,
            "Amplifica dano sustentado e pressão constante de rota.",
            "amplificação", "dano sustentado", "cura"),
        s("Cai Yan", "Di Renjie", 8, ConfiancaDado.MEDIA,
            "Controle e recuperação tornam a rota muito estável.",
            "cura", "controle", "estabilidade"),

        s("Yaria", "Alessio", 9, ConfiancaDado.MEDIA,
            "Acompanha a mobilidade aérea e protege entradas agressivas.",
            "mobilidade compartilhada", "escudo", "explosão"),
        s("Dolia", "Alessio", 8, ConfiancaDado.MEDIA,
            "Sustentação e reset aumentam a pressão de finalização.",
            "reset de ultimate", "sustentação", "finalização"),
        s("Annette", "Alessio", 8, ConfiancaDado.MEDIA,
            "Desengage cria espaço para reposicionar e continuar o poke.",
            "desengage", "poke", "controle de área"),

        s("Ming", "Lady Sun", 9, ConfiancaDado.MEDIA,
            "Amplifica a explosão após o rolamento.",
            "amplificação", "explosão", "cura"),
        s("Da Qiao", "Lady Sun", 8, ConfiancaDado.MEDIA,
            "Mobilidade e macro permitem pressionar e sair antes da resposta.",
            "macro", "mobilidade", "pressão de torre"),
        s("Liu Shan", "Lady Sun", 8, ConfiancaDado.MEDIA,
            "Controle e pressão de torre combinam com janelas de burst.",
            "controle", "explosão", "torres"),

        s("Dolia", "Loong", 10, ConfiancaDado.MEDIA,
            "Resetar uma ultimate de alto impacto altera duas lutas seguidas.",
            "reset de ultimate", "artilharia", "sobrevivência"),
        s("Zhang Fei", "Loong", 9, ConfiancaDado.MEDIA,
            "Linha de frente deixa Loong usar toda a artilharia com segurança.",
            "peel", "linha de frente", "artilharia"),
        s("Da Qiao", "Loong", 8, ConfiancaDado.MEDIA,
            "Reposicionamento complementa alcance e flexibilidade.",
            "macro", "reposicionamento", "controle"),

        s("Mozi", "Shouyue", 10, ConfiancaDado.ALTA,
            "Duas ameaças de longa distância encadeiam controle e precisão.",
            "artilharia", "controle à distância", "poke"),
        s("Kui", "Shouyue", 9, ConfiancaDado.MEDIA,
            "O gancho entrega um alvo parado para o tiro de precisão.",
            "pickoff", "gancho", "explosão"),
        s("Da Qiao", "Shouyue", 8, ConfiancaDado.MEDIA,
            "Controle de corredores amplia a zona de ameaça do sniper.",
            "macro", "zoneamento", "artilharia"),

        s("Ming", "Meng Ya", 9, ConfiancaDado.MEDIA,
            "Amplificação aumenta o volume de dano e a pressão precoce.",
            "amplificação", "dano sustentado", "pressão"),
        s("Cai Yan", "Meng Ya", 8, ConfiancaDado.MEDIA,
            "Cura permite manter o avanço durante o alto volume de tiros.",
            "cura", "pressão", "luta longa"),
        s("Sun Bin", "Meng Ya", 8, ConfiancaDado.MEDIA,
            "Velocidade ajuda a manter distância e reposicionar o DPS.",
            "velocidade", "kite", "dano sustentado"),

        s("Ming", "Erin", 8, ConfiancaDado.MEDIA,
            "Amplifica um ADC mágico móvel e dificulta itemização defensiva.",
            "amplificação", "dano mágico", "mobilidade"),
        s("Dolia", "Erin", 8, ConfiancaDado.MEDIA,
            "Sustentação prolonga o dano mágico contínuo.",
            "sustentação", "controle", "dano sustentado"),
        s("Sun Bin", "Erin", 8, ConfiancaDado.MEDIA,
            "Aceleração combina com kite e mobilidade natural.",
            "velocidade", "kite", "mobilidade"),

        s("Liu Shan", "Fang", 9, ConfiancaDado.MEDIA,
            "Pressão precoce, explosão e dano a torres criam snowball.",
            "pressão de torre", "explosão", "início de jogo"),
        s("Guiguzi", "Fang", 9, ConfiancaDado.MEDIA,
            "Agrupa alvos para a marca e o dano explosivo.",
            "agrupamento", "explosão", "rotação"),
        s("Donghuang", "Fang", 8, ConfiancaDado.MEDIA,
            "Supressão garante tempo para aplicar e detonar a marca.",
            "supressão", "pickoff", "explosão"),

        s("Yaria", "Luara", 9, ConfiancaDado.MEDIA,
            "Acompanha travessias de terreno e protege a carregadora móvel.",
            "mobilidade compartilhada", "escudo", "fim de jogo"),
        s("Ming", "Luara", 8, ConfiancaDado.MEDIA,
            "Amplifica dano contínuo e escalamento tardio.",
            "amplificação", "dano sustentado", "cura"),
        s("Zhang Fei", "Luara", 8, ConfiancaDado.MEDIA,
            "Peel cria espaço para atravessar terreno e continuar atacando.",
            "peel", "linha de frente", "mobilidade"),

        s("Mozi", "Chano", 9, ConfiancaDado.MEDIA,
            "Controle e artilharia sobrepostos pressionam antes da luta.",
            "artilharia", "controle", "poke"),
        s("Da Qiao", "Chano", 8, ConfiancaDado.MEDIA,
            "Macro favorece iniciação e finalização de longa distância.",
            "macro", "zoneamento", "finalização"),
        s("Dolia", "Chano", 8, ConfiancaDado.MEDIA,
            "Reset amplia a capacidade de iniciar ou finalizar duas vezes.",
            "reset de ultimate", "artilharia", "finalização"),

        s("Ming", "Consorte Yu", 8, ConfiancaDado.MEDIA,
            "Amplificação complementa proteção física e poke.",
            "amplificação", "poke", "proteção"),
        s("Da Qiao", "Consorte Yu", 8, ConfiancaDado.MEDIA,
            "A dupla controla distância e se reposiciona com segurança.",
            "macro", "poke", "reposicionamento"),
        s("Zhang Fei", "Consorte Yu", 8, ConfiancaDado.MEDIA,
            "Proteção mista contra dive físico e controle frontal.",
            "peel", "escudo", "controle"),

        s("Dyadia", "Ser do Fluxo (Atirador)", 9, ConfiancaDado.EXPLORATORIA,
            "Cura e mobilidade combinam com um ADC adaptável.",
            "mobilidade", "cura", "escaramuça"),
        s("Zhang Fei", "Ser do Fluxo (Atirador)", 8, ConfiancaDado.EXPLORATORIA,
            "Linha de frente permite adaptar a postura sem perder proteção.",
            "peel", "linha de frente", "adaptação"),
        s("Sakeer", "Ser do Fluxo (Atirador)", 8, ConfiancaDado.EXPLORATORIA,
            "Visão e sustentação favorecem lutas móveis.",
            "visão", "cura", "mobilidade"),

        s("Sakeer", "Agu", 8, ConfiancaDado.EXPLORATORIA,
            "A dupla forma uma linha resistente com cura e utilidade.",
            "sustentação", "visão", "utilidade"),
        s("Dyadia", "Agu", 8, ConfiancaDado.EXPLORATORIA,
            "Pressão de rota e cura ampliam o valor utilitário no início.",
            "cura", "pressão", "início de jogo"),

        s("Zhang Fei", "Chicha", 8, ConfiancaDado.EXPLORATORIA,
            "Peel permite manter ataques contínuos em alcance curto.",
            "peel", "dano sustentado", "linha de frente"),
        s("Dyadia", "Chicha", 8, ConfiancaDado.EXPLORATORIA,
            "Cura e mobilidade sustentam duelos e perseguições.",
            "cura", "mobilidade", "duelo")
    );

    public List<SinergiaBotLane> listarTodas() {
        return sinergias;
    }

    private SinergiaBotLane s(
        String suporte,
        String atirador,
        int nota,
        ConfiancaDado confianca,
        String motivo,
        String... gatilhos
    ) {
        return new SinergiaBotLane(
            suporte,
            atirador,
            nota,
            confianca,
            motivo,
            List.of(gatilhos)
        );
    }
}
