package br.com.carlosdaniel.hokdraftcoach.model;

public enum TipoRespostaCondicaoVitoria {
    ACESSAR_E_ELIMINAR_CARREGADOR,
    SEPARAR_CARREGADOR_DO_AMPLIFICADOR,
    QUEBRAR_FORMACAO_DA_LINHA_DE_FRENTE,
    FORCAR_LUTAS_CURTAS,
    APLICAR_ANTI_CURA,
    ENGAGE_SOBRE_POKE,
    FLANQUEAR_ARTILHARIA,
    RESPONDER_PRESSAO_LATERAL,
    FORCAR_OBJETIVO_DO_LADO_OPOSTO,
    INTERROMPER_INICIADOR,
    ESPALHAR_FORMACAO,
    PROTEGER_RETAGUARDA,
    NEGAR_RECURSOS,
    ACELERAR_O_JOGO,
    CRIAR_PICKOFF_ANTES_DO_OBJETIVO
}
